This is SBCL 1.2.4.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
; compiling file "/home/fmbiased/zot/trunk/asdfs/ae2zot.lisp" (written 28 JAN 2016 11:24:19 AM):
; compiling (IN-PACKAGE :CL-USER)
; compiling (DEFPACKAGE :AE2ZOT ...)
; compiling (IN-PACKAGE :AE2ZOT)
; compiling (DEFVAR *REAL-CONSTANTS* ...)
; compiling (DEFMACRO IN ...)
; compiling (DEFUN PREDICATEP ...)
; compiling (DECLAIM (INLINE PREDICATEP))
; compiling (DEFUN CLTL-FORMULAP ...)
; compiling (DECLAIM (INLINE CLTL-FORMULAP))
; compiling (DEFUN LTL-FORMULAP ...)
; compiling (DECLAIM (INLINE LTL-FORMULAP))
; compiling (DEFUN ARITH-COP ...)
; compiling (DECLAIM (INLINE ARITH-COP))
; compiling (DEFUN ARITH-OPP ...)
; compiling (DECLAIM (INLINE ARITH-OPP))
; compiling (DEFUN ARITH-ITEMP ...)
; compiling (DECLAIM (INLINE ARITH-ITEMP))
; compiling (DEFUN BOOL-FMLAP ...)
; compiling (DECLAIM (INLINE BOOL-ITEMP))
; compiling (DEFUN TEMP-FMLAP ...)
; compiling (DECLAIM (INLINE TEMP-FMLAP))
; compiling (DEFUN GET-ITEM-CODOM ...)
; compiling (DEFUN GET-ITEM-SIG ...)
; compiling (DEFUN GET-ITEM-SORT ...)
; compiling (DEFUN ARITY ...)
; compiling (DEFUN DENEG ...)
; compiling (DEFUN TO-SMT-DIALECT ...)
; compiling (DEFVAR *PROPS* ...)
; compiling (DEFCLASS AE2ZOT-KRIPKE ...)
; compiling (DEFUN MAKE-KRIPKE ...)
; compiling (DEFMETHOD CALL ...)
; compiling (DEFGENERIC CALL-FMLA-ID ...)
; compiling (DEFMETHOD CALL-FMLA-ID ...)
; compiling (DEFUN THE-LOOPEX ...)
; compiling (DEFUN THE-ILOOP ...)
; compiling (DEFUN LOOPFREE ...)
; compiling (DEFUN LOOPCONSTRAINTS ...)
; compiling (DEFUN GEN-BOOL ...)
; compiling (DEFUN GEN-FUTR ...)
; compiling (DEFUN GEN-ARITH-FUTR ...)
; compiling (DEFUN LASTSTATEFORMULA ...)
; compiling (DEFUN GEN-EVT-FUTR ...)
; compiling (DEFUN STABILIZE-CONSTANTS ...)
; compiling (DEFUN GEN-PAST1 ...)
; compiling (DEFUN GEN-PAST2 ...)
; compiling (DEFUN GEN-ARITH-PAST ...)
; compiling (DEFUN GEN-I-ATOMIC-FORMULAE ...)
; compiling (DEFUN GEN-ARITH-CONSTRAINTS ...)
; compiling (DEFUN GEN-EXISTENCE-CONDITION ...)
; compiling (DEFUN GEN-PERIODIC-ARITH-TERMS ...)
; compiling (DEFUN GEN-REGIONS ...)
; compiling (DEFUN THE-BIG-FORMULA ...)
; compiling (DEFUN MANAGE-TRANSITIONS ...)
; compiling (DEFUN PRN-STR ...)
; compiling (DEFUN ZOT ...)
; compiling (DEFUN DECLARE-ASSUMPTIONS ...)

; /home/fmbiased/.cache/common-lisp/sbcl-1.2.4.debian-linux-x64/home/fmbiased/zot/trunk/asdfs/ae2zot-TMP.fasl written
; compilation finished in 0:00:00.474
IPC-terms: ((YESTERDAY SDSENDSENSORDISTANCEPARDISTANCE)
            OBJBUSPARAMRECEIVEDDISTANCE SDSENDSENSORDISTANCEPARDISTANCE
            OBJCTRLPARAMRECEIVEDDISTANCE 2)
IPC-constraints: ((< SDSENDSENSORDISTANCEPARDISTANCE 2)
                  (= SDSENDSENSORDISTANCEPARDISTANCE
                     (YESTERDAY SDSENDSENSORDISTANCEPARDISTANCE))
                  (= SDSENDSENSORDISTANCEPARDISTANCE
                     OBJBUSPARAMRECEIVEDDISTANCE)
                  (= SDSENDSENSORDISTANCEPARDISTANCE
                     OBJCTRLPARAMRECEIVEDDISTANCE)
                  (< OBJCTRLPARAMRECEIVEDDISTANCE 2)
                  (>= OBJCTRLPARAMRECEIVEDDISTANCE 2))
This is SMT-Arithmetic-eeZot

1. processing formula
Used boolean propositions: 
((< SDSENDSENSORDISTANCEPARDISTANCE 2) IOD_PNSFKAN_EEKTXBQZTILH3G_END
 IOD_PNSFKAN_EEKTXBQZTILH3G_START
 (= SDSENDSENSORDISTANCEPARDISTANCE
    (YESTERDAY SDSENDSENSORDISTANCEPARDISTANCE))
 SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
 (= SDSENDSENSORDISTANCEPARDISTANCE OBJBUSPARAMRECEIVEDDISTANCE)
 MESSAGE_IJQC4AOAEEKTXBQZTILH3G
 (= SDSENDSENSORDISTANCEPARDISTANCE OBJCTRLPARAMRECEIVEDDISTANCE)
 MESSAGE_LZQ5WAOBEEKTXBQZTILH3G MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
 MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
 IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
 IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START SENDSENSORDISTANCE_END
 SENDSENSORDISTANCE_STOP SENDSENSORDISTANCE_START SDSENDSENSORDISTANCE
 SDSENDBRAKECOMMAND_TIMECONSTRAINT_1 MESSAGE_FOVPUAOCEEKTXBQZTILH3G
 MESSAGE_I36JSAOCEEKTXBQZTILH3G MESSAGE_I36JSAOCEEKTXBQZTILH3G_START
 MESSAGE_FOVPUAOCEEKTXBQZTILH3G_START
 IOD__PNSFKAN_EEKTXBQZTILH3G_SENDBRAKECOMMAND_END
 IOD__PNSFKAN_EEKTXBQZTILH3G_SENDBRAKECOMMAND_START SENDBRAKECOMMAND_END
 SENDBRAKECOMMAND_STOP SENDBRAKECOMMAND_START SDSENDBRAKECOMMAND
 MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END OBJBUSOPSENDSENSORDISTANCE
 MESSAGE_FOVPUAOCEEKTXBQZTILH3G_END OBJBUSOPSENDBRAKECOMMAND
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G_TIMECONDITION
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G_TRIGGER
 (< OBJCTRLPARAMRECEIVEDDISTANCE 2)
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
 (>= OBJCTRLPARAMRECEIVEDDISTANCE 2)
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
 OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
 OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
 $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G
 OBJCTRL_STDSTATEMACHINE1_STATEBRAKING_EXIT
 OBJCTRL_STDSTATEMACHINE1_STATEBRAKING_ENTER
 $OBJCTRL_STDSTATEMACHINE1_STATEBRAKING
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G
 OBJCTRL_STDSTATEMACHINE1_STATEWARNING_EXIT
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
 OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
 $OBJCTRL_STDSTATEMACHINE1_STATEWARNING MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
 OBJCTRLOPNOTIFYDISTANCE
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION__APEGAOCEEKTXBQZTILH3G_TRIGGER
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G_TIMECONDITION
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G_TRIGGER
 OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_EXIT
 OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_ENTER
 $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G
 OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING_EXIT
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION__APEGAOCEEKTXBQZTILH3G
 OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING_ENTER
 $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING MESSAGE_I36JSAOCEEKTXBQZTILH3G_END
 OBJBRAKESOPNOTIFYBRAKE
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G BRAKEINTERRUPT
 RADARCLOCKTICK MADESYSTEMSTART)

Used arithmetic terms: 
NIL

Used timed arithmetic terms: 
(OBJBUSPARAMRECEIVEDDISTANCE SDSENDSENSORDISTANCEPARDISTANCE
 OBJCTRLPARAMRECEIVEDDISTANCE)

Graph dependency over terms 
((2 2 OBJCTRLPARAMRECEIVEDDISTANCE OBJBUSPARAMRECEIVEDDISTANCE 2
  SDSENDSENSORDISTANCEPARDISTANCE (YESTERDAY SDSENDSENSORDISTANCEPARDISTANCE)))

Related variables 
((OBJCTRLPARAMRECEIVEDDISTANCE OBJBUSPARAMRECEIVEDDISTANCE 2
  SDSENDSENSORDISTANCEPARDISTANCE))

Time bound: 200
define loop constraints
define LTL boolean connectives
define LTL future formulae X, U, R
define last state contraints
define eventuality for LTL future modalities U,R
gen-past1...
gen-past2...
define FO future formulae Xt
define FO future formulae Yt
define for interpreted relations: <,>,=,<=,>= 
define FO terms for +,-,*,/,mod 
define existence condition for Integers

done processing formula

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  27.043 seconds of real time
  0.000000 seconds of total run time (0.000000 user, 0.000000 system)
  0.00% CPU
  91,945,739,289 processor cycles
  32,640 bytes consed
  
---SAT---
LOOPEX = TRUE
I_LOOP = 161
------ time 0 ------
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  IOD_PNSFKAN_EEKTXBQZTILH3G_START
  MADESYSTEMSTART
OBJBUSPARAMRECEIVEDDISTANCE = 202.0
SDSENDSENSORDISTANCEPARDISTANCE = 2.0
------ time 1 ------
  OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_ENTER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  OBJBUSOPSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 1.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 2 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 203.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 3 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 204.0
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 4 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
OBJBUSPARAMRECEIVEDDISTANCE = 205.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 5 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 206.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 6 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 207.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 7 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 208.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 8 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 209.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 9 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 210.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 10 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 211.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 11 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  OBJBUSOPSENDSENSORDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 0.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 12 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 212.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 13 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 213.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 14 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 214.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 15 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 215.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 16 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 216.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 17 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 217.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 18 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 218.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 19 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 219.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 20 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 220.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 21 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -5.0
  OBJBUSOPSENDSENSORDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 1.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 22 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 221.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 23 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 222.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 24 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 223.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 25 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 224.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 26 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 225.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 27 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 226.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 28 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 227.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 29 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -3.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 228.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 30 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 229.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 31 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  OBJBUSOPSENDSENSORDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = -1.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 32 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 230.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 33 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 231.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 34 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 232.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 35 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 233.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 36 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 234.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 37 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 235.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 38 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 236.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 39 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 237.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 40 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 238.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 41 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -4.0
  OBJBUSOPSENDSENSORDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 0.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 42 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 239.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 43 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  BRAKEINTERRUPT
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G
OBJBUSPARAMRECEIVEDDISTANCE = 240.0
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_EXIT
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 44 ------
  SDSENDBRAKECOMMAND_TIMECONSTRAINT_1
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_FOVPUAOCEEKTXBQZTILH3G_END
OBJCTRLPARAMRECEIVEDDISTANCE = -5.0
  MESSAGE_FOVPUAOCEEKTXBQZTILH3G
  SDSENDBRAKECOMMAND
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDBRAKECOMMAND_START
  SENDSENSORDISTANCE_START
  $OBJCTRL_STDSTATEMACHINE1_STATEBRAKING
  OBJBUSOPSENDBRAKECOMMAND
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 241.0
  SENDBRAKECOMMAND_START
  MESSAGE_FOVPUAOCEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_STATEBRAKING_ENTER
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 45 ------
  SDSENDBRAKECOMMAND_TIMECONSTRAINT_1
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  OBJCTRL_STDSTATEMACHINE1_STATEBRAKING_EXIT
  SDSENDBRAKECOMMAND
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G_TIMECONDITION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G_TRIGGER
  $OBJCTRL_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 242.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 46 ------
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION__APEGAOCEEKTXBQZTILH3G_TRIGGER
  SDSENDBRAKECOMMAND_TIMECONSTRAINT_1
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION__APEGAOCEEKTXBQZTILH3G
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  MESSAGE_I36JSAOCEEKTXBQZTILH3G
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  OBJBRAKESOPNOTIFYBRAKE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SENDBRAKECOMMAND_END
  MESSAGE_I36JSAOCEEKTXBQZTILH3G_END
  SDSENDBRAKECOMMAND
  MESSAGE_I36JSAOCEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
  SDSENDSENSORDISTANCE
  OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_EXIT
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 243.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDBRAKECOMMAND_END
------ time 47 ------
  OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING_ENTER
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 244.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 48 ------
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 245.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 49 ------
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 246.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 50 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 247.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 51 ------
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  OBJBUSOPSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = -1.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 52 ------
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 248.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 53 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 249.0
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 54 ------
OBJCTRLPARAMRECEIVEDDISTANCE = -3.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
OBJBUSPARAMRECEIVEDDISTANCE = 250.0
SDSENDSENSORDISTANCEPARDISTANCE = -2.0
------ time 55 ------
OBJCTRLPARAMRECEIVEDDISTANCE = -3.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 251.0
SDSENDSENSORDISTANCEPARDISTANCE = -2.0
------ time 56 ------
OBJCTRLPARAMRECEIVEDDISTANCE = -3.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 252.0
SDSENDSENSORDISTANCEPARDISTANCE = -2.0
------ time 57 ------
  OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING_EXIT
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G
OBJCTRLPARAMRECEIVEDDISTANCE = -3.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G_TRIGGER
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G_TIMECONDITION
OBJBUSPARAMRECEIVEDDISTANCE = 253.0
SDSENDSENSORDISTANCEPARDISTANCE = -2.0
------ time 58 ------
  OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_ENTER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -3.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 254.0
SDSENDSENSORDISTANCEPARDISTANCE = -2.0
------ time 59 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -3.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 255.0
SDSENDSENSORDISTANCEPARDISTANCE = -2.0
------ time 60 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -3.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 256.0
SDSENDSENSORDISTANCEPARDISTANCE = -2.0
------ time 61 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -3.0
  OBJBUSOPSENDSENSORDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = -2.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = -2.0
------ time 62 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 257.0
SDSENDSENSORDISTANCEPARDISTANCE = -2.0
------ time 63 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 258.0
SDSENDSENSORDISTANCEPARDISTANCE = -2.0
------ time 64 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 259.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 65 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 260.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 66 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 261.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 67 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 262.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 68 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 263.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 69 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 264.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 70 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 265.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 71 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  OBJBUSOPSENDSENSORDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = -1.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 72 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 266.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 73 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 267.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 74 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 268.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 75 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 269.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 76 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 270.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 77 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 271.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 78 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 272.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 79 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 273.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 80 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 274.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 81 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -10.0
  OBJBUSOPSENDSENSORDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 0.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 82 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 275.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 83 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 276.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 84 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 277.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 85 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 278.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 86 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 279.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 87 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 280.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 88 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 281.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 89 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 282.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 90 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 283.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 91 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  OBJBUSOPSENDSENSORDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = -1.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 92 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 284.0
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 93 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  BRAKEINTERRUPT
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G
OBJBUSPARAMRECEIVEDDISTANCE = 285.0
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_EXIT
SDSENDSENSORDISTANCEPARDISTANCE = -1.0
------ time 94 ------
  SDSENDBRAKECOMMAND_TIMECONSTRAINT_1
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_FOVPUAOCEEKTXBQZTILH3G_END
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  MESSAGE_FOVPUAOCEEKTXBQZTILH3G
  SDSENDBRAKECOMMAND
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDBRAKECOMMAND_START
  SENDSENSORDISTANCE_START
  $OBJCTRL_STDSTATEMACHINE1_STATEBRAKING
  OBJBUSOPSENDBRAKECOMMAND
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 286.0
  SENDBRAKECOMMAND_START
  MESSAGE_FOVPUAOCEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_STATEBRAKING_ENTER
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 95 ------
  SDSENDBRAKECOMMAND_TIMECONSTRAINT_1
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_STATEBRAKING_EXIT
  SDSENDBRAKECOMMAND
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G_TIMECONDITION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G_TRIGGER
  $OBJCTRL_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 287.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 96 ------
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION__APEGAOCEEKTXBQZTILH3G_TRIGGER
  SDSENDBRAKECOMMAND_TIMECONSTRAINT_1
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION__APEGAOCEEKTXBQZTILH3G
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  MESSAGE_I36JSAOCEEKTXBQZTILH3G
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  OBJBRAKESOPNOTIFYBRAKE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SENDBRAKECOMMAND_END
  MESSAGE_I36JSAOCEEKTXBQZTILH3G_END
  SDSENDBRAKECOMMAND
  MESSAGE_I36JSAOCEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
  SDSENDSENSORDISTANCE
  OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_EXIT
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 288.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDBRAKECOMMAND_END
------ time 97 ------
  OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING_ENTER
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 289.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 98 ------
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 290.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 99 ------
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 291.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 100 ------
OBJCTRLPARAMRECEIVEDDISTANCE = -5.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 292.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 101 ------
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  OBJBUSOPSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 0.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 102 ------
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 293.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 103 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 294.0
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 104 ------
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
OBJBUSPARAMRECEIVEDDISTANCE = 295.0
SDSENDSENSORDISTANCEPARDISTANCE = 2.0
------ time 105 ------
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 296.0
SDSENDSENSORDISTANCEPARDISTANCE = 2.0
------ time 106 ------
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 297.0
SDSENDSENSORDISTANCEPARDISTANCE = 2.0
------ time 107 ------
  OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING_EXIT
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G_TRIGGER
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G_TIMECONDITION
OBJBUSPARAMRECEIVEDDISTANCE = 298.0
SDSENDSENSORDISTANCEPARDISTANCE = 2.0
------ time 108 ------
  OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_ENTER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 3.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 299.0
SDSENDSENSORDISTANCEPARDISTANCE = 2.0
------ time 109 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 300.0
SDSENDSENSORDISTANCEPARDISTANCE = 2.0
------ time 110 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 301.0
SDSENDSENSORDISTANCEPARDISTANCE = 2.0
------ time 111 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJBUSOPSENDSENSORDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 2.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 2.0
------ time 112 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 302.0
SDSENDSENSORDISTANCEPARDISTANCE = 2.0
------ time 113 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 303.0
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_EXIT
SDSENDSENSORDISTANCEPARDISTANCE = 2.0
------ time 114 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 304.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 115 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 305.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 116 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 306.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 117 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 307.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 118 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 308.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 119 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 309.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 120 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 310.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 121 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJBUSOPSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 0.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 122 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 311.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 123 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 312.0
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 124 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
OBJBUSPARAMRECEIVEDDISTANCE = 313.0
SDSENDSENSORDISTANCEPARDISTANCE = 9.0
------ time 125 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 314.0
SDSENDSENSORDISTANCEPARDISTANCE = 9.0
------ time 126 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 10.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 315.0
SDSENDSENSORDISTANCEPARDISTANCE = 9.0
------ time 127 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 316.0
SDSENDSENSORDISTANCEPARDISTANCE = 9.0
------ time 128 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 317.0
SDSENDSENSORDISTANCEPARDISTANCE = 9.0
------ time 129 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 318.0
SDSENDSENSORDISTANCEPARDISTANCE = 9.0
------ time 130 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 10.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 319.0
SDSENDSENSORDISTANCEPARDISTANCE = 9.0
------ time 131 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJBUSOPSENDSENSORDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 9.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 9.0
------ time 132 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 320.0
SDSENDSENSORDISTANCEPARDISTANCE = 9.0
------ time 133 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 9.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 321.0
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_EXIT
SDSENDSENSORDISTANCEPARDISTANCE = 9.0
------ time 134 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 322.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 135 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 323.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 136 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 324.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 137 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 325.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 138 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 326.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 139 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 7.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 327.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 140 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 7.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 328.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 141 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJBUSOPSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 6.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 142 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 7.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 329.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 143 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = 6.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 330.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 144 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 331.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 145 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 332.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 146 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 333.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 147 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 334.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 148 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 335.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 149 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 336.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 150 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 337.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 151 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJBUSOPSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 0.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 152 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 338.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 153 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 339.0
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 154 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
OBJBUSPARAMRECEIVEDDISTANCE = 340.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 155 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 341.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 156 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 7.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 342.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 157 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 343.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 158 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 7.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 344.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 159 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 5.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 160 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 7.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 8.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 161 ------
  **LOOP**
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJBUSOPSENDSENSORDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 6.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 162 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 345.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 163 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 6.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 346.0
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_EXIT
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 164 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 347.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 165 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 348.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 166 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 349.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 167 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 350.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 168 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 351.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 169 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 352.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 170 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 353.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 171 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  OBJBUSOPSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 1.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 172 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 354.0
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 173 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 355.0
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
SDSENDSENSORDISTANCEPARDISTANCE = 1.0
------ time 174 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
OBJBUSPARAMRECEIVEDDISTANCE = 356.0
SDSENDSENSORDISTANCEPARDISTANCE = 14.0
------ time 175 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 15.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 357.0
SDSENDSENSORDISTANCEPARDISTANCE = 14.0
------ time 176 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 358.0
SDSENDSENSORDISTANCEPARDISTANCE = 14.0
------ time 177 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 359.0
SDSENDSENSORDISTANCEPARDISTANCE = 14.0
------ time 178 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 360.0
SDSENDSENSORDISTANCEPARDISTANCE = 14.0
------ time 179 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 361.0
SDSENDSENSORDISTANCEPARDISTANCE = 14.0
------ time 180 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 15.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 362.0
SDSENDSENSORDISTANCEPARDISTANCE = 14.0
------ time 181 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  OBJBUSOPSENDSENSORDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 14.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 14.0
------ time 182 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 363.0
SDSENDSENSORDISTANCEPARDISTANCE = 14.0
------ time 183 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 14.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 364.0
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_EXIT
SDSENDSENSORDISTANCEPARDISTANCE = 14.0
------ time 184 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 365.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 185 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 366.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 186 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 367.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 187 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 368.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 188 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 369.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 189 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 370.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 190 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 371.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 191 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJBUSOPSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 0.0
  RADARCLOCKTICK
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 192 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 372.0
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 193 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
OBJCTRLPARAMRECEIVEDDISTANCE = 0.0
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SENDSENSORDISTANCE_END
  OBJCTRLOPNOTIFYDISTANCE
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 373.0
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
SDSENDSENSORDISTANCEPARDISTANCE = 0.0
------ time 194 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 2.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
OBJBUSPARAMRECEIVEDDISTANCE = 374.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 195 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = -5.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 375.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 196 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 7.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 376.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 197 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 7.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 377.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 198 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 9.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 378.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 199 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
OBJCTRLPARAMRECEIVEDDISTANCE = 1.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 5.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ time 200 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
OBJCTRLPARAMRECEIVEDDISTANCE = 7.0
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
OBJBUSPARAMRECEIVEDDISTANCE = 8.0
SDSENDSENSORDISTANCEPARDISTANCE = 6.0
------ end ------
Evaluation took:
  28.905 seconds of real time
  1.868000 seconds of total run time (1.856000 user, 0.012000 system)
  [ Run times consist of 0.100 seconds GC time, and 1.768 seconds non-GC time. ]
  6.46% CPU
  484 forms interpreted
  98,279,266,413 processor cycles
  129,562,112 bytes consed
  
