This is SBCL 1.2.4.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
IPC-terms: ((YESTERDAY SDSENDSENSORDISTANCEPARDISTANCE)
            OBJBUSPARAMRECEIVEDDISTANCE SDSENDSENSORDISTANCEPARDISTANCE
            OBJCTRLPARAMRECEIVEDDISTANCE 2)
IPC-constraints: ((= SDSENDSENSORDISTANCEPARDISTANCE
                     (YESTERDAY SDSENDSENSORDISTANCEPARDISTANCE))
                  (= SDSENDSENSORDISTANCEPARDISTANCE
                     OBJBUSPARAMRECEIVEDDISTANCE)
                  (= SDSENDSENSORDISTANCEPARDISTANCE
                     OBJCTRLPARAMRECEIVEDDISTANCE)
                  (< OBJCTRLPARAMRECEIVEDDISTANCE 2)
                  (>= OBJCTRLPARAMRECEIVEDDISTANCE 2))
This is AE2SBVZOT.

1. processing formula
Used boolean propositions: 
(IOD_PNSFKAN_EEKTXBQZTILH3G_END IOD_PNSFKAN_EEKTXBQZTILH3G_START
 (= SDSENDSENSORDISTANCEPARDISTANCE
    (YESTERDAY SDSENDSENSORDISTANCEPARDISTANCE))
 SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
 (= SDSENDSENSORDISTANCEPARDISTANCE OBJBUSPARAMRECEIVEDDISTANCE)
 MESSAGE_IJQC4AOAEEKTXBQZTILH3G
 (= SDSENDSENSORDISTANCEPARDISTANCE OBJCTRLPARAMRECEIVEDDISTANCE)
 MESSAGE_LZQ5WAOBEEKTXBQZTILH3G MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
 MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
 IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
 IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START SENDSENSORDISTANCE_END
 SENDSENSORDISTANCE_STOP SENDSENSORDISTANCE_START SDSENDSENSORDISTANCE
 SDSENDBRAKECOMMAND_TIMECONSTRAINT_1 MESSAGE_FOVPUAOCEEKTXBQZTILH3G
 MESSAGE_I36JSAOCEEKTXBQZTILH3G MESSAGE_I36JSAOCEEKTXBQZTILH3G_START
 MESSAGE_FOVPUAOCEEKTXBQZTILH3G_START
 IOD__PNSFKAN_EEKTXBQZTILH3G_SENDBRAKECOMMAND_END
 IOD__PNSFKAN_EEKTXBQZTILH3G_SENDBRAKECOMMAND_START SENDBRAKECOMMAND_END
 SENDBRAKECOMMAND_STOP SENDBRAKECOMMAND_START SDSENDBRAKECOMMAND
 MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END OBJBUSOPSENDSENSORDISTANCE
 MESSAGE_FOVPUAOCEEKTXBQZTILH3G_END OBJBUSOPSENDBRAKECOMMAND
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER T
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G_TIMECONDITION
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G_TRIGGER
 (< OBJCTRLPARAMRECEIVEDDISTANCE 2)
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
 (>= OBJCTRLPARAMRECEIVEDDISTANCE 2)
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
 OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
 OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
 $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G
 OBJCTRL_STDSTATEMACHINE1_STATEBRAKING_EXIT
 OBJCTRL_STDSTATEMACHINE1_STATEBRAKING_ENTER
 $OBJCTRL_STDSTATEMACHINE1_STATEBRAKING
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G
 OBJCTRL_STDSTATEMACHINE1_STATEWARNING_EXIT
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
 OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
 $OBJCTRL_STDSTATEMACHINE1_STATEWARNING MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
 OBJCTRLOPNOTIFYDISTANCE
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION__APEGAOCEEKTXBQZTILH3G_TRIGGER
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G_TIMECONDITION
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G_TRIGGER
 OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_EXIT
 OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_ENTER
 $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G
 OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING_EXIT
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION__APEGAOCEEKTXBQZTILH3G
 OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING_ENTER
 $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING MESSAGE_I36JSAOCEEKTXBQZTILH3G_END
 OBJBRAKESOPNOTIFYBRAKE
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G BRAKEINTERRUPT
 RADARCLOCKTICK MADESYSTEMSTART)

Used arithmetic terms: 
NIL

Used timed arithmetic terms: 
(OBJBUSPARAMRECEIVEDDISTANCE SDSENDSENSORDISTANCEPARDISTANCE
 OBJCTRLPARAMRECEIVEDDISTANCE)

Graph dependency over terms 
((2 2 OBJCTRLPARAMRECEIVEDDISTANCE OBJBUSPARAMRECEIVEDDISTANCE
  SDSENDSENSORDISTANCEPARDISTANCE (YESTERDAY SDSENDSENSORDISTANCEPARDISTANCE)))

Related variables 
((2 OBJCTRLPARAMRECEIVEDDISTANCE OBJBUSPARAMRECEIVEDDISTANCE
  SDSENDSENSORDISTANCEPARDISTANCE))

Time bound: 200

Number of Boolean variables: 
71
define FO future formulae Xt
define FO future formulae Yt
define for interpreted relations: <,>,=,<=,>= 
define FO terms for +,-,*,/,mod 
define loop constraints

done processing formula
define LTL future formulae X, U, R
define LTL future formulae X, U, R
gen-past2...
gen-past2...
define LTL boolean connectives
define LTL boolean connectives

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  11.167 seconds of real time
  0.000000 seconds of total run time (0.000000 user, 0.000000 system)
  0.00% CPU
  37,966,442,204 processor cycles
  0 bytes consed
  
---SAT---
------ time 0 ------
  IOD_PNSFKAN_EEKTXBQZTILH3G_START
  MADESYSTEMSTART
  OBJBUSPARAMRECEIVEDDISTANCE = 2
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
------ time 1 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_ENTER
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 0
  SDSENDSENSORDISTANCEPARDISTANCE = 0
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
------ time 2 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 11
  SDSENDSENSORDISTANCEPARDISTANCE = 0
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
------ time 3 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 12
  SDSENDSENSORDISTANCEPARDISTANCE = 0
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 4 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 13
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 5 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 14
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
------ time 6 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 15
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 7 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 16
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 8 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 17
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 9 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 18
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 10 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 19
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 11 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = (- 1)
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 12 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 20
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
------ time 13 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 21
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
------ time 14 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 22
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 15 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 23
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
------ time 16 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 24
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 17 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 25
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 18 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 26
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
------ time 19 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 27
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
------ time 20 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 28
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
------ time 21 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = (- 2)
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
------ time 22 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 29
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
------ time 23 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 30
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 2)
------ time 24 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 31
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 2)
------ time 25 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 32
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 4)
------ time 26 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 33
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 27 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 34
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 2)
------ time 28 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 35
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 29 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 36
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 4)
------ time 30 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 37
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 2)
------ time 31 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = (- 3)
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 4)
------ time 32 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 38
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 4)
------ time 33 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 39
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
------ time 34 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 40
  SDSENDSENSORDISTANCEPARDISTANCE = (- 4)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 35 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 41
  SDSENDSENSORDISTANCEPARDISTANCE = (- 4)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
------ time 36 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 42
  SDSENDSENSORDISTANCEPARDISTANCE = (- 4)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 5)
------ time 37 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 43
  SDSENDSENSORDISTANCEPARDISTANCE = (- 4)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
------ time 38 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 44
  SDSENDSENSORDISTANCEPARDISTANCE = (- 4)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
------ time 39 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 45
  SDSENDSENSORDISTANCEPARDISTANCE = (- 4)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 5)
------ time 40 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 46
  SDSENDSENSORDISTANCEPARDISTANCE = (- 4)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 5)
------ time 41 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = (- 4)
  SDSENDSENSORDISTANCEPARDISTANCE = (- 4)
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 42 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 47
  SDSENDSENSORDISTANCEPARDISTANCE = (- 4)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
------ time 43 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 48
  SDSENDSENSORDISTANCEPARDISTANCE = (- 4)
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 4)
------ time 44 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 49
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 45 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 50
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 46 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 51
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 47 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 52
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 48 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 53
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 49 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 54
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 50 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 55
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 51 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 2
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 52 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 56
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 53 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_EXIT
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 57
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
------ time 54 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 58
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 55 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 59
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 56 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 60
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 57 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 61
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 58 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 62
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 59 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 63
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 60 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 64
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 61 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 3
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 62 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 65
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 63 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 66
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 3
------ time 64 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 67
  SDSENDSENSORDISTANCEPARDISTANCE = 6
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 65 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 68
  SDSENDSENSORDISTANCEPARDISTANCE = 6
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 66 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 69
  SDSENDSENSORDISTANCEPARDISTANCE = 6
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 67 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 70
  SDSENDSENSORDISTANCEPARDISTANCE = 6
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 68 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 71
  SDSENDSENSORDISTANCEPARDISTANCE = 6
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 69 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 72
  SDSENDSENSORDISTANCEPARDISTANCE = 6
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 70 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 73
  SDSENDSENSORDISTANCEPARDISTANCE = 6
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 71 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 6
  SDSENDSENSORDISTANCEPARDISTANCE = 6
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 72 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 74
  SDSENDSENSORDISTANCEPARDISTANCE = 6
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 73 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 75
  SDSENDSENSORDISTANCEPARDISTANCE = 6
  OBJCTRLPARAMRECEIVEDDISTANCE = 6
------ time 74 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 76
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 75 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 77
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 76 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 78
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 77 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 79
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 78 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 80
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 79 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 81
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 4)
------ time 80 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 82
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 81 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 5
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 82 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 83
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 83 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 84
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 5
------ time 84 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 85
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 85 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 86
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 86 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 87
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 87 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 88
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 88 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 89
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 89 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 90
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 90 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 91
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 91 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 4
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 92 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 92
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 93 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 93
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 4
------ time 94 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 94
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 95 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 95
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 96 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 96
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 97 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 97
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 98 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 98
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
------ time 99 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 99
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 100 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 100
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 101 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 3
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 4
------ time 102 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 101
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 103 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 102
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 3
------ time 104 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 103
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 105 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 104
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 106 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 105
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 107 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 106
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 108 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 107
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 109 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 108
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 110 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 109
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 111 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 2
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 112 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 110
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 113 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 111
  SDSENDSENSORDISTANCEPARDISTANCE = 2
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
------ time 114 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 112
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 115 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 113
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 116 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 114
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 117 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 115
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 118 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 116
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 119 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 117
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 120 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 118
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 121 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 3
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 122 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 119
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 123 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 120
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 3
------ time 124 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 121
  SDSENDSENSORDISTANCEPARDISTANCE = 7
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 125 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 122
  SDSENDSENSORDISTANCEPARDISTANCE = 7
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 126 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 123
  SDSENDSENSORDISTANCEPARDISTANCE = 7
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 127 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 124
  SDSENDSENSORDISTANCEPARDISTANCE = 7
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 128 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 125
  SDSENDSENSORDISTANCEPARDISTANCE = 7
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 129 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = (- 4)
  SDSENDSENSORDISTANCEPARDISTANCE = 7
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
------ time 130 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 8
  SDSENDSENSORDISTANCEPARDISTANCE = 7
  OBJCTRLPARAMRECEIVEDDISTANCE = 7
------ time 131 ------
**LOOP**
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 7
  SDSENDSENSORDISTANCEPARDISTANCE = 7
  OBJCTRLPARAMRECEIVEDDISTANCE = 7
------ time 132 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 126
  SDSENDSENSORDISTANCEPARDISTANCE = 7
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 133 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 127
  SDSENDSENSORDISTANCEPARDISTANCE = 7
  OBJCTRLPARAMRECEIVEDDISTANCE = 7
------ time 134 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 128
  SDSENDSENSORDISTANCEPARDISTANCE = 8
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 135 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 129
  SDSENDSENSORDISTANCEPARDISTANCE = 8
  OBJCTRLPARAMRECEIVEDDISTANCE = 9
------ time 136 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 130
  SDSENDSENSORDISTANCEPARDISTANCE = 8
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 137 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 131
  SDSENDSENSORDISTANCEPARDISTANCE = 8
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 138 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 132
  SDSENDSENSORDISTANCEPARDISTANCE = 8
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 139 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 133
  SDSENDSENSORDISTANCEPARDISTANCE = 8
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
------ time 140 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 134
  SDSENDSENSORDISTANCEPARDISTANCE = 8
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 141 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 8
  SDSENDSENSORDISTANCEPARDISTANCE = 8
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 142 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 135
  SDSENDSENSORDISTANCEPARDISTANCE = 8
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 143 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 136
  SDSENDSENSORDISTANCEPARDISTANCE = 8
  OBJCTRLPARAMRECEIVEDDISTANCE = 8
------ time 144 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 137
  SDSENDSENSORDISTANCEPARDISTANCE = 0
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
------ time 145 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 138
  SDSENDSENSORDISTANCEPARDISTANCE = 0
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
------ time 146 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 139
  SDSENDSENSORDISTANCEPARDISTANCE = 0
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
------ time 147 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 140
  SDSENDSENSORDISTANCEPARDISTANCE = 0
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
------ time 148 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 141
  SDSENDSENSORDISTANCEPARDISTANCE = 0
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
------ time 149 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 142
  SDSENDSENSORDISTANCEPARDISTANCE = 0
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
------ time 150 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 143
  SDSENDSENSORDISTANCEPARDISTANCE = 0
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
------ time 151 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 0
  SDSENDSENSORDISTANCEPARDISTANCE = 0
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
------ time 152 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 144
  SDSENDSENSORDISTANCEPARDISTANCE = 0
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
------ time 153 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 145
  SDSENDSENSORDISTANCEPARDISTANCE = 0
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 154 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 146
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 155 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 147
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 156 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 148
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 157 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 149
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 158 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 150
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 159 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 151
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 160 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 152
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 161 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 5
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 162 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 153
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 163 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_EXIT
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 154
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 5
------ time 164 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 155
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 165 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 156
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 166 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 157
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 167 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 158
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 168 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 159
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 169 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 160
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 170 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 161
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 171 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 5
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 172 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 162
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 173 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 163
  SDSENDSENSORDISTANCEPARDISTANCE = 5
  OBJCTRLPARAMRECEIVEDDISTANCE = 5
------ time 174 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 164
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
------ time 175 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 165
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 176 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 166
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 177 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 167
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 178 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 168
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 179 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 169
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 180 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 170
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 181 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 4
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 182 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 171
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
------ time 183 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 172
  SDSENDSENSORDISTANCEPARDISTANCE = 4
  OBJCTRLPARAMRECEIVEDDISTANCE = 4
------ time 184 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 173
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 185 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 174
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 186 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 175
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 187 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 176
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 188 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 177
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 189 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 178
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 190 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 179
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 191 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJBUSPARAMRECEIVEDDISTANCE = 3
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 192 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 180
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 193 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 181
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 3
------ time 194 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSPARAMRECEIVEDDISTANCE = 182
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 3
------ time 195 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 3
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 3
------ time 196 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 183
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 197 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 184
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 198 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 185
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
------ time 199 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 0
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
------ time 200 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSPARAMRECEIVEDDISTANCE = 4
  SDSENDSENSORDISTANCEPARDISTANCE = 3
  OBJCTRLPARAMRECEIVEDDISTANCE = 3
------ end ------
Evaluation took:
  11.961 seconds of real time
  0.800000 seconds of total run time (0.720000 user, 0.080000 system)
  [ Run times consist of 0.080 seconds GC time, and 0.720 seconds non-GC time. ]
  6.69% CPU
  40,669,228,120 processor cycles
  2,448,020,192 bytes consed
  
