This is SBCL 1.2.4.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
IPC-terms: ((YESTERDAY SDSENDSENSORDISTANCEPARDISTANCE)
            OBJBUSPARAMRECEIVEDDISTANCE SDSENDSENSORDISTANCEPARDISTANCE
            OBJCTRLPARAMRECEIVEDDISTANCE 2)
IPC-constraints: ((< SDSENDSENSORDISTANCEPARDISTANCE 2)
                  (= SDSENDSENSORDISTANCEPARDISTANCE
                     (YESTERDAY SDSENDSENSORDISTANCEPARDISTANCE))
                  (= SDSENDSENSORDISTANCEPARDISTANCE
                     OBJBUSPARAMRECEIVEDDISTANCE)
                  (= SDSENDSENSORDISTANCEPARDISTANCE
                     OBJCTRLPARAMRECEIVEDDISTANCE)
                  (< OBJCTRLPARAMRECEIVEDDISTANCE 2)
                  (>= OBJCTRLPARAMRECEIVEDDISTANCE 2))
This is AE2SBVZOT.

1. processing formula
Used boolean propositions: 
((< SDSENDSENSORDISTANCEPARDISTANCE 2) IOD_PNSFKAN_EEKTXBQZTILH3G_END
 IOD_PNSFKAN_EEKTXBQZTILH3G_START
 (= SDSENDSENSORDISTANCEPARDISTANCE
    (YESTERDAY SDSENDSENSORDISTANCEPARDISTANCE))
 SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
 (= SDSENDSENSORDISTANCEPARDISTANCE OBJBUSPARAMRECEIVEDDISTANCE)
 MESSAGE_IJQC4AOAEEKTXBQZTILH3G
 (= SDSENDSENSORDISTANCEPARDISTANCE OBJCTRLPARAMRECEIVEDDISTANCE)
 MESSAGE_LZQ5WAOBEEKTXBQZTILH3G MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
 MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
 IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
 IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START SENDSENSORDISTANCE_END
 SENDSENSORDISTANCE_STOP SENDSENSORDISTANCE_START SDSENDSENSORDISTANCE
 SDSENDBRAKECOMMAND_TIMECONSTRAINT_1 MESSAGE_FOVPUAOCEEKTXBQZTILH3G
 MESSAGE_I36JSAOCEEKTXBQZTILH3G MESSAGE_I36JSAOCEEKTXBQZTILH3G_START
 MESSAGE_FOVPUAOCEEKTXBQZTILH3G_START
 IOD__PNSFKAN_EEKTXBQZTILH3G_SENDBRAKECOMMAND_END
 IOD__PNSFKAN_EEKTXBQZTILH3G_SENDBRAKECOMMAND_START SENDBRAKECOMMAND_END
 SENDBRAKECOMMAND_STOP SENDBRAKECOMMAND_START SDSENDBRAKECOMMAND
 MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END OBJBUSOPSENDSENSORDISTANCE
 MESSAGE_FOVPUAOCEEKTXBQZTILH3G_END OBJBUSOPSENDBRAKECOMMAND
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER T
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G_TIMECONDITION
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G_TRIGGER
 (< OBJCTRLPARAMRECEIVEDDISTANCE 2)
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
 (>= OBJCTRLPARAMRECEIVEDDISTANCE 2)
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
 OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
 OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
 $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G
 OBJCTRL_STDSTATEMACHINE1_STATEBRAKING_EXIT
 OBJCTRL_STDSTATEMACHINE1_STATEBRAKING_ENTER
 $OBJCTRL_STDSTATEMACHINE1_STATEBRAKING
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G
 OBJCTRL_STDSTATEMACHINE1_STATEWARNING_EXIT
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
 OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
 $OBJCTRL_STDSTATEMACHINE1_STATEWARNING MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
 OBJCTRLOPNOTIFYDISTANCE
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION__APEGAOCEEKTXBQZTILH3G_TRIGGER
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G_TIMECONDITION
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G_TRIGGER
 OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_EXIT
 OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_ENTER
 $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G
 OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING_EXIT
 OBJBRAKES_STDSTATEMACHINE1_TRANSITION__APEGAOCEEKTXBQZTILH3G
 OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING_ENTER
 $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING MESSAGE_I36JSAOCEEKTXBQZTILH3G_END
 OBJBRAKESOPNOTIFYBRAKE
 OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G BRAKEINTERRUPT
 RADARCLOCKTICK MADESYSTEMSTART)

Used arithmetic terms: 
NIL

Used timed arithmetic terms: 
(OBJBUSPARAMRECEIVEDDISTANCE SDSENDSENSORDISTANCEPARDISTANCE
 OBJCTRLPARAMRECEIVEDDISTANCE)

Graph dependency over terms 
((2 2 OBJCTRLPARAMRECEIVEDDISTANCE OBJBUSPARAMRECEIVEDDISTANCE 2
  SDSENDSENSORDISTANCEPARDISTANCE (YESTERDAY SDSENDSENSORDISTANCEPARDISTANCE)))

Related variables 
((OBJCTRLPARAMRECEIVEDDISTANCE OBJBUSPARAMRECEIVEDDISTANCE 2
  SDSENDSENSORDISTANCEPARDISTANCE))

Time bound: 200

Number of Boolean variables: 
71
define FO future formulae Xt
define FO future formulae Yt
define for interpreted relations: <,>,=,<=,>= 
define FO terms for +,-,*,/,mod 
define loop constraints

done processing formula
define LTL future formulae X, U, R
define LTL future formulae X, U, R
gen-past2...
gen-past2...
define LTL boolean connectives
define LTL boolean connectives

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  4.960 seconds of real time
  0.000000 seconds of total run time (0.000000 user, 0.000000 system)
  0.00% CPU
  16,865,655,573 processor cycles
  0 bytes consed
  
---SAT---
------ time 0 ------
  IOD_PNSFKAN_EEKTXBQZTILH3G_START
  MADESYSTEMSTART
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 201
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 1 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_ENTER
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 3
  SDSENDSENSORDISTANCEPARDISTANCE = 3
------ time 2 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 202
  SDSENDSENSORDISTANCEPARDISTANCE = 3
------ time 3 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 3
  OBJBUSPARAMRECEIVEDDISTANCE = 203
  SDSENDSENSORDISTANCEPARDISTANCE = 3
------ time 4 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 5
  OBJBUSPARAMRECEIVEDDISTANCE = 204
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 5 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 5
  OBJBUSPARAMRECEIVEDDISTANCE = 205
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 6 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 206
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 7 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 5
  OBJBUSPARAMRECEIVEDDISTANCE = 207
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 8 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 5
  OBJBUSPARAMRECEIVEDDISTANCE = 208
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 9 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 209
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 10 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 210
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 11 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 5
  OBJBUSPARAMRECEIVEDDISTANCE = 4
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 12 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 5
  OBJBUSPARAMRECEIVEDDISTANCE = 211
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 13 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 4
  OBJBUSPARAMRECEIVEDDISTANCE = 212
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 14 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 213
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 15 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 214
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 16 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 215
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 17 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 216
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 18 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 217
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 19 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 218
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 20 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 219
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 21 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = (- 3)
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 22 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 220
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 23 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
  OBJBUSPARAMRECEIVEDDISTANCE = 221
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 24 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 222
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 25 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 223
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 26 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
  OBJBUSPARAMRECEIVEDDISTANCE = 224
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 27 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 225
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 28 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 226
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 29 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 227
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 30 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 228
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 31 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
  OBJBUSPARAMRECEIVEDDISTANCE = (- 2)
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 32 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 229
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 33 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 2)
  OBJBUSPARAMRECEIVEDDISTANCE = 230
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 34 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 231
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 35 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 232
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 36 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 233
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 37 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 234
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 38 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 235
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 39 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 236
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 40 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 237
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 41 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 0
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 42 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 238
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 43 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 239
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 44 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 240
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 45 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 241
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 46 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 242
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 47 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 243
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 48 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 244
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 49 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 245
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 50 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 246
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 51 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 0
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 52 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 247
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 53 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 248
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 54 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 2)
  OBJBUSPARAMRECEIVEDDISTANCE = 249
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 55 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 250
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 56 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 2)
  OBJBUSPARAMRECEIVEDDISTANCE = 251
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 57 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 252
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 58 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 253
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 59 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 2)
  OBJBUSPARAMRECEIVEDDISTANCE = 254
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 60 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 255
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 61 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 2)
  OBJBUSPARAMRECEIVEDDISTANCE = (- 1)
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 62 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 2)
  OBJBUSPARAMRECEIVEDDISTANCE = 256
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 63 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 257
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 64 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 258
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 65 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 259
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 66 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 260
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 67 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 261
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 68 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 262
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 69 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 263
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 70 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 264
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 71 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = (- 2)
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 72 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 265
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 73 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 2)
  OBJBUSPARAMRECEIVEDDISTANCE = 266
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 74 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 267
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 75 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 4)
  OBJBUSPARAMRECEIVEDDISTANCE = 268
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 76 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 269
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 77 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 270
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 78 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 271
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 79 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 2)
  OBJBUSPARAMRECEIVEDDISTANCE = 272
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 80 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 273
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 81 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 4)
  OBJBUSPARAMRECEIVEDDISTANCE = (- 3)
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 82 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 4)
  OBJBUSPARAMRECEIVEDDISTANCE = 274
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 83 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_EXIT
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  BRAKEINTERRUPT
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
  OBJBUSPARAMRECEIVEDDISTANCE = 275
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 84 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDBRAKECOMMAND_START
  SDSENDBRAKECOMMAND
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_STATEBRAKING_ENTER
  SDSENDBRAKECOMMAND_TIMECONSTRAINT_1
  SENDBRAKECOMMAND_START
  $OBJCTRL_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 276
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 85 ------
  MESSAGE_FOVPUAOCEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G
  SDSENDBRAKECOMMAND
  SDSENDSENSORDISTANCE
  MESSAGE_FOVPUAOCEEKTXBQZTILH3G
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJBUSOPSENDBRAKECOMMAND
  SDSENDBRAKECOMMAND_TIMECONSTRAINT_1
  MESSAGE_FOVPUAOCEEKTXBQZTILH3G_START
  $OBJCTRL_STDSTATEMACHINE1_STATEBRAKING
  OBJCTRL_STDSTATEMACHINE1_STATEBRAKING_EXIT
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_VYX8UAODEEKTXBQZTILH3G_TIMECONDITION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 277
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 86 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDBRAKECOMMAND_END
  MESSAGE_I36JSAOCEEKTXBQZTILH3G
  OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_EXIT
  SDSENDBRAKECOMMAND
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
  MESSAGE_I36JSAOCEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  SENDBRAKECOMMAND_END
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION__APEGAOCEEKTXBQZTILH3G
  SDSENDBRAKECOMMAND_TIMECONSTRAINT_1
  MESSAGE_I36JSAOCEEKTXBQZTILH3G_START
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION__APEGAOCEEKTXBQZTILH3G_TRIGGER
  OBJBRAKESOPNOTIFYBRAKE
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 278
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 87 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING_ENTER
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 279
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 88 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 5
  OBJBUSPARAMRECEIVEDDISTANCE = 280
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 89 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 5
  OBJBUSPARAMRECEIVEDDISTANCE = 281
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 90 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 282
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 91 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 4
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 92 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 5
  OBJBUSPARAMRECEIVEDDISTANCE = 283
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 93 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 4
  OBJBUSPARAMRECEIVEDDISTANCE = 284
  SDSENDSENSORDISTANCEPARDISTANCE = 4
------ time 94 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 285
  SDSENDSENSORDISTANCEPARDISTANCE = 3
------ time 95 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 4
  OBJBUSPARAMRECEIVEDDISTANCE = 286
  SDSENDSENSORDISTANCEPARDISTANCE = 3
------ time 96 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 4
  OBJBUSPARAMRECEIVEDDISTANCE = 287
  SDSENDSENSORDISTANCEPARDISTANCE = 3
------ time 97 ------
  $OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G
  SDSENDSENSORDISTANCE
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJBRAKES_STDSTATEMACHINE1_STATEBRAKING_EXIT
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJBRAKES_STDSTATEMACHINE1_TRANSITION_FDSOSAODEEKTXBQZTILH3G_TIMECONDITION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 288
  SDSENDSENSORDISTANCEPARDISTANCE = 3
------ time 98 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJBRAKES_STDSTATEMACHINE1_STATEIDLE_ENTER
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 289
  SDSENDSENSORDISTANCEPARDISTANCE = 3
------ time 99 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 290
  SDSENDSENSORDISTANCEPARDISTANCE = 3
------ time 100 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 291
  SDSENDSENSORDISTANCEPARDISTANCE = 3
------ time 101 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 3
  SDSENDSENSORDISTANCEPARDISTANCE = 3
------ time 102 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 292
  SDSENDSENSORDISTANCEPARDISTANCE = 3
------ time 103 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 3
  OBJBUSPARAMRECEIVEDDISTANCE = 293
  SDSENDSENSORDISTANCEPARDISTANCE = 3
------ time 104 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 3
  OBJBUSPARAMRECEIVEDDISTANCE = 294
  SDSENDSENSORDISTANCEPARDISTANCE = 2
------ time 105 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 295
  SDSENDSENSORDISTANCEPARDISTANCE = 2
------ time 106 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 3
  OBJBUSPARAMRECEIVEDDISTANCE = 296
  SDSENDSENSORDISTANCEPARDISTANCE = 2
------ time 107 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 297
  SDSENDSENSORDISTANCEPARDISTANCE = 2
------ time 108 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 3
  OBJBUSPARAMRECEIVEDDISTANCE = 298
  SDSENDSENSORDISTANCEPARDISTANCE = 2
------ time 109 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 3
  OBJBUSPARAMRECEIVEDDISTANCE = 299
  SDSENDSENSORDISTANCEPARDISTANCE = 2
------ time 110 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 300
  SDSENDSENSORDISTANCEPARDISTANCE = 2
------ time 111 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 2
  SDSENDSENSORDISTANCEPARDISTANCE = 2
------ time 112 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 301
  SDSENDSENSORDISTANCEPARDISTANCE = 2
------ time 113 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 302
  SDSENDSENSORDISTANCEPARDISTANCE = 2
------ time 114 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 303
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 115 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 304
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 116 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 305
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 117 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 306
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 118 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 307
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 119 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 308
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 120 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 309
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 121 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 0
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 122 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 310
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 123 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_EXIT
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 311
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 124 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_ENTER
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 312
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 125 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 313
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 126 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 314
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 127 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 315
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 128 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 316
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 129 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 317
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 130 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 318
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 131 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = (- 1)
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 132 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 319
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 133 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 320
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 134 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 321
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 135 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 322
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 136 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 323
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 137 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 324
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 138 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 325
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 139 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 326
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 140 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 327
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 141 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = (- 2)
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 142 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 328
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 143 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 2)
  OBJBUSPARAMRECEIVEDDISTANCE = 329
  SDSENDSENSORDISTANCEPARDISTANCE = (- 2)
------ time 144 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 330
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 145 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 4)
  OBJBUSPARAMRECEIVEDDISTANCE = 331
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 146 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 332
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 147 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 333
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 148 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 334
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 149 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 335
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 150 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 336
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 151 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = (- 3)
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 152 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 337
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 153 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 3)
  OBJBUSPARAMRECEIVEDDISTANCE = 338
  SDSENDSENSORDISTANCEPARDISTANCE = (- 3)
------ time 154 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 339
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 155 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 340
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 156 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 341
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 157 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 342
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 158 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 343
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 159 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 8
  OBJBUSPARAMRECEIVEDDISTANCE = 344
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 160 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 345
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 161 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = (- 1)
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 162 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 346
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 163 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = (- 1)
  OBJBUSPARAMRECEIVEDDISTANCE = 347
  SDSENDSENSORDISTANCEPARDISTANCE = (- 1)
------ time 164 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 348
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 165 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 349
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 166 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 350
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 167 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 351
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 168 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 352
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 169 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 8
  OBJBUSPARAMRECEIVEDDISTANCE = 353
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 170 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 354
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 171 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 0
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 172 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 1
  OBJBUSPARAMRECEIVEDDISTANCE = 355
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 173 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 356
  SDSENDSENSORDISTANCEPARDISTANCE = 0
------ time 174 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 357
  SDSENDSENSORDISTANCEPARDISTANCE = 6
------ time 175 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 358
  SDSENDSENSORDISTANCEPARDISTANCE = 6
------ time 176 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 359
  SDSENDSENSORDISTANCEPARDISTANCE = 6
------ time 177 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 7
  OBJBUSPARAMRECEIVEDDISTANCE = 360
  SDSENDSENSORDISTANCEPARDISTANCE = 6
------ time 178 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 361
  SDSENDSENSORDISTANCEPARDISTANCE = 6
------ time 179 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 7
  OBJBUSPARAMRECEIVEDDISTANCE = 362
  SDSENDSENSORDISTANCEPARDISTANCE = 6
------ time 180 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 363
  SDSENDSENSORDISTANCEPARDISTANCE = 6
------ time 181 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 6
  SDSENDSENSORDISTANCEPARDISTANCE = 6
------ time 182 ------
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 364
  SDSENDSENSORDISTANCEPARDISTANCE = 6
------ time 183 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G_GUARD
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  OBJCTRL_STDSTATEMACHINE1_STATEWARNING_EXIT
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_QGXUMAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_OUUU0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  $OBJCTRL_STDSTATEMACHINE1_STATEWARNING
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 6
  OBJBUSPARAMRECEIVEDDISTANCE = 365
  SDSENDSENSORDISTANCEPARDISTANCE = 6
------ time 184 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_STATENOACTION_ENTER
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 366
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 185 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 6
  OBJBUSPARAMRECEIVEDDISTANCE = 367
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 186 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 6
  OBJBUSPARAMRECEIVEDDISTANCE = 368
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 187 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 369
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 188 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 370
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 189 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 7
  OBJBUSPARAMRECEIVEDDISTANCE = 4
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 190 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 6
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 191 ------
  SDSENDSENSORDISTANCE
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_START
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G
  RADARCLOCKTICK
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  MESSAGE_IJQC4AOAEEKTXBQZTILH3G_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJBUSOPSENDSENSORDISTANCE
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 5
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 192 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 371
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 193 ------
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_START
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  OBJCTRLOPNOTIFYDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_TRIGGER
  MESSAGE_LZQ5WAOBEEKTXBQZTILH3G_END
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_TRIGGER
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G
  SENDSENSORDISTANCE_END
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 5
  OBJBUSPARAMRECEIVEDDISTANCE = 372
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 194 ------
  IOD__PNSFKAN_EEKTXBQZTILH3G_SENDSENSORDISTANCE_START
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  SENDSENSORDISTANCE_START
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 373
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 195 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 374
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 196 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 375
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 197 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 376
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 198 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 2
  OBJBUSPARAMRECEIVEDDISTANCE = 377
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 199 ------
  SDSENDSENSORDISTANCE
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_WCVW0AODEEKTXBQZTILH3G_GUARD
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 7
  OBJBUSPARAMRECEIVEDDISTANCE = 4
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ time 200 ------
  SDSENDSENSORDISTANCE
  $OBJBRAKES_STDSTATEMACHINE1_STATEIDLE
  $OBJCTRL_STDSTATEMACHINE1_STATENOACTION
  OBJCTRL_STDSTATEMACHINE1_TRANSITION_BR9NSAODEEKTXBQZTILH3G_GUARD
  SDSENDSENSORDISTANCE_TIMECONSTRAINT_1
  OBJCTRLPARAMRECEIVEDDISTANCE = 0
  OBJBUSPARAMRECEIVEDDISTANCE = 6
  SDSENDSENSORDISTANCEPARDISTANCE = 5
------ end ------
Evaluation took:
  6.072 seconds of real time
  1.108000 seconds of total run time (1.024000 user, 0.084000 system)
  [ Run times consist of 0.096 seconds GC time, and 1.012 seconds non-GC time. ]
  18.25% CPU
  20,642,847,779 processor cycles
  3,417,564,864 bytes consed
  
