This is SBCL 1.2.4.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  0.377 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  2.12% CPU
  1,282,563,238 processor cycles
  32,704 bytes consed
  
---UNSAT---

Checked Bound: 1
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  0.513 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  1.56% CPU
  1,741,899,055 processor cycles
  32,752 bytes consed
  
---UNSAT---

Checked Bound: 2
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  0.685 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  1.17% CPU
  2,328,194,140 processor cycles
  32,176 bytes consed
  
---UNSAT---

Checked Bound: 3
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  0.897 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  0.89% CPU
  3,047,432,101 processor cycles
  32,752 bytes consed
  
---UNSAT---

Checked Bound: 4
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  2.276 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  0.35% CPU
  7,736,595,870 processor cycles
  32,752 bytes consed
  
---UNSAT---

Checked Bound: 5
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  3.403 seconds of real time
  0.008000 seconds of total run time (0.004000 user, 0.004000 system)
  0.24% CPU
  11,571,183,472 processor cycles
  32,688 bytes consed
  
---UNSAT---

Checked Bound: 6
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  3.612 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  0.22% CPU
  12,280,535,546 processor cycles
  32,672 bytes consed
  
---UNSAT---

Checked Bound: 7
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  4.270 seconds of real time
  0.020000 seconds of total run time (0.016000 user, 0.004000 system)
  [ Run times consist of 0.012 seconds GC time, and 0.008 seconds non-GC time. ]
  0.47% CPU
  14,516,885,727 processor cycles
  32,752 bytes consed
  
---UNSAT---

Checked Bound: 8
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  4.340 seconds of real time
  0.020000 seconds of total run time (0.012000 user, 0.008000 system)
  [ Run times consist of 0.016 seconds GC time, and 0.004 seconds non-GC time. ]
  0.46% CPU
  14,754,069,940 processor cycles
  32,752 bytes consed
  
---UNSAT---

Checked Bound: 9
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  4.852 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  0.16% CPU
  16,498,620,604 processor cycles
  32,704 bytes consed
  
---SAT---
------ time 0 ------
  BIGBANG
------ time 1 ------
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  SDSEARCH_PAR_SERVER2_START
  SDSEARCH_ALT_OP1_SERVER1_START
  SDSEARCH_PAR_SERVER1
  SDSEARCH_ALT_OP1_START
  SDSEARCH_PAR_APP_END
  SDSEARCH_PAR_OP2_SERVER2_START
  SDSEARCH_SCREEN
  SDSEARCH_PAR_OP1_APP_START
  MSGPINGS2_START
  SDSEARCH_PAR_OP2_SERVER1_END
  SDSEARCH_SERVER2_START
  SDSEARCH_SERVER2
  SDSEARCH_PAR_OP2
  SDSEARCH
  SDSEARCH_PAR_OP1_START
  SDSEARCH_PAR_OP1_SERVER1
  SDSEARCH_PAR_OP2_APP_START
  SDSEARCH_PAR_APP_START
  SDSEARCH_SERVER1_START
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_PAR_OP2_APP_END
  SDSEARCH_PAR_OP2_START
  SDSEARCH_ALT_START
  SDSEARCH_SCREEN_START
  MSGPINGS1
  SDSEARCH_ALT
  MSGPINGS2
  SDSEARCH_PAR_SERVER2
  SDSEARCH_ALT_SCREEN
  SDSEARCH_PAR_SERVER1_START
  SDSEARCH_PAR_OP1
  SDSEARCH_SERVER1
  SDSEARCH_PAR_OP2_APP
  SDSEARCH_ALT_SCREEN_START
  SDSEARCH_PAR_OP1_SERVER1_END
  SDSEARCH_PAR_OP2_SERVER1
  SDSEARCH_PAR_APP
  SDSEARCH_PAR_OP2_SERVER1_START
  SDSEARCH_ALT_SERVER1_START
  SDSEARCH_APP_START
  SDSEARCH_PAR_SERVER1_END
  SDSEARCH_ALT_OP1
  SDSEARCH_PAR_OP1_APP
  SDSEARCH_PAR_START
  SDSEARCH_PAR_OP1_SERVER1_START
  MSGPINGS1_START
  SDSEARCH_PAR_OP2_SERVER2
  SDSEARCH_START
  SDSEARCH_PAR_OP1_APP_END
  SDSEARCH_PAR
  MSGPINGS1_END
------ time 2 ------
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  MSGREPLYS1_1ST
  SDSEARCH_SCREEN
  SDSEARCH_SERVER2
  SDSEARCH_PAR_OP2
  SDSEARCH
  SDSEARCH_ALT_OP1_SERVER1
  MSGPINGS2_END
  SDSEARCH_PAR_OP2_SERVER2_END
  MSGREPLYS1_1ST_START
  SDSEARCH_ALT
  MSGPINGS2
  SDSEARCH_PAR_SERVER2
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_APP_START
  SDSEARCH_ALT_APP
  SDSEARCH_PAR_OP1
  SDSEARCH_SERVER1
  SDSEARCH_PAR_OP2_END
  SDSEARCH_ALT_OP1_APP
  SDSEARCH_ALT_OP1_APP_START
  SDSEARCH_ALT_OP1
  SDSEARCH_PAR_OP2_SERVER2
  MSGREPLYS1_1ST_END
  SDSEARCH_PAR
------ time 3 ------
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_ALT_OP1_PAR1_OP2_APP_START
  SDSEARCH_ALT_OP1_PAR1_APP_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_START
  LOOP1OP1MSGSEARCHNEXTS1_START
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP_START
  SDSEARCH_ALT_OP1_PAR1_OP2_START
  SDSEARCH_ALT_OP1_PAR1_OP1_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_APP_START
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1_APP
  SDSEARCH
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1_START
  SDSEARCH_PAR_OP1_END
  SDSEARCH_PAR_OP1_SERVER2_END
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_SERVER1_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER1_START
  SDSEARCH_PAR_END
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_PAR_SERVER2_END
  SDSEARCH_ALT
  SDSEARCH_PAR_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_APP
  LOOP1OP1MSGSEARCHNEXTS1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_START
  SDSEARCH_PAR_OP1
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_APP
  SDSEARCH_PAR_OP1_SERVER2_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1
  SDSEARCH_ALT_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1_START
  SDSEARCH_ALT_OP1_PAR1_OP1_APP_START
  SDSEARCH_PAR_OP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_START
  LOOP1OP1MSGSEARCHNEXTS1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER1
  SDSEARCH_PAR
------ time 4 ------
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER2
  MSGREPLYS2_1ST_START
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER2_START
  SDSEARCH_SERVER2
  LOOP1OP1MSGRESULTS1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1
  MSGREPLYS2_1ST
  SDSEARCH_ALT_OP1_PAR1_OP1_APP
  SDSEARCH
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER1_END
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER2_START
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  LOOP1OP1MSGRESULTS1
  SDSEARCH_ALT_SERVER2
  SDSEARCH_ALT_OP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_ALT
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_OP1_SERVER2_START
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER2
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_PAR1_SERVER2_START
  SDSEARCH_ALT_OP1_APP
  LOOP1OP1MSGRESULTS1_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1
  SDSEARCH_ALT_OP1
  SDSEARCH_ALT_SERVER2_START
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER2_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_SERVER2
------ time 5 ------
  SDSEARCH_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER1_START
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_APP_END
  LOOP1OP1MSGUPDATERESULTS1_START
  LOOP1OP1MSGUPDATERESULTS1
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER1
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_START
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1
  MSGREPLYS2_1ST
  SDSEARCH_ALT_OP1_PAR1_OP1_APP
  SDSEARCH
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2
  SDSEARCH_ALT_SERVER2
  SDSEARCH_ALT_OP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_ALT
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER2
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1
  SDSEARCH_ALT_OP1
  SDSEARCH_ALT_OP1_PAR1_SERVER2
------ time 6 ------
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  LOOP1OP1MSGUPDATERESULTS1
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_APP
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER1
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1
  MSGREPLYS2_1ST
  SDSEARCH_ALT_OP1_PAR1_OP1_APP
  SDSEARCH
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2
  SDSEARCH_ALT_SERVER2
  SDSEARCH_ALT_OP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  LOOP1OP2MSGSEARCHNEXTS1_START
  SDSEARCH_ALT
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_APP_START
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER2
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1
  SDSEARCH_ALT_OP1
  LOOP1OP2MSGSEARCHNEXTS1_END
  LOOP1OP2MSGSEARCHNEXTS1
  SDSEARCH_ALT_OP1_PAR1_SERVER2
------ time 7 ------
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER2_END
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SCREEN_START
  LOOP1OP1MSGUPDATERESULTS1
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN_START
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1_END
  SDSEARCH_ALT_OP1_SCREEN_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER1
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1
  MSGREPLYS2_1ST
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1_END
  SDSEARCH
  LOOP1OP1MSGUPDATERESULTS1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN_START
  SDSEARCH_ALT_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2
  SDSEARCH_ALT_OP1_PAR1_SCREEN
  SDSEARCH_ALT_SERVER2
  LOOP1OP2MSGRESULTS1_END
  SDSEARCH_ALT_OP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN
  SDSEARCH_ALT
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER2_START
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER2
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_APP
  LOOP1OP2MSGRESULTS1_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER2_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SCREEN_END
  LOOP1OP2MSGRESULTS1
  SDSEARCH_ALT_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SCREEN_START
  SDSEARCH_ALT_OP1_PAR1_SERVER2
------ time 8 ------
  SDSEARCH_APP
  SDSEARCH_ALT_OP1_PAR1_SERVER2_END
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_SERVER1_END
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER1_START
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN_END
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_SERVER1_END
  SDSEARCH_ALT_SCREEN_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_END
  SDSEARCH_ALT_OP1_PAR1_END
  SDSEARCH_ALT_OP1_SERVER2_END
  SDSEARCH_ALT_SERVER2_END
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER2_END
  MSGREPLYS2_1ST_END
  SDSEARCH_ALT_OP1_PAR1_OP1_APP_END
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP1_SCREEN_END
  SDSEARCH_ALT_OP1_PAR1_OP2_APP_END
  MSGREPLYS2_1ST
  SDSEARCH_ALT_OP1_SERVER1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP1_APP
  SDSEARCH_ALT_APP_END
  SDSEARCH
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP1_SCREEN
  SDSEARCH_ALT_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2
  SDSEARCH_END
  SDSEARCH_ALT_OP1_PAR1_SCREEN
  SDSEARCH_ALT_SERVER2
  LOOP1OP2MSGUPDATERESULTS1
  SDSEARCH_ALT_OP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_END
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER2_END
  LOOP1OP2MSGUPDATERESULTS1_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER2_START
  SDSEARCH_ALT
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER2_END
  SDSEARCH_ALT_APP
  SDSEARCH_ALT_OP1_PAR1_OP1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SCREEN_END
  SDSEARCH_ALT_OP1_PAR1_OP1_SCREEN_START
  SDSEARCH_ALT_OP1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER2
  SDSEARCH_ALT_OP1_PAR1_APP_END
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_END
  SDSEARCH_ALT_OP1_PAR1_SERVER1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SCREEN_START
  SDSEARCH_SERVER2_END
  SDSEARCH_ALT_OP1_APP_END
  SDSEARCH_ALT_OP1_SCREEN_END
  SDSEARCH_ALT_OP1
  LOOP1OP2MSGUPDATERESULTS1_END
  SDSEARCH_APP_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_APP_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SCREEN_END
  SDSEARCH_ALT_END
  SDSEARCH_SCREEN_END
  SDSEARCH_ALT_OP1_PAR1_SERVER2
------ time 9 ------
------ time 10 ------
**LOOP**
------ end of bvzot result ------

Found: 10
