This is SBCL 1.2.4.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  0.422 seconds of real time
  0.008000 seconds of total run time (0.004000 user, 0.004000 system)
  1.90% CPU
  1,433,843,289 processor cycles
  0 bytes consed
  
---UNSAT---

Checked Bound: 1
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  0.597 seconds of real time
  0.008000 seconds of total run time (0.004000 user, 0.004000 system)
  1.34% CPU
  2,029,027,928 processor cycles
  0 bytes consed
  
---UNSAT---

Checked Bound: 2
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  0.786 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  1.02% CPU
  2,671,822,435 processor cycles
  0 bytes consed
  
---UNSAT---

Checked Bound: 3
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  2.314 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  0.35% CPU
  7,867,718,825 processor cycles
  0 bytes consed
  
---UNSAT---

Checked Bound: 4
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  2.548 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  0.31% CPU
  8,662,301,882 processor cycles
  0 bytes consed
  
---UNSAT---

Checked Bound: 5
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  3.280 seconds of real time
  0.028000 seconds of total run time (0.016000 user, 0.012000 system)
  [ Run times consist of 0.016 seconds GC time, and 0.012 seconds non-GC time. ]
  0.85% CPU
  11,150,697,638 processor cycles
  0 bytes consed
  
---UNSAT---

Checked Bound: 6
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  2.864 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  0.28% CPU
  9,739,655,098 processor cycles
  0 bytes consed
  
---UNSAT---

Checked Bound: 7
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  3.628 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  0.22% CPU
  12,338,282,537 processor cycles
  32,752 bytes consed
  
---UNSAT---

Checked Bound: 8
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  4.344 seconds of real time
  0.012000 seconds of total run time (0.000000 user, 0.012000 system)
  0.28% CPU
  14,768,533,863 processor cycles
  32,752 bytes consed
  
---UNSAT---

Checked Bound: 9
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  5.108 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  0.16% CPU
  17,365,425,614 processor cycles
  0 bytes consed
  
---UNSAT---

Checked Bound: 10
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  5.719 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  0.14% CPU
  19,446,757,068 processor cycles
  32,752 bytes consed
  
---UNSAT---

Checked Bound: 11
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  6.350 seconds of real time
  0.008000 seconds of total run time (0.000000 user, 0.008000 system)
  0.13% CPU
  21,592,664,445 processor cycles
  32,752 bytes consed
  
---UNSAT---

Checked Bound: 12
This is BVZOT.

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  7.473 seconds of real time
  0.008000 seconds of total run time (0.004000 user, 0.004000 system)
  0.11% CPU
  25,405,708,299 processor cycles
  32,752 bytes consed
  
---SAT---
------ time 0 ------
  BIGBANG
------ time 1 ------
  SDSEARCH_APP
  SDSEARCH_ALT_OP1_PAR1_SCREEN_START
  SDSEARCH_PAR_SERVER1
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_ALT_OP1_START
  SDSEARCH_PAR_APP_END
  SDSEARCH_SCREEN
  SDSEARCH_PAR_OP1_APP_START
  MSGPINGS2_START
  SDSEARCH_SERVER2_START
  SDSEARCH_ALT_OP1_PAR1_OP2_START
  SDSEARCH_ALT_OP1_PAR1_OP1_START
  SDSEARCH_ALT_OP1_SCREEN_START
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP1_SCREEN_END
  SDSEARCH_PAR_OP2
  SDSEARCH
  SDSEARCH_ALT_OP1_PAR1_OP1_SCREEN
  SDSEARCH_PAR_OP1_START
  SDSEARCH_PAR_OP1_SERVER1
  SDSEARCH_PAR_OP2_APP_START
  SDSEARCH_PAR_APP_START
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN_START
  SDSEARCH_ALT_OP1_SCREEN
  SDSEARCH_SERVER1_START
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN
  SDSEARCH_PAR_OP2_APP_END
  SDSEARCH_ALT_OP1_PAR1_SCREEN
  SDSEARCH_PAR_OP2_START
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_START
  SDSEARCH_SCREEN_START
  MSGPINGS1
  SDSEARCH_ALT
  MSGPINGS2
  SDSEARCH_ALT_SCREEN
  SDSEARCH_PAR_SERVER1_START
  SDSEARCH_ALT_OP1_PAR1_OP1_SCREEN_START
  SDSEARCH_PAR_OP1
  SDSEARCH_SERVER1
  SDSEARCH_PAR_OP2_APP
  SDSEARCH_ALT_SCREEN_START
  SDSEARCH_PAR_OP1_SERVER1_END
  SDSEARCH_PAR_APP
  SDSEARCH_APP_START
  SDSEARCH_ALT_OP1
  SDSEARCH_PAR_OP1_APP
  SDSEARCH_PAR_START
  SDSEARCH_PAR_OP1_SERVER1_START
  MSGPINGS1_START
  SDSEARCH_ALT_OP1_PAR1_START
  SDSEARCH_START
  SDSEARCH_PAR_OP1_APP_END
  SDSEARCH_PAR
  MSGPINGS1_END
------ time 2 ------
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SCREEN
  SDSEARCH_PAR_SERVER2_START
  SDSEARCH_ALT_OP1_SERVER1_START
  SDSEARCH_PAR_SERVER1
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_PAR_OP2_SERVER2_START
  MSGREPLYS1_1ST
  SDSEARCH_ALT_OP1_PAR1_APP_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN_START
  SDSEARCH_SCREEN
  SDSEARCH_PAR_OP2_SERVER1_END
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1
  SDSEARCH_PAR_OP2
  SDSEARCH
  SDSEARCH_ALT_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SCREEN
  MSGPINGS2_END
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN
  SDSEARCH_PAR_OP2_SERVER2_END
  MSGREPLYS1_1ST_START
  SDSEARCH_ALT
  MSGPINGS2
  SDSEARCH_PAR_SERVER2
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_APP_START
  SDSEARCH_ALT_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_START
  SDSEARCH_PAR_OP1
  SDSEARCH_SERVER1
  SDSEARCH_PAR_OP2_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_PAR_OP2_SERVER1
  SDSEARCH_PAR_OP2_SERVER1_START
  SDSEARCH_ALT_OP1_APP
  SDSEARCH_ALT_SERVER1_START
  SDSEARCH_PAR_SERVER1_END
  SDSEARCH_ALT_OP1_APP_START
  SDSEARCH_ALT_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SCREEN_START
  SDSEARCH_PAR_OP2_SERVER2
  MSGREPLYS1_1ST_END
  SDSEARCH_PAR
------ time 3 ------
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_ALT_OP1_PAR1_OP2_APP_START
  LOOP1OP1MSGSEARCHNEXTS1_START
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_APP_START
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1
  SDSEARCH
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1_START
  SDSEARCH_PAR_OP1_END
  SDSEARCH_PAR_OP1_SERVER2_END
  SDSEARCH_ALT_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SERVER1_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER1_START
  SDSEARCH_ALT_OP1_PAR1_SCREEN
  SDSEARCH_PAR_END
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_PAR_SERVER2_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN
  SDSEARCH_ALT
  SDSEARCH_PAR_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_APP
  LOOP1OP1MSGSEARCHNEXTS1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_APP
  SDSEARCH_PAR_OP1
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_APP
  SDSEARCH_PAR_OP1_SERVER2_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1
  SDSEARCH_ALT_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1_START
  SDSEARCH_PAR_OP1_SERVER2
  LOOP1OP1MSGSEARCHNEXTS1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER1
  SDSEARCH_PAR
------ time 4 ------
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_SCREEN
  SDSEARCH_SERVER2
  LOOP1OP1MSGRESULTS1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1
  SDSEARCH
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER1_END
  SDSEARCH_ALT_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  LOOP1OP1MSGRESULTS1
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN
  SDSEARCH_ALT
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_APP
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_APP
  LOOP1OP1MSGRESULTS1_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1
  SDSEARCH_ALT_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER1
------ time 5 ------
  SDSEARCH_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER1_START
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_APP_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SCREEN
  LOOP1OP1MSGUPDATERESULTS1_START
  LOOP1OP1MSGUPDATERESULTS1
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER1
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_START
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1
  SDSEARCH
  SDSEARCH_ALT_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2
  SDSEARCH_ALT_OP1_PAR1_SCREEN
  SDSEARCH_ALT_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN
  SDSEARCH_ALT
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_APP
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1
  SDSEARCH_ALT_OP1
  SDSEARCH_ALT_SERVER2_START
------ time 6 ------
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SCREEN
  LOOP1OP1MSGUPDATERESULTS1
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_APP
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER1
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1
  SDSEARCH
  SDSEARCH_ALT_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2
  SDSEARCH_ALT_OP1_PAR1_SCREEN
  SDSEARCH_ALT_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN
  LOOP1OP2MSGSEARCHNEXTS1_START
  SDSEARCH_ALT
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_APP_START
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1
  SDSEARCH_ALT_OP1
  LOOP1OP2MSGSEARCHNEXTS1_END
  LOOP1OP2MSGSEARCHNEXTS1
------ time 7 ------
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SCREEN
  LOOP1OP1MSGUPDATERESULTS1
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_APP
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER1
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1_APP
  SDSEARCH
  LOOP1OP1MSGUPDATERESULTS1_END
  SDSEARCH_ALT_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2
  SDSEARCH_ALT_OP1_PAR1_SCREEN
  SDSEARCH_ALT_SERVER2
  LOOP1OP2MSGRESULTS1_END
  SDSEARCH_ALT_OP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN
  SDSEARCH_ALT
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_OP1_SERVER2_START
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_APP
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_PAR1_SERVER2_START
  SDSEARCH_ALT_OP1_APP
  LOOP1OP2MSGRESULTS1_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SCREEN_END
  LOOP1OP2MSGRESULTS1
  SDSEARCH_ALT_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER1_END
  SDSEARCH_ALT_OP1_PAR1_OP1_APP_START
  SDSEARCH_ALT_OP1_PAR1_SERVER2
------ time 8 ------
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER2_END
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_APP
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER2_START
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP1_APP
  SDSEARCH
  SDSEARCH_ALT_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2
  SDSEARCH_ALT_OP1_PAR1_SCREEN
  SDSEARCH_ALT_SERVER2
  LOOP1OP2MSGUPDATERESULTS1
  SDSEARCH_ALT_OP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN
  LOOP1OP2MSGUPDATERESULTS1_START
  SDSEARCH_ALT
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_SERVER1_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER2
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER2_START
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER2
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SCREEN_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP1_SERVER2_START
  SDSEARCH_ALT_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_APP_END
  SDSEARCH_ALT_OP1_PAR1_SERVER2
------ time 9 ------
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_END
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER2
  LOOP1OP3MSGSEARCHNEXTS1
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP1_APP
  SDSEARCH
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_APP
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER2_START
  SDSEARCH_ALT_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2
  SDSEARCH_ALT_OP1_PAR1_SCREEN
  SDSEARCH_ALT_SERVER2
  LOOP1OP2MSGUPDATERESULTS1
  SDSEARCH_ALT_OP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER2_START
  SDSEARCH_ALT
  LOOP1OP3MSGSEARCHNEXTS1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SERVER2_END
  SDSEARCH_ALT_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_APP_START
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1
  LOOP1OP3MSGSEARCHNEXTS1_START
  SDSEARCH_ALT_OP1
  LOOP1OP2MSGUPDATERESULTS1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP2_SCREEN_END
  SDSEARCH_ALT_OP1_PAR1_SERVER2
------ time 10 ------
  SDSEARCH_APP
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_SCREEN
  SDSEARCH_ALT_OP1_PAR1
  LOOP1OP3MSGRESULTS1
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER2_END
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_SERVER1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER1_END
  SDSEARCH
  LOOP1OP3MSGRESULTS1_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_APP
  SDSEARCH_ALT_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SCREEN
  SDSEARCH_ALT_SERVER2
  SDSEARCH_ALT_OP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_SERVER2_START
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER2_END
  SDSEARCH_ALT
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_SERVER2_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_SCREEN_START
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_SERVER2
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SERVER1
  LOOP1OP3MSGRESULTS1_END
  SDSEARCH_ALT_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_SERVER2
  SDSEARCH_ALT_OP1_PAR1_SERVER2
------ time 11 ------
  SDSEARCH_APP
  SDSEARCH_ALT_OP1_PAR1_SERVER2_END
  SDSEARCH_ALT_SERVER1
  SDSEARCH_ALT_SERVER1_END
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER1_START
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_SCREEN
  SDSEARCH_ALT_OP1_PAR1
  SDSEARCH_SERVER1_END
  SDSEARCH_ALT_SCREEN_END
  SDSEARCH_ALT_OP1_PAR1_END
  SDSEARCH_ALT_OP1_SERVER2_END
  SDSEARCH_ALT_SERVER2_END
  SDSEARCH_SCREEN
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER2
  MSGREPLYS2_1ST_START
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER1
  MSGREPLYS2_1ST_END
  SDSEARCH_ALT_OP1_PAR1_OP1_APP_END
  SDSEARCH_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_APP_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_END
  MSGREPLYS2_1ST
  SDSEARCH_ALT_OP1_SERVER1_END
  SDSEARCH_ALT_OP1_PAR1_OP1_APP
  SDSEARCH_ALT_APP_END
  SDSEARCH
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN_END
  LOOP1OP3MSGUPDATERESULTS1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_APP
  SDSEARCH_ALT_OP1_SCREEN
  SDSEARCH_ALT_OP1_PAR1_APP
  SDSEARCH_ALT_OP1_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_APP_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3_SCREEN_END
  SDSEARCH_ALT_OP1_PAR1_OP2_SCREEN
  LOOP1OP3MSGUPDATERESULTS1
  SDSEARCH_END
  SDSEARCH_ALT_OP1_PAR1_SCREEN
  SDSEARCH_ALT_SERVER2
  SDSEARCH_ALT_OP1_SERVER2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_OP3
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_END
  SDSEARCH_ALT_OP1_PAR1_OP2
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_SCREEN
  SDSEARCH_ALT
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER1_END
  SDSEARCH_ALT_OP1_PAR1_OP2_APP
  SDSEARCH_ALT_SCREEN
  SDSEARCH_ALT_OP1_PAR1_SERVER1
  SDSEARCH_ALT_APP
  SDSEARCH_ALT_OP1_PAR1_OP1_END
  LOOP1OP3MSGUPDATERESULTS1_START
  SDSEARCH_ALT_OP1_PAR1_SCREEN_END
  SDSEARCH_ALT_OP1_END
  SDSEARCH_ALT_OP1_PAR1_APP_END
  SDSEARCH_SERVER1
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1
  SDSEARCH_ALT_OP1_APP
  SDSEARCH_ALT_OP1_PAR1_OP2_END
  SDSEARCH_ALT_OP1_PAR1_SERVER1_END
  SDSEARCH_SERVER2_END
  SDSEARCH_ALT_OP1_APP_END
  SDSEARCH_ALT_OP1_SCREEN_END
  SDSEARCH_ALT_OP1
  SDSEARCH_APP_END
  SDSEARCH_ALT_OP1_PAR1_OP1_SERVER2_END
  SDSEARCH_ALT_OP1_PAR1_OP2_LOOP1_APP_END
  SDSEARCH_ALT_END
  SDSEARCH_SCREEN_END
  SDSEARCH_ALT_OP1_PAR1_SERVER2
------ time 12 ------
------ time 13 ------
**LOOP**
------ end of bvzot result ------

Found: 13
