This is SBCL 1.2.4.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
IPC-terms: ((YESTERDAY OBJPROC_1PARAMONE_NR) (YESTERDAY OBJPROC_1PARAMWIN_NR)
            (YESTERDAY OBJPROC_1PARAMTWO_NR) OBJPROC_1ATTRACTIVE
            (YESTERDAY OBJPROC_1ATTRACTIVE) OBJPROC_1ATTRMAX
            (YESTERDAY OBJPROC_1ATTRMAX) OBJPROC_1ATTRNEIGHBOURR
            (YESTERDAY OBJPROC_1ATTRNEIGHBOURR) OBJPROC_1ATTRMYNUMBER
            (YESTERDAY OBJPROC_1ATTRMYNUMBER) (YESTERDAY OBJPROC_4PARAMONE_NR)
            (YESTERDAY OBJPROC_4PARAMWIN_NR) (YESTERDAY OBJPROC_4PARAMTWO_NR)
            OBJPROC_4ATTRACTIVE (YESTERDAY OBJPROC_4ATTRACTIVE)
            OBJPROC_4ATTRMAX (YESTERDAY OBJPROC_4ATTRMAX)
            OBJPROC_4ATTRNEIGHBOURR (YESTERDAY OBJPROC_4ATTRNEIGHBOURR)
            OBJPROC_4ATTRMYNUMBER (YESTERDAY OBJPROC_4ATTRMYNUMBER)
            (YESTERDAY OBJPROC_6PARAMONE_NR) (YESTERDAY OBJPROC_6PARAMWIN_NR)
            (YESTERDAY OBJPROC_6PARAMTWO_NR) OBJPROC_6ATTRACTIVE
            (YESTERDAY OBJPROC_6ATTRACTIVE) OBJPROC_6ATTRMAX
            (YESTERDAY OBJPROC_6ATTRMAX) OBJPROC_6ATTRNEIGHBOURR
            (YESTERDAY OBJPROC_6ATTRNEIGHBOURR) OBJPROC_6ATTRMYNUMBER
            (YESTERDAY OBJPROC_6ATTRMYNUMBER) (YESTERDAY OBJPROC_3PARAMONE_NR)
            OBJPROC_4PARAMWIN_NR (YESTERDAY OBJPROC_3PARAMWIN_NR)
            OBJPROC_4PARAMTWO_NR (YESTERDAY OBJPROC_3PARAMTWO_NR)
            OBJPROC_4PARAMONE_NR OBJPROC_3ATTRACTIVE
            (YESTERDAY OBJPROC_3ATTRACTIVE) OBJPROC_3ATTRMAX
            (YESTERDAY OBJPROC_3ATTRMAX) OBJPROC_3ATTRNEIGHBOURR
            (YESTERDAY OBJPROC_3ATTRNEIGHBOURR) OBJPROC_3ATTRMYNUMBER
            (YESTERDAY OBJPROC_3ATTRMYNUMBER) (YESTERDAY OBJPROC_0PARAMONE_NR)
            OBJPROC_0PARAMONE_NR OBJPROC_1PARAMWIN_NR
            (YESTERDAY OBJPROC_0PARAMWIN_NR) OBJPROC_0PARAMWIN_NR
            OBJPROC_1PARAMTWO_NR (YESTERDAY OBJPROC_0PARAMTWO_NR)
            OBJPROC_1PARAMONE_NR OBJPROC_0PARAMTWO_NR OBJPROC_0ATTRACTIVE
            (YESTERDAY OBJPROC_0ATTRACTIVE) OBJPROC_0ATTRMAX
            (YESTERDAY OBJPROC_0ATTRMAX) OBJPROC_0ATTRNEIGHBOURR
            (YESTERDAY OBJPROC_0ATTRNEIGHBOURR) OBJPROC_0ATTRMYNUMBER
            (YESTERDAY OBJPROC_0ATTRMYNUMBER) (YESTERDAY OBJPROC_5PARAMONE_NR)
            OBJPROC_5PARAMONE_NR OBJPROC_6PARAMWIN_NR
            (YESTERDAY OBJPROC_5PARAMWIN_NR) OBJPROC_5PARAMWIN_NR
            OBJPROC_6PARAMTWO_NR (YESTERDAY OBJPROC_5PARAMTWO_NR)
            OBJPROC_6PARAMONE_NR OBJPROC_5PARAMTWO_NR OBJPROC_5ATTRACTIVE
            (YESTERDAY OBJPROC_5ATTRACTIVE) OBJPROC_5ATTRMAX
            (YESTERDAY OBJPROC_5ATTRMAX) OBJPROC_5ATTRNEIGHBOURR
            (YESTERDAY OBJPROC_5ATTRNEIGHBOURR) OBJPROC_5ATTRMYNUMBER
            (YESTERDAY OBJPROC_5ATTRMYNUMBER) (YESTERDAY OBJPROC_2PARAMONE_NR)
            OBJPROC_2PARAMONE_NR OBJPROC_3PARAMWIN_NR
            (YESTERDAY OBJPROC_2PARAMWIN_NR) OBJPROC_2PARAMWIN_NR
            OBJPROC_3PARAMTWO_NR (YESTERDAY OBJPROC_2PARAMTWO_NR)
            OBJPROC_3PARAMONE_NR 0 OBJPROC_2PARAMTWO_NR 1 OBJPROC_2ATTRACTIVE
            (YESTERDAY OBJPROC_2ATTRACTIVE) OBJPROC_2ATTRMAX
            (YESTERDAY OBJPROC_2ATTRMAX) OBJPROC_2ATTRNEIGHBOURR
            (YESTERDAY OBJPROC_2ATTRNEIGHBOURR) OBJPROC_2ATTRMYNUMBER
            (YESTERDAY OBJPROC_2ATTRMYNUMBER))
IPC-constraints: ((= OBJPROC_5ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_4ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_4ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_3ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_3ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_3ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_2ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_2ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_2ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_2ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_1ATTRMYNUMBER)
                  (= OBJPROC_2PARAMWIN_NR (YESTERDAY OBJPROC_1PARAMONE_NR))
                  (= OBJPROC_2PARAMONE_NR (YESTERDAY OBJPROC_1PARAMONE_NR))
                  (= OBJPROC_1ATTRNEIGHBOURR (YESTERDAY OBJPROC_1PARAMONE_NR))
                  (= OBJPROC_2PARAMTWO_NR (YESTERDAY OBJPROC_1PARAMONE_NR))
                  (= OBJPROC_1PARAMONE_NR OBJPROC_1ATTRMAX)
                  (= OBJPROC_2PARAMWIN_NR (YESTERDAY OBJPROC_1PARAMWIN_NR))
                  (= OBJPROC_1PARAMWIN_NR OBJPROC_1ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMAX OBJPROC_1ATTRMYNUMBER)
                  (= OBJPROC_2PARAMONE_NR OBJPROC_1ATTRMYNUMBER)
                  (= OBJPROC_2PARAMTWO_NR (YESTERDAY OBJPROC_1PARAMTWO_NR))
                  (= OBJPROC_2PARAMONE_NR (YESTERDAY OBJPROC_1ATTRNEIGHBOURR))
                  (= OBJPROC_1ATTRMAX (YESTERDAY OBJPROC_1ATTRNEIGHBOURR))
                  (> OBJPROC_1ATTRNEIGHBOURR OBJPROC_1ATTRMAX)
                  (> OBJPROC_1ATTRNEIGHBOURR OBJPROC_1PARAMTWO_NR)
                  (= OBJPROC_1ATTRACTIVE 0)
                  (<= OBJPROC_1ATTRNEIGHBOURR OBJPROC_1ATTRMAX)
                  (<= OBJPROC_1ATTRNEIGHBOURR OBJPROC_1PARAMTWO_NR)
                  (= OBJPROC_1ATTRACTIVE 1)
                  (= OBJPROC_1ATTRACTIVE (YESTERDAY OBJPROC_1ATTRACTIVE))
                  (= OBJPROC_1ATTRMAX (YESTERDAY OBJPROC_1ATTRMAX))
                  (= OBJPROC_1ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_1ATTRNEIGHBOURR))
                  (= OBJPROC_1ATTRMYNUMBER (YESTERDAY OBJPROC_1ATTRMYNUMBER))
                  (= OBJPROC_5PARAMWIN_NR (YESTERDAY OBJPROC_4PARAMONE_NR))
                  (= OBJPROC_5PARAMONE_NR (YESTERDAY OBJPROC_4PARAMONE_NR))
                  (= OBJPROC_4ATTRNEIGHBOURR (YESTERDAY OBJPROC_4PARAMONE_NR))
                  (= OBJPROC_5PARAMTWO_NR (YESTERDAY OBJPROC_4PARAMONE_NR))
                  (= OBJPROC_4PARAMONE_NR OBJPROC_4ATTRMAX)
                  (= OBJPROC_5PARAMWIN_NR (YESTERDAY OBJPROC_4PARAMWIN_NR))
                  (= OBJPROC_4PARAMWIN_NR OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_4ATTRMAX OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_5PARAMONE_NR OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_5PARAMTWO_NR (YESTERDAY OBJPROC_4PARAMTWO_NR))
                  (= OBJPROC_5PARAMONE_NR (YESTERDAY OBJPROC_4ATTRNEIGHBOURR))
                  (= OBJPROC_4ATTRMAX (YESTERDAY OBJPROC_4ATTRNEIGHBOURR))
                  (> OBJPROC_4ATTRNEIGHBOURR OBJPROC_4ATTRMAX)
                  (> OBJPROC_4ATTRNEIGHBOURR OBJPROC_4PARAMTWO_NR)
                  (= OBJPROC_4ATTRACTIVE 0)
                  (<= OBJPROC_4ATTRNEIGHBOURR OBJPROC_4ATTRMAX)
                  (<= OBJPROC_4ATTRNEIGHBOURR OBJPROC_4PARAMTWO_NR)
                  (= OBJPROC_4ATTRACTIVE 1)
                  (= OBJPROC_4ATTRACTIVE (YESTERDAY OBJPROC_4ATTRACTIVE))
                  (= OBJPROC_4ATTRMAX (YESTERDAY OBJPROC_4ATTRMAX))
                  (= OBJPROC_4ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_4ATTRNEIGHBOURR))
                  (= OBJPROC_4ATTRMYNUMBER (YESTERDAY OBJPROC_4ATTRMYNUMBER))
                  (= OBJPROC_0PARAMWIN_NR (YESTERDAY OBJPROC_6PARAMONE_NR))
                  (= OBJPROC_0PARAMONE_NR (YESTERDAY OBJPROC_6PARAMONE_NR))
                  (= OBJPROC_6ATTRNEIGHBOURR (YESTERDAY OBJPROC_6PARAMONE_NR))
                  (= OBJPROC_0PARAMTWO_NR (YESTERDAY OBJPROC_6PARAMONE_NR))
                  (= OBJPROC_6PARAMONE_NR OBJPROC_6ATTRMAX)
                  (= OBJPROC_0PARAMWIN_NR (YESTERDAY OBJPROC_6PARAMWIN_NR))
                  (= OBJPROC_6PARAMWIN_NR OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_6ATTRMAX OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_0PARAMONE_NR OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_0PARAMTWO_NR (YESTERDAY OBJPROC_6PARAMTWO_NR))
                  (= OBJPROC_0PARAMONE_NR (YESTERDAY OBJPROC_6ATTRNEIGHBOURR))
                  (= OBJPROC_6ATTRMAX (YESTERDAY OBJPROC_6ATTRNEIGHBOURR))
                  (> OBJPROC_6ATTRNEIGHBOURR OBJPROC_6ATTRMAX)
                  (> OBJPROC_6ATTRNEIGHBOURR OBJPROC_6PARAMTWO_NR)
                  (= OBJPROC_6ATTRACTIVE 0)
                  (<= OBJPROC_6ATTRNEIGHBOURR OBJPROC_6ATTRMAX)
                  (<= OBJPROC_6ATTRNEIGHBOURR OBJPROC_6PARAMTWO_NR)
                  (= OBJPROC_6ATTRACTIVE 1)
                  (= OBJPROC_6ATTRACTIVE (YESTERDAY OBJPROC_6ATTRACTIVE))
                  (= OBJPROC_6ATTRMAX (YESTERDAY OBJPROC_6ATTRMAX))
                  (= OBJPROC_6ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_6ATTRNEIGHBOURR))
                  (= OBJPROC_6ATTRMYNUMBER (YESTERDAY OBJPROC_6ATTRMYNUMBER))
                  (= OBJPROC_4PARAMWIN_NR (YESTERDAY OBJPROC_3PARAMONE_NR))
                  (= OBJPROC_4PARAMONE_NR (YESTERDAY OBJPROC_3PARAMONE_NR))
                  (= OBJPROC_3ATTRNEIGHBOURR (YESTERDAY OBJPROC_3PARAMONE_NR))
                  (= OBJPROC_4PARAMTWO_NR (YESTERDAY OBJPROC_3PARAMONE_NR))
                  (= OBJPROC_3PARAMONE_NR OBJPROC_3ATTRMAX)
                  (= OBJPROC_4PARAMWIN_NR (YESTERDAY OBJPROC_3PARAMWIN_NR))
                  (= OBJPROC_3PARAMWIN_NR OBJPROC_3ATTRMYNUMBER)
                  (= OBJPROC_3ATTRMAX OBJPROC_3ATTRMYNUMBER)
                  (= OBJPROC_4PARAMONE_NR OBJPROC_3ATTRMYNUMBER)
                  (= OBJPROC_4PARAMTWO_NR (YESTERDAY OBJPROC_3PARAMTWO_NR))
                  (= OBJPROC_4PARAMONE_NR (YESTERDAY OBJPROC_3ATTRNEIGHBOURR))
                  (= OBJPROC_3ATTRMAX (YESTERDAY OBJPROC_3ATTRNEIGHBOURR))
                  (> OBJPROC_3ATTRNEIGHBOURR OBJPROC_3ATTRMAX)
                  (> OBJPROC_3ATTRNEIGHBOURR OBJPROC_3PARAMTWO_NR)
                  (= OBJPROC_3ATTRACTIVE 0)
                  (<= OBJPROC_3ATTRNEIGHBOURR OBJPROC_3ATTRMAX)
                  (<= OBJPROC_3ATTRNEIGHBOURR OBJPROC_3PARAMTWO_NR)
                  (= OBJPROC_3ATTRACTIVE 1)
                  (= OBJPROC_3ATTRACTIVE (YESTERDAY OBJPROC_3ATTRACTIVE))
                  (= OBJPROC_3ATTRMAX (YESTERDAY OBJPROC_3ATTRMAX))
                  (= OBJPROC_3ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_3ATTRNEIGHBOURR))
                  (= OBJPROC_3ATTRMYNUMBER (YESTERDAY OBJPROC_3ATTRMYNUMBER))
                  (= OBJPROC_1PARAMWIN_NR (YESTERDAY OBJPROC_0PARAMONE_NR))
                  (= OBJPROC_1PARAMONE_NR (YESTERDAY OBJPROC_0PARAMONE_NR))
                  (= OBJPROC_0ATTRNEIGHBOURR (YESTERDAY OBJPROC_0PARAMONE_NR))
                  (= OBJPROC_1PARAMTWO_NR (YESTERDAY OBJPROC_0PARAMONE_NR))
                  (= OBJPROC_0PARAMONE_NR OBJPROC_0ATTRMAX)
                  (= OBJPROC_1PARAMWIN_NR (YESTERDAY OBJPROC_0PARAMWIN_NR))
                  (= OBJPROC_0PARAMWIN_NR OBJPROC_0ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMAX OBJPROC_0ATTRMYNUMBER)
                  (= OBJPROC_1PARAMONE_NR OBJPROC_0ATTRMYNUMBER)
                  (= OBJPROC_1PARAMTWO_NR (YESTERDAY OBJPROC_0PARAMTWO_NR))
                  (= OBJPROC_1PARAMONE_NR (YESTERDAY OBJPROC_0ATTRNEIGHBOURR))
                  (= OBJPROC_0ATTRMAX (YESTERDAY OBJPROC_0ATTRNEIGHBOURR))
                  (> OBJPROC_0ATTRNEIGHBOURR OBJPROC_0ATTRMAX)
                  (> OBJPROC_0ATTRNEIGHBOURR OBJPROC_0PARAMTWO_NR)
                  (= OBJPROC_0ATTRACTIVE 0)
                  (<= OBJPROC_0ATTRNEIGHBOURR OBJPROC_0ATTRMAX)
                  (<= OBJPROC_0ATTRNEIGHBOURR OBJPROC_0PARAMTWO_NR)
                  (= OBJPROC_0ATTRACTIVE 1)
                  (= OBJPROC_0ATTRACTIVE (YESTERDAY OBJPROC_0ATTRACTIVE))
                  (= OBJPROC_0ATTRMAX (YESTERDAY OBJPROC_0ATTRMAX))
                  (= OBJPROC_0ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_0ATTRNEIGHBOURR))
                  (= OBJPROC_0ATTRMYNUMBER (YESTERDAY OBJPROC_0ATTRMYNUMBER))
                  (= OBJPROC_6PARAMWIN_NR (YESTERDAY OBJPROC_5PARAMONE_NR))
                  (= OBJPROC_6PARAMONE_NR (YESTERDAY OBJPROC_5PARAMONE_NR))
                  (= OBJPROC_5ATTRNEIGHBOURR (YESTERDAY OBJPROC_5PARAMONE_NR))
                  (= OBJPROC_6PARAMTWO_NR (YESTERDAY OBJPROC_5PARAMONE_NR))
                  (= OBJPROC_5PARAMONE_NR OBJPROC_5ATTRMAX)
                  (= OBJPROC_6PARAMWIN_NR (YESTERDAY OBJPROC_5PARAMWIN_NR))
                  (= OBJPROC_5PARAMWIN_NR OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_5ATTRMAX OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_6PARAMONE_NR OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_6PARAMTWO_NR (YESTERDAY OBJPROC_5PARAMTWO_NR))
                  (= OBJPROC_6PARAMONE_NR (YESTERDAY OBJPROC_5ATTRNEIGHBOURR))
                  (= OBJPROC_5ATTRMAX (YESTERDAY OBJPROC_5ATTRNEIGHBOURR))
                  (> OBJPROC_5ATTRNEIGHBOURR OBJPROC_5ATTRMAX)
                  (> OBJPROC_5ATTRNEIGHBOURR OBJPROC_5PARAMTWO_NR)
                  (= OBJPROC_5ATTRACTIVE 0)
                  (<= OBJPROC_5ATTRNEIGHBOURR OBJPROC_5ATTRMAX)
                  (<= OBJPROC_5ATTRNEIGHBOURR OBJPROC_5PARAMTWO_NR)
                  (= OBJPROC_5ATTRACTIVE 1)
                  (= OBJPROC_5ATTRACTIVE (YESTERDAY OBJPROC_5ATTRACTIVE))
                  (= OBJPROC_5ATTRMAX (YESTERDAY OBJPROC_5ATTRMAX))
                  (= OBJPROC_5ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_5ATTRNEIGHBOURR))
                  (= OBJPROC_5ATTRMYNUMBER (YESTERDAY OBJPROC_5ATTRMYNUMBER))
                  (= OBJPROC_3PARAMWIN_NR (YESTERDAY OBJPROC_2PARAMONE_NR))
                  (= OBJPROC_3PARAMONE_NR (YESTERDAY OBJPROC_2PARAMONE_NR))
                  (= OBJPROC_2ATTRNEIGHBOURR (YESTERDAY OBJPROC_2PARAMONE_NR))
                  (= OBJPROC_3PARAMTWO_NR (YESTERDAY OBJPROC_2PARAMONE_NR))
                  (= OBJPROC_2PARAMONE_NR OBJPROC_2ATTRMAX)
                  (= OBJPROC_3PARAMWIN_NR (YESTERDAY OBJPROC_2PARAMWIN_NR))
                  (= OBJPROC_2PARAMWIN_NR OBJPROC_2ATTRMYNUMBER)
                  (= OBJPROC_2ATTRMAX OBJPROC_2ATTRMYNUMBER)
                  (= OBJPROC_3PARAMONE_NR OBJPROC_2ATTRMYNUMBER)
                  (= OBJPROC_3PARAMTWO_NR (YESTERDAY OBJPROC_2PARAMTWO_NR))
                  (= OBJPROC_3PARAMONE_NR (YESTERDAY OBJPROC_2ATTRNEIGHBOURR))
                  (= OBJPROC_2ATTRMAX (YESTERDAY OBJPROC_2ATTRNEIGHBOURR))
                  (> OBJPROC_2ATTRNEIGHBOURR OBJPROC_2ATTRMAX)
                  (> OBJPROC_2ATTRNEIGHBOURR OBJPROC_2PARAMTWO_NR)
                  (= OBJPROC_2ATTRACTIVE 0)
                  (<= OBJPROC_2ATTRNEIGHBOURR OBJPROC_2ATTRMAX)
                  (<= OBJPROC_2ATTRNEIGHBOURR OBJPROC_2PARAMTWO_NR)
                  (= OBJPROC_2ATTRACTIVE 1)
                  (= OBJPROC_2ATTRACTIVE (YESTERDAY OBJPROC_2ATTRACTIVE))
                  (= OBJPROC_2ATTRMAX (YESTERDAY OBJPROC_2ATTRMAX))
                  (= OBJPROC_2ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_2ATTRNEIGHBOURR))
                  (= OBJPROC_2ATTRMYNUMBER (YESTERDAY OBJPROC_2ATTRMYNUMBER)))
This is AE2SBVZOT.

1. processing formula
Used boolean propositions: 
((= OBJPROC_5ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_4ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_4ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
 (= OBJPROC_3ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_3ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
 (= OBJPROC_3ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
 (= OBJPROC_2ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_2ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
 (= OBJPROC_2ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
 (= OBJPROC_2ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER)
 (= OBJPROC_1ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_1ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
 (= OBJPROC_1ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
 (= OBJPROC_1ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER)
 (= OBJPROC_1ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_1ATTRMYNUMBER)
 (= OBJPROC_2PARAMWIN_NR (YESTERDAY OBJPROC_1PARAMONE_NR))
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_2PARAMONE_NR (YESTERDAY OBJPROC_1PARAMONE_NR))
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_1ATTRNEIGHBOURR (YESTERDAY OBJPROC_1PARAMONE_NR))
 (= OBJPROC_2PARAMTWO_NR (YESTERDAY OBJPROC_1PARAMONE_NR))
 (= OBJPROC_1PARAMONE_NR OBJPROC_1ATTRMAX)
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_2PARAMWIN_NR (YESTERDAY OBJPROC_1PARAMWIN_NR))
 (= OBJPROC_1PARAMWIN_NR OBJPROC_1ATTRMYNUMBER)
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_1ATTRMAX OBJPROC_1ATTRMYNUMBER)
 (= OBJPROC_2PARAMONE_NR OBJPROC_1ATTRMYNUMBER)
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TIMECONDITION
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_2PARAMTWO_NR (YESTERDAY OBJPROC_1PARAMTWO_NR))
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_2PARAMONE_NR (YESTERDAY OBJPROC_1ATTRNEIGHBOURR))
 (= OBJPROC_1ATTRMAX (YESTERDAY OBJPROC_1ATTRNEIGHBOURR))
 (> OBJPROC_1ATTRNEIGHBOURR OBJPROC_1ATTRMAX)
 (> OBJPROC_1ATTRNEIGHBOURR OBJPROC_1PARAMTWO_NR)
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_1ATTRACTIVE 0) (<= OBJPROC_1ATTRNEIGHBOURR OBJPROC_1ATTRMAX)
 (<= OBJPROC_1ATTRNEIGHBOURR OBJPROC_1PARAMTWO_NR) (= OBJPROC_1ATTRACTIVE 1)
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS4-CREESTAJMMF3ZX1Q
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS5-CREESTAJMMF3ZX1Q
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_1_STDPROCESS_SM_STATEINIT_EXIT OBJPROC_1_STDPROCESS_SM_STATEINIT_ENTER
 $OBJPROC_1_STDPROCESS_SM_STATEINIT OBJPROC_1_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q
 OBJPROC_1_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_1_STDPROCESS_SM_STATEMAIN
 OBJPROC_1_STDPROCESS_SM_STATEWIN_EXIT
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q
 OBJPROC_1_STDPROCESS_SM_STATEWIN_ENTER $OBJPROC_1_STDPROCESS_SM_STATEWIN
 OBJPROC_1_STDPROCESS_SM_STATELOST_EXIT
 OBJPROC_1_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q
 OBJPROC_1_STDPROCESS_SM_STATELOST_ENTER $OBJPROC_1_STDPROCESS_SM_STATELOST
 (= OBJPROC_1ATTRACTIVE (YESTERDAY OBJPROC_1ATTRACTIVE))
 OBJPROC_1ASSIGNMENT_EQMS5-CREESTAJMMF3ZX1QACTIVE
 (= OBJPROC_1ATTRMAX (YESTERDAY OBJPROC_1ATTRMAX))
 OBJPROC_1ASSIGNMENT_EQMS4UCREESTAJMMF3ZX1QMAX
 OBJPROC_1ASSIGNMENT_EQMS5UCREESTAJMMF3ZX1QMAX
 (= OBJPROC_1ATTRNEIGHBOURR (YESTERDAY OBJPROC_1ATTRNEIGHBOURR))
 OBJPROC_1ASSIGNMENT_EQMS5ECREESTAJMMF3ZX1QNEIGHBOURR
 (= OBJPROC_1ATTRMYNUMBER (YESTERDAY OBJPROC_1ATTRMYNUMBER)) OBJPROC_1OPONE
 OBJPROC_1OPWINNER OBJPROC_1OPTWO
 (= OBJPROC_5PARAMWIN_NR (YESTERDAY OBJPROC_4PARAMONE_NR))
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_5PARAMONE_NR (YESTERDAY OBJPROC_4PARAMONE_NR))
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_4ATTRNEIGHBOURR (YESTERDAY OBJPROC_4PARAMONE_NR))
 (= OBJPROC_5PARAMTWO_NR (YESTERDAY OBJPROC_4PARAMONE_NR))
 (= OBJPROC_4PARAMONE_NR OBJPROC_4ATTRMAX)
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_5PARAMWIN_NR (YESTERDAY OBJPROC_4PARAMWIN_NR))
 (= OBJPROC_4PARAMWIN_NR OBJPROC_4ATTRMYNUMBER)
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_4ATTRMAX OBJPROC_4ATTRMYNUMBER)
 (= OBJPROC_5PARAMONE_NR OBJPROC_4ATTRMYNUMBER)
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TIMECONDITION
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_5PARAMTWO_NR (YESTERDAY OBJPROC_4PARAMTWO_NR))
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_5PARAMONE_NR (YESTERDAY OBJPROC_4ATTRNEIGHBOURR))
 (= OBJPROC_4ATTRMAX (YESTERDAY OBJPROC_4ATTRNEIGHBOURR))
 (> OBJPROC_4ATTRNEIGHBOURR OBJPROC_4ATTRMAX)
 (> OBJPROC_4ATTRNEIGHBOURR OBJPROC_4PARAMTWO_NR)
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_4ATTRACTIVE 0) (<= OBJPROC_4ATTRNEIGHBOURR OBJPROC_4ATTRMAX)
 (<= OBJPROC_4ATTRNEIGHBOURR OBJPROC_4PARAMTWO_NR) (= OBJPROC_4ATTRACTIVE 1)
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS4-CREESTAJMMF3ZX1Q
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS5-CREESTAJMMF3ZX1Q
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_4_STDPROCESS_SM_STATEINIT_EXIT OBJPROC_4_STDPROCESS_SM_STATEINIT_ENTER
 $OBJPROC_4_STDPROCESS_SM_STATEINIT OBJPROC_4_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q
 OBJPROC_4_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_4_STDPROCESS_SM_STATEMAIN
 OBJPROC_4_STDPROCESS_SM_STATEWIN_EXIT
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q
 OBJPROC_4_STDPROCESS_SM_STATEWIN_ENTER $OBJPROC_4_STDPROCESS_SM_STATEWIN
 OBJPROC_4_STDPROCESS_SM_STATELOST_EXIT
 OBJPROC_4_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q
 OBJPROC_4_STDPROCESS_SM_STATELOST_ENTER $OBJPROC_4_STDPROCESS_SM_STATELOST
 (= OBJPROC_4ATTRACTIVE (YESTERDAY OBJPROC_4ATTRACTIVE))
 OBJPROC_4ASSIGNMENT_EQMS5-CREESTAJMMF3ZX1QACTIVE
 (= OBJPROC_4ATTRMAX (YESTERDAY OBJPROC_4ATTRMAX))
 OBJPROC_4ASSIGNMENT_EQMS4UCREESTAJMMF3ZX1QMAX
 OBJPROC_4ASSIGNMENT_EQMS5UCREESTAJMMF3ZX1QMAX
 (= OBJPROC_4ATTRNEIGHBOURR (YESTERDAY OBJPROC_4ATTRNEIGHBOURR))
 OBJPROC_4ASSIGNMENT_EQMS5ECREESTAJMMF3ZX1QNEIGHBOURR
 (= OBJPROC_4ATTRMYNUMBER (YESTERDAY OBJPROC_4ATTRMYNUMBER)) OBJPROC_4OPONE
 OBJPROC_4OPWINNER OBJPROC_4OPTWO
 (= OBJPROC_0PARAMWIN_NR (YESTERDAY OBJPROC_6PARAMONE_NR))
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_0PARAMONE_NR (YESTERDAY OBJPROC_6PARAMONE_NR))
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_6ATTRNEIGHBOURR (YESTERDAY OBJPROC_6PARAMONE_NR))
 (= OBJPROC_0PARAMTWO_NR (YESTERDAY OBJPROC_6PARAMONE_NR))
 (= OBJPROC_6PARAMONE_NR OBJPROC_6ATTRMAX)
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_0PARAMWIN_NR (YESTERDAY OBJPROC_6PARAMWIN_NR))
 (= OBJPROC_6PARAMWIN_NR OBJPROC_6ATTRMYNUMBER)
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_6ATTRMAX OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_0PARAMONE_NR OBJPROC_6ATTRMYNUMBER)
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TIMECONDITION
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_0PARAMTWO_NR (YESTERDAY OBJPROC_6PARAMTWO_NR))
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_0PARAMONE_NR (YESTERDAY OBJPROC_6ATTRNEIGHBOURR))
 (= OBJPROC_6ATTRMAX (YESTERDAY OBJPROC_6ATTRNEIGHBOURR))
 (> OBJPROC_6ATTRNEIGHBOURR OBJPROC_6ATTRMAX)
 (> OBJPROC_6ATTRNEIGHBOURR OBJPROC_6PARAMTWO_NR)
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_6ATTRACTIVE 0) (<= OBJPROC_6ATTRNEIGHBOURR OBJPROC_6ATTRMAX)
 (<= OBJPROC_6ATTRNEIGHBOURR OBJPROC_6PARAMTWO_NR) (= OBJPROC_6ATTRACTIVE 1)
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS4-CREESTAJMMF3ZX1Q
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS5-CREESTAJMMF3ZX1Q
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_6_STDPROCESS_SM_STATEINIT_EXIT OBJPROC_6_STDPROCESS_SM_STATEINIT_ENTER
 $OBJPROC_6_STDPROCESS_SM_STATEINIT OBJPROC_6_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q
 OBJPROC_6_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_6_STDPROCESS_SM_STATEMAIN
 OBJPROC_6_STDPROCESS_SM_STATEWIN_EXIT
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q
 OBJPROC_6_STDPROCESS_SM_STATEWIN_ENTER $OBJPROC_6_STDPROCESS_SM_STATEWIN
 OBJPROC_6_STDPROCESS_SM_STATELOST_EXIT
 OBJPROC_6_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q
 OBJPROC_6_STDPROCESS_SM_STATELOST_ENTER $OBJPROC_6_STDPROCESS_SM_STATELOST
 (= OBJPROC_6ATTRACTIVE (YESTERDAY OBJPROC_6ATTRACTIVE))
 OBJPROC_6ASSIGNMENT_EQMS5-CREESTAJMMF3ZX1QACTIVE
 (= OBJPROC_6ATTRMAX (YESTERDAY OBJPROC_6ATTRMAX))
 OBJPROC_6ASSIGNMENT_EQMS4UCREESTAJMMF3ZX1QMAX
 OBJPROC_6ASSIGNMENT_EQMS5UCREESTAJMMF3ZX1QMAX
 (= OBJPROC_6ATTRNEIGHBOURR (YESTERDAY OBJPROC_6ATTRNEIGHBOURR))
 OBJPROC_6ASSIGNMENT_EQMS5ECREESTAJMMF3ZX1QNEIGHBOURR
 (= OBJPROC_6ATTRMYNUMBER (YESTERDAY OBJPROC_6ATTRMYNUMBER)) OBJPROC_6OPONE
 OBJPROC_6OPWINNER OBJPROC_6OPTWO
 (= OBJPROC_4PARAMWIN_NR (YESTERDAY OBJPROC_3PARAMONE_NR))
 OBJPROC_4OPWINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_4PARAMONE_NR (YESTERDAY OBJPROC_3PARAMONE_NR))
 OBJPROC_4OPONETR_EQMS4-CREESTAJMMF3ZX1Q_CALL
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_3ATTRNEIGHBOURR (YESTERDAY OBJPROC_3PARAMONE_NR))
 (= OBJPROC_4PARAMTWO_NR (YESTERDAY OBJPROC_3PARAMONE_NR))
 OBJPROC_4OPTWOTR_EQMS5ECREESTAJMMF3ZX1Q_CALL
 (= OBJPROC_3PARAMONE_NR OBJPROC_3ATTRMAX)
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_4OPWINNERTR_EQMS6ECREESTAJMMF3ZX1Q_CALL
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_4PARAMWIN_NR (YESTERDAY OBJPROC_3PARAMWIN_NR))
 OBJPROC_4OPWINNERTR_EQMS6UCREESTAJMMF3ZX1Q_CALL
 (= OBJPROC_3PARAMWIN_NR OBJPROC_3ATTRMYNUMBER)
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_3ATTRMAX OBJPROC_3ATTRMYNUMBER)
 (= OBJPROC_4PARAMONE_NR OBJPROC_3ATTRMYNUMBER)
 OBJPROC_4OPONETR_EQMS4UCREESTAJMMF3ZX1Q_CALL
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TIMECONDITION
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_4PARAMTWO_NR (YESTERDAY OBJPROC_3PARAMTWO_NR))
 OBJPROC_4OPTWOTR_EQMS5OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_4PARAMONE_NR (YESTERDAY OBJPROC_3ATTRNEIGHBOURR))
 OBJPROC_4OPONETR_EQMS5UCREESTAJMMF3ZX1Q_CALL
 (= OBJPROC_3ATTRMAX (YESTERDAY OBJPROC_3ATTRNEIGHBOURR))
 (> OBJPROC_3ATTRNEIGHBOURR OBJPROC_3ATTRMAX)
 (> OBJPROC_3ATTRNEIGHBOURR OBJPROC_3PARAMTWO_NR)
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_3ATTRACTIVE 0) (<= OBJPROC_3ATTRNEIGHBOURR OBJPROC_3ATTRMAX)
 (<= OBJPROC_3ATTRNEIGHBOURR OBJPROC_3PARAMTWO_NR) (= OBJPROC_3ATTRACTIVE 1)
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS4-CREESTAJMMF3ZX1Q
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS5-CREESTAJMMF3ZX1Q
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_3_STDPROCESS_SM_STATEINIT_EXIT OBJPROC_3_STDPROCESS_SM_STATEINIT_ENTER
 $OBJPROC_3_STDPROCESS_SM_STATEINIT OBJPROC_3_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q
 OBJPROC_3_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_3_STDPROCESS_SM_STATEMAIN
 OBJPROC_3_STDPROCESS_SM_STATEWIN_EXIT
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q
 OBJPROC_3_STDPROCESS_SM_STATEWIN_ENTER $OBJPROC_3_STDPROCESS_SM_STATEWIN
 OBJPROC_3_STDPROCESS_SM_STATELOST_EXIT
 OBJPROC_3_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q
 OBJPROC_3_STDPROCESS_SM_STATELOST_ENTER $OBJPROC_3_STDPROCESS_SM_STATELOST
 (= OBJPROC_3ATTRACTIVE (YESTERDAY OBJPROC_3ATTRACTIVE))
 OBJPROC_3ASSIGNMENT_EQMS5-CREESTAJMMF3ZX1QACTIVE
 (= OBJPROC_3ATTRMAX (YESTERDAY OBJPROC_3ATTRMAX))
 OBJPROC_3ASSIGNMENT_EQMS4UCREESTAJMMF3ZX1QMAX
 OBJPROC_3ASSIGNMENT_EQMS5UCREESTAJMMF3ZX1QMAX
 (= OBJPROC_3ATTRNEIGHBOURR (YESTERDAY OBJPROC_3ATTRNEIGHBOURR))
 OBJPROC_3ASSIGNMENT_EQMS5ECREESTAJMMF3ZX1QNEIGHBOURR
 (= OBJPROC_3ATTRMYNUMBER (YESTERDAY OBJPROC_3ATTRMYNUMBER)) OBJPROC_3OPONE
 OBJPROC_3OPWINNER OBJPROC_3OPTWO
 OBJMONITOR_STDMONITOR_SM_TRANSITION_EQM57ECREESTAJMMF3ZX1Q_TRIGGER
 OBJMONITOR_STDMONITOR_SM_TRANSITION_EQM57UCREESTAJMMF3ZX1Q_TRIGGER
 OBJMONITOR_STDMONITOR_SM_STATESTATE_NO_WINNER_EXIT
 OBJMONITOR_STDMONITOR_SM_STATESTATE_NO_WINNER_ENTER
 $OBJMONITOR_STDMONITOR_SM_STATESTATE_NO_WINNER
 OBJMONITOR_STDMONITOR_SM_STATESTATE_WINNER_EXIT
 OBJMONITOR_STDMONITOR_SM_TRANSITION_EQM57ECREESTAJMMF3ZX1Q
 OBJMONITOR_STDMONITOR_SM_STATESTATE_WINNER_ENTER
 $OBJMONITOR_STDMONITOR_SM_STATESTATE_WINNER
 OBJMONITOR_STDMONITOR_SM_STATESTATE_ERROR_EXIT
 OBJMONITOR_STDMONITOR_SM_TRANSITION_EQM57UCREESTAJMMF3ZX1Q
 OBJMONITOR_STDMONITOR_SM_STATESTATE_ERROR_ENTER
 $OBJMONITOR_STDMONITOR_SM_STATESTATE_ERROR
 (= OBJPROC_1PARAMWIN_NR (YESTERDAY OBJPROC_0PARAMONE_NR))
 OBJPROC_1OPWINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_1PARAMONE_NR (YESTERDAY OBJPROC_0PARAMONE_NR))
 OBJPROC_1OPONETR_EQMS4-CREESTAJMMF3ZX1Q_CALL
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_0ATTRNEIGHBOURR (YESTERDAY OBJPROC_0PARAMONE_NR))
 (= OBJPROC_1PARAMTWO_NR (YESTERDAY OBJPROC_0PARAMONE_NR))
 OBJPROC_1OPTWOTR_EQMS5ECREESTAJMMF3ZX1Q_CALL
 (= OBJPROC_0PARAMONE_NR OBJPROC_0ATTRMAX)
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_1OPWINNERTR_EQMS6ECREESTAJMMF3ZX1Q_CALL
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_1PARAMWIN_NR (YESTERDAY OBJPROC_0PARAMWIN_NR))
 OBJPROC_1OPWINNERTR_EQMS6UCREESTAJMMF3ZX1Q_CALL
 (= OBJPROC_0PARAMWIN_NR OBJPROC_0ATTRMYNUMBER)
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_0ATTRMAX OBJPROC_0ATTRMYNUMBER)
 (= OBJPROC_1PARAMONE_NR OBJPROC_0ATTRMYNUMBER)
 OBJPROC_1OPONETR_EQMS4UCREESTAJMMF3ZX1Q_CALL
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TIMECONDITION
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_1PARAMTWO_NR (YESTERDAY OBJPROC_0PARAMTWO_NR))
 OBJPROC_1OPTWOTR_EQMS5OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_1PARAMONE_NR (YESTERDAY OBJPROC_0ATTRNEIGHBOURR))
 OBJPROC_1OPONETR_EQMS5UCREESTAJMMF3ZX1Q_CALL
 (= OBJPROC_0ATTRMAX (YESTERDAY OBJPROC_0ATTRNEIGHBOURR))
 (> OBJPROC_0ATTRNEIGHBOURR OBJPROC_0ATTRMAX)
 (> OBJPROC_0ATTRNEIGHBOURR OBJPROC_0PARAMTWO_NR)
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_0ATTRACTIVE 0) (<= OBJPROC_0ATTRNEIGHBOURR OBJPROC_0ATTRMAX)
 (<= OBJPROC_0ATTRNEIGHBOURR OBJPROC_0PARAMTWO_NR) (= OBJPROC_0ATTRACTIVE 1)
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS4-CREESTAJMMF3ZX1Q
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS5-CREESTAJMMF3ZX1Q
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_0_STDPROCESS_SM_STATEINIT_EXIT OBJPROC_0_STDPROCESS_SM_STATEINIT_ENTER
 $OBJPROC_0_STDPROCESS_SM_STATEINIT OBJPROC_0_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q
 OBJPROC_0_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_0_STDPROCESS_SM_STATEMAIN
 OBJPROC_0_STDPROCESS_SM_STATEWIN_EXIT
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q
 OBJPROC_0_STDPROCESS_SM_STATEWIN_ENTER $OBJPROC_0_STDPROCESS_SM_STATEWIN
 OBJPROC_0_STDPROCESS_SM_STATELOST_EXIT
 OBJPROC_0_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q
 OBJPROC_0_STDPROCESS_SM_STATELOST_ENTER $OBJPROC_0_STDPROCESS_SM_STATELOST
 (= OBJPROC_0ATTRACTIVE (YESTERDAY OBJPROC_0ATTRACTIVE))
 OBJPROC_0ASSIGNMENT_EQMS5-CREESTAJMMF3ZX1QACTIVE
 (= OBJPROC_0ATTRMAX (YESTERDAY OBJPROC_0ATTRMAX))
 OBJPROC_0ASSIGNMENT_EQMS4UCREESTAJMMF3ZX1QMAX
 OBJPROC_0ASSIGNMENT_EQMS5UCREESTAJMMF3ZX1QMAX
 (= OBJPROC_0ATTRNEIGHBOURR (YESTERDAY OBJPROC_0ATTRNEIGHBOURR))
 OBJPROC_0ASSIGNMENT_EQMS5ECREESTAJMMF3ZX1QNEIGHBOURR
 (= OBJPROC_0ATTRMYNUMBER (YESTERDAY OBJPROC_0ATTRMYNUMBER))
 OBJPROC_0OPONETR_EQMS4UCREESTAJMMF3ZX1Q_CALL
 OBJPROC_0OPONETR_EQMS5UCREESTAJMMF3ZX1Q_CALL
 OBJPROC_0OPONETR_EQMS4-CREESTAJMMF3ZX1Q_CALL OBJPROC_0OPONE
 OBJPROC_0OPWINNERTR_EQMS6ECREESTAJMMF3ZX1Q_CALL
 OBJPROC_0OPWINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_0OPWINNERTR_EQMS6UCREESTAJMMF3ZX1Q_CALL OBJPROC_0OPWINNER
 OBJPROC_0OPTWOTR_EQMS5ECREESTAJMMF3ZX1Q_CALL
 OBJPROC_0OPTWOTR_EQMS5OCREESTAJMMF3ZX1Q_CALL OBJPROC_0OPTWO
 (= OBJPROC_6PARAMWIN_NR (YESTERDAY OBJPROC_5PARAMONE_NR))
 OBJPROC_6OPWINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_6PARAMONE_NR (YESTERDAY OBJPROC_5PARAMONE_NR))
 OBJPROC_6OPONETR_EQMS4-CREESTAJMMF3ZX1Q_CALL
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_5ATTRNEIGHBOURR (YESTERDAY OBJPROC_5PARAMONE_NR))
 (= OBJPROC_6PARAMTWO_NR (YESTERDAY OBJPROC_5PARAMONE_NR))
 OBJPROC_6OPTWOTR_EQMS5ECREESTAJMMF3ZX1Q_CALL
 (= OBJPROC_5PARAMONE_NR OBJPROC_5ATTRMAX)
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_6OPWINNERTR_EQMS6ECREESTAJMMF3ZX1Q_CALL
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_6PARAMWIN_NR (YESTERDAY OBJPROC_5PARAMWIN_NR))
 OBJPROC_6OPWINNERTR_EQMS6UCREESTAJMMF3ZX1Q_CALL
 (= OBJPROC_5PARAMWIN_NR OBJPROC_5ATTRMYNUMBER)
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_5ATTRMAX OBJPROC_5ATTRMYNUMBER)
 (= OBJPROC_6PARAMONE_NR OBJPROC_5ATTRMYNUMBER)
 OBJPROC_6OPONETR_EQMS4UCREESTAJMMF3ZX1Q_CALL
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TIMECONDITION
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_6PARAMTWO_NR (YESTERDAY OBJPROC_5PARAMTWO_NR))
 OBJPROC_6OPTWOTR_EQMS5OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_6PARAMONE_NR (YESTERDAY OBJPROC_5ATTRNEIGHBOURR))
 OBJPROC_6OPONETR_EQMS5UCREESTAJMMF3ZX1Q_CALL
 (= OBJPROC_5ATTRMAX (YESTERDAY OBJPROC_5ATTRNEIGHBOURR))
 (> OBJPROC_5ATTRNEIGHBOURR OBJPROC_5ATTRMAX)
 (> OBJPROC_5ATTRNEIGHBOURR OBJPROC_5PARAMTWO_NR)
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_5ATTRACTIVE 0) (<= OBJPROC_5ATTRNEIGHBOURR OBJPROC_5ATTRMAX)
 (<= OBJPROC_5ATTRNEIGHBOURR OBJPROC_5PARAMTWO_NR) (= OBJPROC_5ATTRACTIVE 1)
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS4-CREESTAJMMF3ZX1Q
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS5-CREESTAJMMF3ZX1Q
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_5_STDPROCESS_SM_STATEINIT_EXIT OBJPROC_5_STDPROCESS_SM_STATEINIT_ENTER
 $OBJPROC_5_STDPROCESS_SM_STATEINIT OBJPROC_5_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q
 OBJPROC_5_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_5_STDPROCESS_SM_STATEMAIN
 OBJPROC_5_STDPROCESS_SM_STATEWIN_EXIT
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q
 OBJPROC_5_STDPROCESS_SM_STATEWIN_ENTER $OBJPROC_5_STDPROCESS_SM_STATEWIN
 OBJPROC_5_STDPROCESS_SM_STATELOST_EXIT
 OBJPROC_5_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q
 OBJPROC_5_STDPROCESS_SM_STATELOST_ENTER $OBJPROC_5_STDPROCESS_SM_STATELOST
 (= OBJPROC_5ATTRACTIVE (YESTERDAY OBJPROC_5ATTRACTIVE))
 OBJPROC_5ASSIGNMENT_EQMS5-CREESTAJMMF3ZX1QACTIVE
 (= OBJPROC_5ATTRMAX (YESTERDAY OBJPROC_5ATTRMAX))
 OBJPROC_5ASSIGNMENT_EQMS4UCREESTAJMMF3ZX1QMAX
 OBJPROC_5ASSIGNMENT_EQMS5UCREESTAJMMF3ZX1QMAX
 (= OBJPROC_5ATTRNEIGHBOURR (YESTERDAY OBJPROC_5ATTRNEIGHBOURR))
 OBJPROC_5ASSIGNMENT_EQMS5ECREESTAJMMF3ZX1QNEIGHBOURR
 (= OBJPROC_5ATTRMYNUMBER (YESTERDAY OBJPROC_5ATTRMYNUMBER))
 OBJPROC_5OPONETR_EQMS4UCREESTAJMMF3ZX1Q_CALL
 OBJPROC_5OPONETR_EQMS5UCREESTAJMMF3ZX1Q_CALL
 OBJPROC_5OPONETR_EQMS4-CREESTAJMMF3ZX1Q_CALL OBJPROC_5OPONE
 OBJPROC_5OPWINNERTR_EQMS6ECREESTAJMMF3ZX1Q_CALL
 OBJPROC_5OPWINNERTR_EQMS6UCREESTAJMMF3ZX1Q_CALL
 OBJPROC_5OPWINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL OBJPROC_5OPWINNER
 OBJPROC_5OPTWOTR_EQMS5ECREESTAJMMF3ZX1Q_CALL
 OBJPROC_5OPTWOTR_EQMS5OCREESTAJMMF3ZX1Q_CALL OBJPROC_5OPTWO
 (= OBJPROC_3PARAMWIN_NR (YESTERDAY OBJPROC_2PARAMONE_NR))
 OBJPROC_3OPWINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_3PARAMONE_NR (YESTERDAY OBJPROC_2PARAMONE_NR))
 OBJPROC_3OPONETR_EQMS4-CREESTAJMMF3ZX1Q_CALL
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS4_CREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_2ATTRNEIGHBOURR (YESTERDAY OBJPROC_2PARAMONE_NR))
 (= OBJPROC_3PARAMTWO_NR (YESTERDAY OBJPROC_2PARAMONE_NR))
 OBJPROC_3OPTWOTR_EQMS5ECREESTAJMMF3ZX1Q_CALL
 (= OBJPROC_2PARAMONE_NR OBJPROC_2ATTRMAX)
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_3OPWINNERTR_EQMS6ECREESTAJMMF3ZX1Q_CALL
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_3PARAMWIN_NR (YESTERDAY OBJPROC_2PARAMWIN_NR))
 OBJPROC_3OPWINNERTR_EQMS6UCREESTAJMMF3ZX1Q_CALL
 (= OBJPROC_2PARAMWIN_NR OBJPROC_2ATTRMYNUMBER)
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_2ATTRMAX OBJPROC_2ATTRMYNUMBER)
 (= OBJPROC_3PARAMONE_NR OBJPROC_2ATTRMYNUMBER)
 OBJPROC_3OPONETR_EQMS4UCREESTAJMMF3ZX1Q_CALL
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TIMECONDITION
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_3PARAMTWO_NR (YESTERDAY OBJPROC_2PARAMTWO_NR))
 OBJPROC_3OPTWOTR_EQMS5OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_3PARAMONE_NR (YESTERDAY OBJPROC_2ATTRNEIGHBOURR))
 OBJPROC_3OPONETR_EQMS5UCREESTAJMMF3ZX1Q_CALL
 (= OBJPROC_2ATTRMAX (YESTERDAY OBJPROC_2ATTRNEIGHBOURR))
 (> OBJPROC_2ATTRNEIGHBOURR OBJPROC_2ATTRMAX)
 (> OBJPROC_2ATTRNEIGHBOURR OBJPROC_2PARAMTWO_NR)
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q_TRIGGER
 (= OBJPROC_2ATTRACTIVE 0) (<= OBJPROC_2ATTRNEIGHBOURR OBJPROC_2ATTRMAX)
 (<= OBJPROC_2ATTRNEIGHBOURR OBJPROC_2PARAMTWO_NR) (= OBJPROC_2ATTRACTIVE 1)
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS6OCREESTAJMMF3ZX1Q
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS4-CREESTAJMMF3ZX1Q
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS5ECREESTAJMMF3ZX1Q
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS5OCREESTAJMMF3ZX1Q
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS5UCREESTAJMMF3ZX1Q
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS5-CREESTAJMMF3ZX1Q
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS5_CREESTAJMMF3ZX1Q_TRIGGER
 OBJPROC_2_STDPROCESS_SM_STATEINIT_EXIT OBJPROC_2_STDPROCESS_SM_STATEINIT_ENTER
 $OBJPROC_2_STDPROCESS_SM_STATEINIT OBJPROC_2_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS4UCREESTAJMMF3ZX1Q
 OBJPROC_2_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_2_STDPROCESS_SM_STATEMAIN
 OBJPROC_2_STDPROCESS_SM_STATEWIN_EXIT
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS6ECREESTAJMMF3ZX1Q
 OBJPROC_2_STDPROCESS_SM_STATEWIN_ENTER $OBJPROC_2_STDPROCESS_SM_STATEWIN
 OBJPROC_2_STDPROCESS_SM_STATELOST_EXIT
 OBJPROC_2_STDPROCESS_SM_TRANSITION_EQMS6UCREESTAJMMF3ZX1Q
 OBJPROC_2_STDPROCESS_SM_STATELOST_ENTER $OBJPROC_2_STDPROCESS_SM_STATELOST
 MADESYSTEMSTART (= OBJPROC_2ATTRACTIVE (YESTERDAY OBJPROC_2ATTRACTIVE))
 OBJPROC_2ASSIGNMENT_EQMS5-CREESTAJMMF3ZX1QACTIVE
 (= OBJPROC_2ATTRMAX (YESTERDAY OBJPROC_2ATTRMAX))
 OBJPROC_2ASSIGNMENT_EQMS4UCREESTAJMMF3ZX1QMAX
 OBJPROC_2ASSIGNMENT_EQMS5UCREESTAJMMF3ZX1QMAX
 (= OBJPROC_2ATTRNEIGHBOURR (YESTERDAY OBJPROC_2ATTRNEIGHBOURR))
 OBJPROC_2ASSIGNMENT_EQMS5ECREESTAJMMF3ZX1QNEIGHBOURR
 (= OBJPROC_2ATTRMYNUMBER (YESTERDAY OBJPROC_2ATTRMYNUMBER))
 OBJPROC_2OPONETR_EQMS5UCREESTAJMMF3ZX1Q_CALL
 OBJPROC_2OPONETR_EQMS4-CREESTAJMMF3ZX1Q_CALL
 OBJPROC_2OPONETR_EQMS4UCREESTAJMMF3ZX1Q_CALL OBJPROC_2OPONE
 OBJPROC_2OPWINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_2OPWINNERTR_EQMS6UCREESTAJMMF3ZX1Q_CALL
 OBJPROC_2OPWINNERTR_EQMS6ECREESTAJMMF3ZX1Q_CALL OBJPROC_2OPWINNER
 OBJPROC_2OPTWOTR_EQMS5OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_2OPTWOTR_EQMS5ECREESTAJMMF3ZX1Q_CALL OBJPROC_2OPTWO
 OBJPROC_1OPWE_HAVE_WINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_4OPWE_HAVE_WINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_6OPWE_HAVE_WINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_3OPWE_HAVE_WINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_0OPWE_HAVE_WINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_5OPWE_HAVE_WINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL
 OBJPROC_2OPWE_HAVE_WINNERTR_EQMS6OCREESTAJMMF3ZX1Q_CALL WE_HAVE_WINNER)

Used arithmetic terms: 
NIL

Used timed arithmetic terms: 
(OBJPROC_1ATTRACTIVE OBJPROC_1ATTRMAX OBJPROC_1ATTRNEIGHBOURR
 OBJPROC_1ATTRMYNUMBER OBJPROC_4ATTRACTIVE OBJPROC_4ATTRMAX
 OBJPROC_4ATTRNEIGHBOURR OBJPROC_4ATTRMYNUMBER OBJPROC_6ATTRACTIVE
 OBJPROC_6ATTRMAX OBJPROC_6ATTRNEIGHBOURR OBJPROC_6ATTRMYNUMBER
 OBJPROC_4PARAMWIN_NR OBJPROC_4PARAMTWO_NR OBJPROC_4PARAMONE_NR
 OBJPROC_3ATTRACTIVE OBJPROC_3ATTRMAX OBJPROC_3ATTRNEIGHBOURR
 OBJPROC_3ATTRMYNUMBER OBJPROC_0PARAMONE_NR OBJPROC_1PARAMWIN_NR
 OBJPROC_0PARAMWIN_NR OBJPROC_1PARAMTWO_NR OBJPROC_1PARAMONE_NR
 OBJPROC_0PARAMTWO_NR OBJPROC_0ATTRACTIVE OBJPROC_0ATTRMAX
 OBJPROC_0ATTRNEIGHBOURR OBJPROC_0ATTRMYNUMBER OBJPROC_5PARAMONE_NR
 OBJPROC_6PARAMWIN_NR OBJPROC_5PARAMWIN_NR OBJPROC_6PARAMTWO_NR
 OBJPROC_6PARAMONE_NR OBJPROC_5PARAMTWO_NR OBJPROC_5ATTRACTIVE OBJPROC_5ATTRMAX
 OBJPROC_5ATTRNEIGHBOURR OBJPROC_5ATTRMYNUMBER OBJPROC_2PARAMONE_NR
 OBJPROC_3PARAMWIN_NR OBJPROC_2PARAMWIN_NR OBJPROC_3PARAMTWO_NR
 OBJPROC_3PARAMONE_NR OBJPROC_2PARAMTWO_NR OBJPROC_2ATTRACTIVE OBJPROC_2ATTRMAX
 OBJPROC_2ATTRNEIGHBOURR OBJPROC_2ATTRMYNUMBER)

Graph dependency over terms 
(((YESTERDAY OBJPROC_2ATTRACTIVE) OBJPROC_2ATTRACTIVE
  (YESTERDAY OBJPROC_5ATTRACTIVE) 1 (YESTERDAY OBJPROC_0ATTRACTIVE) 1
  (YESTERDAY OBJPROC_3ATTRACTIVE) 1 (YESTERDAY OBJPROC_6ATTRACTIVE) 1
  (YESTERDAY OBJPROC_4ATTRACTIVE) 1 OBJPROC_2ATTRACTIVE OBJPROC_5ATTRACTIVE
  OBJPROC_0ATTRACTIVE OBJPROC_3ATTRACTIVE OBJPROC_6ATTRACTIVE
  OBJPROC_4ATTRACTIVE (YESTERDAY OBJPROC_1ATTRACTIVE) 1 0 OBJPROC_1ATTRACTIVE)
 ((YESTERDAY OBJPROC_2ATTRMYNUMBER) (YESTERDAY OBJPROC_2ATTRNEIGHBOURR)
  (YESTERDAY OBJPROC_2ATTRMAX) OBJPROC_2ATTRNEIGHBOURR OBJPROC_2ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_2ATTRNEIGHBOURR) OBJPROC_2ATTRMYNUMBER
  OBJPROC_2ATTRNEIGHBOURR OBJPROC_2ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_1PARAMTWO_NR) (YESTERDAY OBJPROC_2ATTRNEIGHBOURR)
  OBJPROC_2ATTRMYNUMBER (YESTERDAY OBJPROC_2PARAMTWO_NR) OBJPROC_2ATTRMYNUMBER
  (YESTERDAY OBJPROC_1PARAMWIN_NR) OBJPROC_3PARAMTWO_NR OBJPROC_2ATTRNEIGHBOURR
  OBJPROC_3PARAMONE_NR (YESTERDAY OBJPROC_2PARAMWIN_NR)
  (YESTERDAY OBJPROC_2PARAMONE_NR) OBJPROC_2ATTRMAX
  (YESTERDAY OBJPROC_5ATTRMYNUMBER) OBJPROC_2ATTRMYNUMBER
  (YESTERDAY OBJPROC_5ATTRNEIGHBOURR) (YESTERDAY OBJPROC_5ATTRMAX)
  OBJPROC_5ATTRNEIGHBOURR OBJPROC_5ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_5ATTRNEIGHBOURR) OBJPROC_5ATTRMYNUMBER
  OBJPROC_5ATTRNEIGHBOURR OBJPROC_5ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_4PARAMTWO_NR) (YESTERDAY OBJPROC_5ATTRNEIGHBOURR)
  OBJPROC_5ATTRMYNUMBER (YESTERDAY OBJPROC_5PARAMTWO_NR) OBJPROC_5ATTRMYNUMBER
  (YESTERDAY OBJPROC_4PARAMWIN_NR) OBJPROC_6PARAMTWO_NR OBJPROC_5ATTRNEIGHBOURR
  OBJPROC_6PARAMONE_NR (YESTERDAY OBJPROC_5PARAMWIN_NR)
  (YESTERDAY OBJPROC_5PARAMONE_NR) OBJPROC_5ATTRMAX
  (YESTERDAY OBJPROC_0ATTRMYNUMBER) OBJPROC_2ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER
  (YESTERDAY OBJPROC_0ATTRNEIGHBOURR) (YESTERDAY OBJPROC_0ATTRMAX)
  OBJPROC_0ATTRNEIGHBOURR OBJPROC_0ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_0ATTRNEIGHBOURR) OBJPROC_0ATTRMYNUMBER
  OBJPROC_0ATTRNEIGHBOURR OBJPROC_0ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_6PARAMTWO_NR) (YESTERDAY OBJPROC_0ATTRNEIGHBOURR)
  OBJPROC_0ATTRMYNUMBER (YESTERDAY OBJPROC_0PARAMTWO_NR) OBJPROC_0ATTRMYNUMBER
  (YESTERDAY OBJPROC_6PARAMWIN_NR) OBJPROC_1PARAMTWO_NR OBJPROC_0ATTRNEIGHBOURR
  OBJPROC_1PARAMONE_NR (YESTERDAY OBJPROC_0PARAMWIN_NR)
  (YESTERDAY OBJPROC_0PARAMONE_NR) OBJPROC_0ATTRMAX
  (YESTERDAY OBJPROC_3ATTRMYNUMBER) OBJPROC_3PARAMWIN_NR OBJPROC_0ATTRMYNUMBER
  OBJPROC_2ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER (YESTERDAY OBJPROC_3ATTRMAX)
  (YESTERDAY OBJPROC_3ATTRNEIGHBOURR) OBJPROC_3ATTRMYNUMBER
  OBJPROC_3PARAMONE_NR (YESTERDAY OBJPROC_3ATTRNEIGHBOURR) OBJPROC_3PARAMTWO_NR
  OBJPROC_3ATTRMAX OBJPROC_3PARAMTWO_NR OBJPROC_3ATTRMAX
  (YESTERDAY OBJPROC_3ATTRNEIGHBOURR) OBJPROC_3ATTRMYNUMBER
  (YESTERDAY OBJPROC_3PARAMTWO_NR) OBJPROC_4PARAMTWO_NR OBJPROC_3ATTRNEIGHBOURR
  OBJPROC_4PARAMONE_NR (YESTERDAY OBJPROC_3PARAMWIN_NR)
  (YESTERDAY OBJPROC_3PARAMONE_NR) OBJPROC_0PARAMONE_NR OBJPROC_0PARAMTWO_NR
  OBJPROC_0PARAMONE_NR OBJPROC_0PARAMWIN_NR (YESTERDAY OBJPROC_6ATTRNEIGHBOURR)
  OBJPROC_6PARAMTWO_NR OBJPROC_6PARAMTWO_NR (YESTERDAY OBJPROC_6PARAMONE_NR)
  (YESTERDAY OBJPROC_6ATTRMAX) OBJPROC_6ATTRNEIGHBOURR OBJPROC_6ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_6ATTRNEIGHBOURR) OBJPROC_6PARAMONE_NR
  (YESTERDAY OBJPROC_6ATTRMYNUMBER) OBJPROC_0PARAMONE_NR OBJPROC_6ATTRMAX
  OBJPROC_6PARAMWIN_NR OBJPROC_0ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER
  OBJPROC_3ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER OBJPROC_5PARAMONE_NR
  OBJPROC_5PARAMTWO_NR OBJPROC_5PARAMONE_NR OBJPROC_5PARAMWIN_NR
  (YESTERDAY OBJPROC_4ATTRNEIGHBOURR) OBJPROC_4PARAMTWO_NR OBJPROC_4PARAMTWO_NR
  (YESTERDAY OBJPROC_4PARAMONE_NR) (YESTERDAY OBJPROC_4ATTRMAX)
  OBJPROC_4ATTRNEIGHBOURR OBJPROC_4ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_4ATTRNEIGHBOURR) OBJPROC_4PARAMONE_NR
  (YESTERDAY OBJPROC_4ATTRMYNUMBER) OBJPROC_5PARAMONE_NR OBJPROC_4ATTRMAX
  OBJPROC_4PARAMWIN_NR OBJPROC_0ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER
  OBJPROC_3ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER
  (YESTERDAY OBJPROC_1ATTRMYNUMBER) OBJPROC_2PARAMONE_NR OBJPROC_1PARAMWIN_NR
  OBJPROC_0ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER
  OBJPROC_4ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER
  OBJPROC_2PARAMONE_NR (YESTERDAY OBJPROC_1ATTRMAX)
  (YESTERDAY OBJPROC_1ATTRNEIGHBOURR) OBJPROC_1ATTRMYNUMBER
  OBJPROC_1PARAMONE_NR (YESTERDAY OBJPROC_1ATTRNEIGHBOURR) OBJPROC_1PARAMTWO_NR
  OBJPROC_1ATTRMAX OBJPROC_1PARAMTWO_NR OBJPROC_1ATTRMAX OBJPROC_2PARAMTWO_NR
  OBJPROC_1ATTRNEIGHBOURR OBJPROC_2PARAMONE_NR OBJPROC_2PARAMWIN_NR
  (YESTERDAY OBJPROC_1PARAMONE_NR)))

Related variables 
((OBJPROC_2ATTRACTIVE OBJPROC_5ATTRACTIVE OBJPROC_0ATTRACTIVE
  OBJPROC_3ATTRACTIVE OBJPROC_6ATTRACTIVE OBJPROC_4ATTRACTIVE 1 0
  OBJPROC_1ATTRACTIVE)
 (OBJPROC_2ATTRNEIGHBOURR OBJPROC_2ATTRMAX OBJPROC_5ATTRNEIGHBOURR
  OBJPROC_5ATTRMAX OBJPROC_0ATTRNEIGHBOURR OBJPROC_0ATTRMAX OBJPROC_3ATTRMAX
  OBJPROC_3PARAMTWO_NR OBJPROC_3ATTRNEIGHBOURR OBJPROC_3PARAMWIN_NR
  OBJPROC_3PARAMONE_NR OBJPROC_0PARAMTWO_NR OBJPROC_0PARAMWIN_NR
  OBJPROC_6PARAMTWO_NR OBJPROC_6ATTRNEIGHBOURR OBJPROC_6PARAMONE_NR
  OBJPROC_0PARAMONE_NR OBJPROC_6ATTRMAX OBJPROC_6PARAMWIN_NR
  OBJPROC_5PARAMTWO_NR OBJPROC_5PARAMWIN_NR OBJPROC_4PARAMTWO_NR
  OBJPROC_4ATTRNEIGHBOURR OBJPROC_4PARAMONE_NR OBJPROC_5PARAMONE_NR
  OBJPROC_4ATTRMAX OBJPROC_4PARAMWIN_NR OBJPROC_1PARAMWIN_NR
  OBJPROC_0ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER
  OBJPROC_4ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER
  OBJPROC_1ATTRMYNUMBER OBJPROC_1PARAMTWO_NR OBJPROC_1ATTRMAX
  OBJPROC_2PARAMTWO_NR OBJPROC_1ATTRNEIGHBOURR OBJPROC_2PARAMONE_NR
  OBJPROC_2PARAMWIN_NR OBJPROC_1PARAMONE_NR))

Time bound: 50

Number of Boolean variables: 
400
define FO future formulae Xt
define FO future formulae Yt
define for interpreted relations: <,>,=,<=,>= 
define FO terms for +,-,*,/,mod 
define loop constraints

done processing formula
define LTL future formulae X, U, R
define LTL future formulae X, U, R
gen-past2...
gen-past2...
define LTL boolean connectives
define LTL boolean connectives

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  9.797 seconds of real time
  0.000000 seconds of total run time (0.000000 user, 0.000000 system)
  0.00% CPU
  33,309,092,564 processor cycles
  0 bytes consed
  
---SAT---
------ time 0 ------
Evaluation took:
  11.607 seconds of real time
  1.812000 seconds of total run time (1.656000 user, 0.156000 system)
  [ Run times consist of 0.176 seconds GC time, and 1.636 seconds non-GC time. ]
  15.61% CPU
  39,465,834,315 processor cycles
  6,785,783,600 bytes consed
  
  before it was aborted by a non-local transfer of control.
  
