This is SBCL 1.2.4.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
IPC-terms: ((YESTERDAY OBJPROC_1PARAMTWO_NR) (YESTERDAY OBJPROC_1PARAMWIN_NR)
            (YESTERDAY OBJPROC_1PARAMONE_NR) OBJPROC_1ATTRMAX
            (YESTERDAY OBJPROC_1ATTRMAX) OBJPROC_1ATTRNEIGHBOURR
            (YESTERDAY OBJPROC_1ATTRNEIGHBOURR) OBJPROC_1ATTRMYNUMBER
            (YESTERDAY OBJPROC_1ATTRMYNUMBER) OBJPROC_1ATTRACTIVE
            (YESTERDAY OBJPROC_1ATTRACTIVE) (YESTERDAY OBJPROC_7PARAMTWO_NR)
            (YESTERDAY OBJPROC_7PARAMWIN_NR) (YESTERDAY OBJPROC_7PARAMONE_NR)
            OBJPROC_7ATTRMAX (YESTERDAY OBJPROC_7ATTRMAX)
            OBJPROC_7ATTRNEIGHBOURR (YESTERDAY OBJPROC_7ATTRNEIGHBOURR)
            OBJPROC_7ATTRMYNUMBER (YESTERDAY OBJPROC_7ATTRMYNUMBER)
            OBJPROC_7ATTRACTIVE (YESTERDAY OBJPROC_7ATTRACTIVE)
            (YESTERDAY OBJPROC_4PARAMTWO_NR) (YESTERDAY OBJPROC_4PARAMWIN_NR)
            (YESTERDAY OBJPROC_4PARAMONE_NR) OBJPROC_4ATTRMAX
            (YESTERDAY OBJPROC_4ATTRMAX) OBJPROC_4ATTRNEIGHBOURR
            (YESTERDAY OBJPROC_4ATTRNEIGHBOURR) OBJPROC_4ATTRMYNUMBER
            (YESTERDAY OBJPROC_4ATTRMYNUMBER) OBJPROC_4ATTRACTIVE
            (YESTERDAY OBJPROC_4ATTRACTIVE) (YESTERDAY OBJPROC_8PARAMTWO_NR)
            (YESTERDAY OBJPROC_8PARAMWIN_NR) OBJPROC_8PARAMWIN_NR
            OBJPROC_8PARAMTWO_NR (YESTERDAY OBJPROC_8PARAMONE_NR)
            OBJPROC_8PARAMONE_NR OBJPROC_8ATTRMAX (YESTERDAY OBJPROC_8ATTRMAX)
            OBJPROC_8ATTRNEIGHBOURR (YESTERDAY OBJPROC_8ATTRNEIGHBOURR)
            OBJPROC_8ATTRMYNUMBER (YESTERDAY OBJPROC_8ATTRMYNUMBER)
            OBJPROC_8ATTRACTIVE (YESTERDAY OBJPROC_8ATTRACTIVE)
            (YESTERDAY OBJPROC_2PARAMTWO_NR) (YESTERDAY OBJPROC_2PARAMWIN_NR)
            OBJPROC_2PARAMWIN_NR OBJPROC_2PARAMTWO_NR
            (YESTERDAY OBJPROC_2PARAMONE_NR) OBJPROC_2PARAMONE_NR
            OBJPROC_2ATTRMAX (YESTERDAY OBJPROC_2ATTRMAX)
            OBJPROC_2ATTRNEIGHBOURR (YESTERDAY OBJPROC_2ATTRNEIGHBOURR)
            OBJPROC_2ATTRMYNUMBER (YESTERDAY OBJPROC_2ATTRMYNUMBER)
            OBJPROC_2ATTRACTIVE (YESTERDAY OBJPROC_2ATTRACTIVE)
            (YESTERDAY OBJPROC_3PARAMTWO_NR) OBJPROC_4PARAMWIN_NR
            (YESTERDAY OBJPROC_3PARAMWIN_NR) OBJPROC_3PARAMWIN_NR
            OBJPROC_4PARAMONE_NR OBJPROC_3PARAMTWO_NR OBJPROC_4PARAMTWO_NR
            (YESTERDAY OBJPROC_3PARAMONE_NR) OBJPROC_3PARAMONE_NR
            OBJPROC_3ATTRMAX (YESTERDAY OBJPROC_3ATTRMAX)
            OBJPROC_3ATTRNEIGHBOURR (YESTERDAY OBJPROC_3ATTRNEIGHBOURR)
            OBJPROC_3ATTRMYNUMBER (YESTERDAY OBJPROC_3ATTRMYNUMBER)
            OBJPROC_3ATTRACTIVE (YESTERDAY OBJPROC_3ATTRACTIVE)
            (YESTERDAY OBJPROC_0PARAMTWO_NR) OBJPROC_1PARAMWIN_NR
            (YESTERDAY OBJPROC_0PARAMWIN_NR) OBJPROC_1PARAMONE_NR
            OBJPROC_1PARAMTWO_NR (YESTERDAY OBJPROC_0PARAMONE_NR)
            OBJPROC_0ATTRMAX (YESTERDAY OBJPROC_0ATTRMAX)
            OBJPROC_0ATTRNEIGHBOURR (YESTERDAY OBJPROC_0ATTRNEIGHBOURR)
            OBJPROC_0ATTRMYNUMBER (YESTERDAY OBJPROC_0ATTRMYNUMBER)
            OBJPROC_0ATTRACTIVE (YESTERDAY OBJPROC_0ATTRACTIVE)
            (YESTERDAY OBJPROC_5PARAMTWO_NR) (YESTERDAY OBJPROC_5PARAMWIN_NR)
            OBJPROC_5PARAMWIN_NR OBJPROC_5PARAMTWO_NR
            (YESTERDAY OBJPROC_5PARAMONE_NR) OBJPROC_5PARAMONE_NR
            OBJPROC_5ATTRMAX (YESTERDAY OBJPROC_5ATTRMAX)
            OBJPROC_5ATTRNEIGHBOURR (YESTERDAY OBJPROC_5ATTRNEIGHBOURR)
            OBJPROC_5ATTRMYNUMBER (YESTERDAY OBJPROC_5ATTRMYNUMBER)
            OBJPROC_5ATTRACTIVE (YESTERDAY OBJPROC_5ATTRACTIVE)
            (YESTERDAY OBJPROC_6PARAMTWO_NR) OBJPROC_7PARAMWIN_NR
            (YESTERDAY OBJPROC_6PARAMWIN_NR) OBJPROC_6PARAMWIN_NR
            OBJPROC_7PARAMONE_NR OBJPROC_6PARAMTWO_NR OBJPROC_7PARAMTWO_NR
            (YESTERDAY OBJPROC_6PARAMONE_NR) OBJPROC_6PARAMONE_NR
            OBJPROC_6ATTRMAX (YESTERDAY OBJPROC_6ATTRMAX)
            OBJPROC_6ATTRNEIGHBOURR (YESTERDAY OBJPROC_6ATTRNEIGHBOURR)
            OBJPROC_6ATTRMYNUMBER (YESTERDAY OBJPROC_6ATTRMYNUMBER)
            OBJPROC_6ATTRACTIVE (YESTERDAY OBJPROC_6ATTRACTIVE)
            (YESTERDAY OBJPROC_9PARAMTWO_NR) OBJPROC_0PARAMWIN_NR
            (YESTERDAY OBJPROC_9PARAMWIN_NR) OBJPROC_9PARAMWIN_NR 0
            OBJPROC_0PARAMONE_NR OBJPROC_9PARAMTWO_NR OBJPROC_0PARAMTWO_NR
            (YESTERDAY OBJPROC_9PARAMONE_NR) OBJPROC_9PARAMONE_NR 1
            OBJPROC_9ATTRMAX (YESTERDAY OBJPROC_9ATTRMAX)
            OBJPROC_9ATTRNEIGHBOURR (YESTERDAY OBJPROC_9ATTRNEIGHBOURR)
            OBJPROC_9ATTRMYNUMBER (YESTERDAY OBJPROC_9ATTRMYNUMBER)
            OBJPROC_9ATTRACTIVE (YESTERDAY OBJPROC_9ATTRACTIVE))
IPC-constraints: ((= OBJPROC_8ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
                  (= OBJPROC_7ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
                  (= OBJPROC_7ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
                  (= OBJPROC_6ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
                  (= OBJPROC_6ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
                  (= OBJPROC_6ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
                  (= OBJPROC_5ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
                  (= OBJPROC_5ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
                  (= OBJPROC_5ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
                  (= OBJPROC_5ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_4ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
                  (= OBJPROC_4ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
                  (= OBJPROC_4ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
                  (= OBJPROC_4ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_4ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_3ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
                  (= OBJPROC_3ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
                  (= OBJPROC_3ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
                  (= OBJPROC_3ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_3ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_3ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_2ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
                  (= OBJPROC_2ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
                  (= OBJPROC_2ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
                  (= OBJPROC_2ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_2ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_2ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_2ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER)
                  (= OBJPROC_1ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER)
                  (= OBJPROC_0ATTRMYNUMBER OBJPROC_1ATTRMYNUMBER)
                  (= OBJPROC_2PARAMWIN_NR (YESTERDAY OBJPROC_1PARAMONE_NR))
                  (<= OBJPROC_1ATTRNEIGHBOURR OBJPROC_1ATTRMAX)
                  (<= OBJPROC_1ATTRNEIGHBOURR OBJPROC_1PARAMTWO_NR)
                  (= OBJPROC_2PARAMTWO_NR (YESTERDAY OBJPROC_1PARAMTWO_NR))
                  (= OBJPROC_2PARAMWIN_NR (YESTERDAY OBJPROC_1PARAMWIN_NR))
                  (= OBJPROC_1PARAMWIN_NR OBJPROC_1ATTRMYNUMBER)
                  (= OBJPROC_2PARAMONE_NR (YESTERDAY OBJPROC_1PARAMONE_NR))
                  (= OBJPROC_1ATTRACTIVE 0)
                  (= OBJPROC_1ATTRMAX OBJPROC_1ATTRMYNUMBER)
                  (= OBJPROC_2PARAMONE_NR OBJPROC_1ATTRMYNUMBER)
                  (= OBJPROC_2PARAMONE_NR (YESTERDAY OBJPROC_1ATTRNEIGHBOURR))
                  (= OBJPROC_1ATTRMAX (YESTERDAY OBJPROC_1ATTRNEIGHBOURR))
                  (> OBJPROC_1ATTRNEIGHBOURR OBJPROC_1ATTRMAX)
                  (> OBJPROC_1ATTRNEIGHBOURR OBJPROC_1PARAMTWO_NR)
                  (= OBJPROC_1ATTRNEIGHBOURR (YESTERDAY OBJPROC_1PARAMONE_NR))
                  (= OBJPROC_2PARAMTWO_NR (YESTERDAY OBJPROC_1PARAMONE_NR))
                  (= OBJPROC_1PARAMONE_NR OBJPROC_1ATTRMAX)
                  (= OBJPROC_1ATTRACTIVE 1)
                  (= OBJPROC_1ATTRMAX (YESTERDAY OBJPROC_1ATTRMAX))
                  (= OBJPROC_1ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_1ATTRNEIGHBOURR))
                  (= OBJPROC_1ATTRMYNUMBER (YESTERDAY OBJPROC_1ATTRMYNUMBER))
                  (= OBJPROC_1ATTRACTIVE (YESTERDAY OBJPROC_1ATTRACTIVE))
                  (= OBJPROC_8PARAMWIN_NR (YESTERDAY OBJPROC_7PARAMONE_NR))
                  (<= OBJPROC_7ATTRNEIGHBOURR OBJPROC_7ATTRMAX)
                  (<= OBJPROC_7ATTRNEIGHBOURR OBJPROC_7PARAMTWO_NR)
                  (= OBJPROC_8PARAMTWO_NR (YESTERDAY OBJPROC_7PARAMTWO_NR))
                  (= OBJPROC_8PARAMWIN_NR (YESTERDAY OBJPROC_7PARAMWIN_NR))
                  (= OBJPROC_7PARAMWIN_NR OBJPROC_7ATTRMYNUMBER)
                  (= OBJPROC_8PARAMONE_NR (YESTERDAY OBJPROC_7PARAMONE_NR))
                  (= OBJPROC_7ATTRACTIVE 0)
                  (= OBJPROC_7ATTRMAX OBJPROC_7ATTRMYNUMBER)
                  (= OBJPROC_8PARAMONE_NR OBJPROC_7ATTRMYNUMBER)
                  (= OBJPROC_8PARAMONE_NR (YESTERDAY OBJPROC_7ATTRNEIGHBOURR))
                  (= OBJPROC_7ATTRMAX (YESTERDAY OBJPROC_7ATTRNEIGHBOURR))
                  (> OBJPROC_7ATTRNEIGHBOURR OBJPROC_7ATTRMAX)
                  (> OBJPROC_7ATTRNEIGHBOURR OBJPROC_7PARAMTWO_NR)
                  (= OBJPROC_7ATTRNEIGHBOURR (YESTERDAY OBJPROC_7PARAMONE_NR))
                  (= OBJPROC_8PARAMTWO_NR (YESTERDAY OBJPROC_7PARAMONE_NR))
                  (= OBJPROC_7PARAMONE_NR OBJPROC_7ATTRMAX)
                  (= OBJPROC_7ATTRACTIVE 1)
                  (= OBJPROC_7ATTRMAX (YESTERDAY OBJPROC_7ATTRMAX))
                  (= OBJPROC_7ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_7ATTRNEIGHBOURR))
                  (= OBJPROC_7ATTRMYNUMBER (YESTERDAY OBJPROC_7ATTRMYNUMBER))
                  (= OBJPROC_7ATTRACTIVE (YESTERDAY OBJPROC_7ATTRACTIVE))
                  (= OBJPROC_5PARAMWIN_NR (YESTERDAY OBJPROC_4PARAMONE_NR))
                  (<= OBJPROC_4ATTRNEIGHBOURR OBJPROC_4ATTRMAX)
                  (<= OBJPROC_4ATTRNEIGHBOURR OBJPROC_4PARAMTWO_NR)
                  (= OBJPROC_5PARAMTWO_NR (YESTERDAY OBJPROC_4PARAMTWO_NR))
                  (= OBJPROC_5PARAMWIN_NR (YESTERDAY OBJPROC_4PARAMWIN_NR))
                  (= OBJPROC_4PARAMWIN_NR OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_5PARAMONE_NR (YESTERDAY OBJPROC_4PARAMONE_NR))
                  (= OBJPROC_4ATTRACTIVE 0)
                  (= OBJPROC_4ATTRMAX OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_5PARAMONE_NR OBJPROC_4ATTRMYNUMBER)
                  (= OBJPROC_5PARAMONE_NR (YESTERDAY OBJPROC_4ATTRNEIGHBOURR))
                  (= OBJPROC_4ATTRMAX (YESTERDAY OBJPROC_4ATTRNEIGHBOURR))
                  (> OBJPROC_4ATTRNEIGHBOURR OBJPROC_4ATTRMAX)
                  (> OBJPROC_4ATTRNEIGHBOURR OBJPROC_4PARAMTWO_NR)
                  (= OBJPROC_4ATTRNEIGHBOURR (YESTERDAY OBJPROC_4PARAMONE_NR))
                  (= OBJPROC_5PARAMTWO_NR (YESTERDAY OBJPROC_4PARAMONE_NR))
                  (= OBJPROC_4PARAMONE_NR OBJPROC_4ATTRMAX)
                  (= OBJPROC_4ATTRACTIVE 1)
                  (= OBJPROC_4ATTRMAX (YESTERDAY OBJPROC_4ATTRMAX))
                  (= OBJPROC_4ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_4ATTRNEIGHBOURR))
                  (= OBJPROC_4ATTRMYNUMBER (YESTERDAY OBJPROC_4ATTRMYNUMBER))
                  (= OBJPROC_4ATTRACTIVE (YESTERDAY OBJPROC_4ATTRACTIVE))
                  (= OBJPROC_9PARAMWIN_NR (YESTERDAY OBJPROC_8PARAMONE_NR))
                  (<= OBJPROC_8ATTRNEIGHBOURR OBJPROC_8ATTRMAX)
                  (<= OBJPROC_8ATTRNEIGHBOURR OBJPROC_8PARAMTWO_NR)
                  (= OBJPROC_9PARAMTWO_NR (YESTERDAY OBJPROC_8PARAMTWO_NR))
                  (= OBJPROC_9PARAMWIN_NR (YESTERDAY OBJPROC_8PARAMWIN_NR))
                  (= OBJPROC_8PARAMWIN_NR OBJPROC_8ATTRMYNUMBER)
                  (= OBJPROC_9PARAMONE_NR (YESTERDAY OBJPROC_8PARAMONE_NR))
                  (= OBJPROC_8ATTRACTIVE 0)
                  (= OBJPROC_8ATTRMAX OBJPROC_8ATTRMYNUMBER)
                  (= OBJPROC_9PARAMONE_NR OBJPROC_8ATTRMYNUMBER)
                  (= OBJPROC_9PARAMONE_NR (YESTERDAY OBJPROC_8ATTRNEIGHBOURR))
                  (= OBJPROC_8ATTRMAX (YESTERDAY OBJPROC_8ATTRNEIGHBOURR))
                  (> OBJPROC_8ATTRNEIGHBOURR OBJPROC_8ATTRMAX)
                  (> OBJPROC_8ATTRNEIGHBOURR OBJPROC_8PARAMTWO_NR)
                  (= OBJPROC_8ATTRNEIGHBOURR (YESTERDAY OBJPROC_8PARAMONE_NR))
                  (= OBJPROC_9PARAMTWO_NR (YESTERDAY OBJPROC_8PARAMONE_NR))
                  (= OBJPROC_8PARAMONE_NR OBJPROC_8ATTRMAX)
                  (= OBJPROC_8ATTRACTIVE 1)
                  (= OBJPROC_8ATTRMAX (YESTERDAY OBJPROC_8ATTRMAX))
                  (= OBJPROC_8ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_8ATTRNEIGHBOURR))
                  (= OBJPROC_8ATTRMYNUMBER (YESTERDAY OBJPROC_8ATTRMYNUMBER))
                  (= OBJPROC_8ATTRACTIVE (YESTERDAY OBJPROC_8ATTRACTIVE))
                  (= OBJPROC_3PARAMWIN_NR (YESTERDAY OBJPROC_2PARAMONE_NR))
                  (<= OBJPROC_2ATTRNEIGHBOURR OBJPROC_2ATTRMAX)
                  (<= OBJPROC_2ATTRNEIGHBOURR OBJPROC_2PARAMTWO_NR)
                  (= OBJPROC_3PARAMTWO_NR (YESTERDAY OBJPROC_2PARAMTWO_NR))
                  (= OBJPROC_3PARAMWIN_NR (YESTERDAY OBJPROC_2PARAMWIN_NR))
                  (= OBJPROC_2PARAMWIN_NR OBJPROC_2ATTRMYNUMBER)
                  (= OBJPROC_3PARAMONE_NR (YESTERDAY OBJPROC_2PARAMONE_NR))
                  (= OBJPROC_2ATTRACTIVE 0)
                  (= OBJPROC_2ATTRMAX OBJPROC_2ATTRMYNUMBER)
                  (= OBJPROC_3PARAMONE_NR OBJPROC_2ATTRMYNUMBER)
                  (= OBJPROC_3PARAMONE_NR (YESTERDAY OBJPROC_2ATTRNEIGHBOURR))
                  (= OBJPROC_2ATTRMAX (YESTERDAY OBJPROC_2ATTRNEIGHBOURR))
                  (> OBJPROC_2ATTRNEIGHBOURR OBJPROC_2ATTRMAX)
                  (> OBJPROC_2ATTRNEIGHBOURR OBJPROC_2PARAMTWO_NR)
                  (= OBJPROC_2ATTRNEIGHBOURR (YESTERDAY OBJPROC_2PARAMONE_NR))
                  (= OBJPROC_3PARAMTWO_NR (YESTERDAY OBJPROC_2PARAMONE_NR))
                  (= OBJPROC_2PARAMONE_NR OBJPROC_2ATTRMAX)
                  (= OBJPROC_2ATTRACTIVE 1)
                  (= OBJPROC_2ATTRMAX (YESTERDAY OBJPROC_2ATTRMAX))
                  (= OBJPROC_2ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_2ATTRNEIGHBOURR))
                  (= OBJPROC_2ATTRMYNUMBER (YESTERDAY OBJPROC_2ATTRMYNUMBER))
                  (= OBJPROC_2ATTRACTIVE (YESTERDAY OBJPROC_2ATTRACTIVE))
                  (= OBJPROC_4PARAMWIN_NR (YESTERDAY OBJPROC_3PARAMONE_NR))
                  (<= OBJPROC_3ATTRNEIGHBOURR OBJPROC_3ATTRMAX)
                  (<= OBJPROC_3ATTRNEIGHBOURR OBJPROC_3PARAMTWO_NR)
                  (= OBJPROC_4PARAMTWO_NR (YESTERDAY OBJPROC_3PARAMTWO_NR))
                  (= OBJPROC_4PARAMWIN_NR (YESTERDAY OBJPROC_3PARAMWIN_NR))
                  (= OBJPROC_3PARAMWIN_NR OBJPROC_3ATTRMYNUMBER)
                  (= OBJPROC_4PARAMONE_NR (YESTERDAY OBJPROC_3PARAMONE_NR))
                  (= OBJPROC_3ATTRACTIVE 0)
                  (= OBJPROC_3ATTRMAX OBJPROC_3ATTRMYNUMBER)
                  (= OBJPROC_4PARAMONE_NR OBJPROC_3ATTRMYNUMBER)
                  (= OBJPROC_4PARAMONE_NR (YESTERDAY OBJPROC_3ATTRNEIGHBOURR))
                  (= OBJPROC_3ATTRMAX (YESTERDAY OBJPROC_3ATTRNEIGHBOURR))
                  (> OBJPROC_3ATTRNEIGHBOURR OBJPROC_3ATTRMAX)
                  (> OBJPROC_3ATTRNEIGHBOURR OBJPROC_3PARAMTWO_NR)
                  (= OBJPROC_3ATTRNEIGHBOURR (YESTERDAY OBJPROC_3PARAMONE_NR))
                  (= OBJPROC_4PARAMTWO_NR (YESTERDAY OBJPROC_3PARAMONE_NR))
                  (= OBJPROC_3PARAMONE_NR OBJPROC_3ATTRMAX)
                  (= OBJPROC_3ATTRACTIVE 1)
                  (= OBJPROC_3ATTRMAX (YESTERDAY OBJPROC_3ATTRMAX))
                  (= OBJPROC_3ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_3ATTRNEIGHBOURR))
                  (= OBJPROC_3ATTRMYNUMBER (YESTERDAY OBJPROC_3ATTRMYNUMBER))
                  (= OBJPROC_3ATTRACTIVE (YESTERDAY OBJPROC_3ATTRACTIVE))
                  (= OBJPROC_1PARAMWIN_NR (YESTERDAY OBJPROC_0PARAMONE_NR))
                  (<= OBJPROC_0ATTRNEIGHBOURR OBJPROC_0ATTRMAX)
                  (<= OBJPROC_0ATTRNEIGHBOURR OBJPROC_0PARAMTWO_NR)
                  (= OBJPROC_1PARAMTWO_NR (YESTERDAY OBJPROC_0PARAMTWO_NR))
                  (= OBJPROC_1PARAMWIN_NR (YESTERDAY OBJPROC_0PARAMWIN_NR))
                  (= OBJPROC_0PARAMWIN_NR OBJPROC_0ATTRMYNUMBER)
                  (= OBJPROC_1PARAMONE_NR (YESTERDAY OBJPROC_0PARAMONE_NR))
                  (= OBJPROC_0ATTRACTIVE 0)
                  (= OBJPROC_0ATTRMAX OBJPROC_0ATTRMYNUMBER)
                  (= OBJPROC_1PARAMONE_NR OBJPROC_0ATTRMYNUMBER)
                  (= OBJPROC_1PARAMONE_NR (YESTERDAY OBJPROC_0ATTRNEIGHBOURR))
                  (= OBJPROC_0ATTRMAX (YESTERDAY OBJPROC_0ATTRNEIGHBOURR))
                  (> OBJPROC_0ATTRNEIGHBOURR OBJPROC_0ATTRMAX)
                  (> OBJPROC_0ATTRNEIGHBOURR OBJPROC_0PARAMTWO_NR)
                  (= OBJPROC_0ATTRNEIGHBOURR (YESTERDAY OBJPROC_0PARAMONE_NR))
                  (= OBJPROC_1PARAMTWO_NR (YESTERDAY OBJPROC_0PARAMONE_NR))
                  (= OBJPROC_0PARAMONE_NR OBJPROC_0ATTRMAX)
                  (= OBJPROC_0ATTRACTIVE 1)
                  (= OBJPROC_0ATTRMAX (YESTERDAY OBJPROC_0ATTRMAX))
                  (= OBJPROC_0ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_0ATTRNEIGHBOURR))
                  (= OBJPROC_0ATTRMYNUMBER (YESTERDAY OBJPROC_0ATTRMYNUMBER))
                  (= OBJPROC_0ATTRACTIVE (YESTERDAY OBJPROC_0ATTRACTIVE))
                  (= OBJPROC_6PARAMWIN_NR (YESTERDAY OBJPROC_5PARAMONE_NR))
                  (<= OBJPROC_5ATTRNEIGHBOURR OBJPROC_5ATTRMAX)
                  (<= OBJPROC_5ATTRNEIGHBOURR OBJPROC_5PARAMTWO_NR)
                  (= OBJPROC_6PARAMTWO_NR (YESTERDAY OBJPROC_5PARAMTWO_NR))
                  (= OBJPROC_6PARAMWIN_NR (YESTERDAY OBJPROC_5PARAMWIN_NR))
                  (= OBJPROC_5PARAMWIN_NR OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_6PARAMONE_NR (YESTERDAY OBJPROC_5PARAMONE_NR))
                  (= OBJPROC_5ATTRACTIVE 0)
                  (= OBJPROC_5ATTRMAX OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_6PARAMONE_NR OBJPROC_5ATTRMYNUMBER)
                  (= OBJPROC_6PARAMONE_NR (YESTERDAY OBJPROC_5ATTRNEIGHBOURR))
                  (= OBJPROC_5ATTRMAX (YESTERDAY OBJPROC_5ATTRNEIGHBOURR))
                  (> OBJPROC_5ATTRNEIGHBOURR OBJPROC_5ATTRMAX)
                  (> OBJPROC_5ATTRNEIGHBOURR OBJPROC_5PARAMTWO_NR)
                  (= OBJPROC_5ATTRNEIGHBOURR (YESTERDAY OBJPROC_5PARAMONE_NR))
                  (= OBJPROC_6PARAMTWO_NR (YESTERDAY OBJPROC_5PARAMONE_NR))
                  (= OBJPROC_5PARAMONE_NR OBJPROC_5ATTRMAX)
                  (= OBJPROC_5ATTRACTIVE 1)
                  (= OBJPROC_5ATTRMAX (YESTERDAY OBJPROC_5ATTRMAX))
                  (= OBJPROC_5ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_5ATTRNEIGHBOURR))
                  (= OBJPROC_5ATTRMYNUMBER (YESTERDAY OBJPROC_5ATTRMYNUMBER))
                  (= OBJPROC_5ATTRACTIVE (YESTERDAY OBJPROC_5ATTRACTIVE))
                  (= OBJPROC_7PARAMWIN_NR (YESTERDAY OBJPROC_6PARAMONE_NR))
                  (<= OBJPROC_6ATTRNEIGHBOURR OBJPROC_6ATTRMAX)
                  (<= OBJPROC_6ATTRNEIGHBOURR OBJPROC_6PARAMTWO_NR)
                  (= OBJPROC_7PARAMTWO_NR (YESTERDAY OBJPROC_6PARAMTWO_NR))
                  (= OBJPROC_7PARAMWIN_NR (YESTERDAY OBJPROC_6PARAMWIN_NR))
                  (= OBJPROC_6PARAMWIN_NR OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_7PARAMONE_NR (YESTERDAY OBJPROC_6PARAMONE_NR))
                  (= OBJPROC_6ATTRACTIVE 0)
                  (= OBJPROC_6ATTRMAX OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_7PARAMONE_NR OBJPROC_6ATTRMYNUMBER)
                  (= OBJPROC_7PARAMONE_NR (YESTERDAY OBJPROC_6ATTRNEIGHBOURR))
                  (= OBJPROC_6ATTRMAX (YESTERDAY OBJPROC_6ATTRNEIGHBOURR))
                  (> OBJPROC_6ATTRNEIGHBOURR OBJPROC_6ATTRMAX)
                  (> OBJPROC_6ATTRNEIGHBOURR OBJPROC_6PARAMTWO_NR)
                  (= OBJPROC_6ATTRNEIGHBOURR (YESTERDAY OBJPROC_6PARAMONE_NR))
                  (= OBJPROC_7PARAMTWO_NR (YESTERDAY OBJPROC_6PARAMONE_NR))
                  (= OBJPROC_6PARAMONE_NR OBJPROC_6ATTRMAX)
                  (= OBJPROC_6ATTRACTIVE 1)
                  (= OBJPROC_6ATTRMAX (YESTERDAY OBJPROC_6ATTRMAX))
                  (= OBJPROC_6ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_6ATTRNEIGHBOURR))
                  (= OBJPROC_6ATTRMYNUMBER (YESTERDAY OBJPROC_6ATTRMYNUMBER))
                  (= OBJPROC_6ATTRACTIVE (YESTERDAY OBJPROC_6ATTRACTIVE))
                  (= OBJPROC_0PARAMWIN_NR (YESTERDAY OBJPROC_9PARAMONE_NR))
                  (<= OBJPROC_9ATTRNEIGHBOURR OBJPROC_9ATTRMAX)
                  (<= OBJPROC_9ATTRNEIGHBOURR OBJPROC_9PARAMTWO_NR)
                  (= OBJPROC_0PARAMTWO_NR (YESTERDAY OBJPROC_9PARAMTWO_NR))
                  (= OBJPROC_0PARAMWIN_NR (YESTERDAY OBJPROC_9PARAMWIN_NR))
                  (= OBJPROC_9PARAMWIN_NR OBJPROC_9ATTRMYNUMBER)
                  (= OBJPROC_0PARAMONE_NR (YESTERDAY OBJPROC_9PARAMONE_NR))
                  (= OBJPROC_9ATTRACTIVE 0)
                  (= OBJPROC_9ATTRMAX OBJPROC_9ATTRMYNUMBER)
                  (= OBJPROC_0PARAMONE_NR OBJPROC_9ATTRMYNUMBER)
                  (= OBJPROC_0PARAMONE_NR (YESTERDAY OBJPROC_9ATTRNEIGHBOURR))
                  (= OBJPROC_9ATTRMAX (YESTERDAY OBJPROC_9ATTRNEIGHBOURR))
                  (> OBJPROC_9ATTRNEIGHBOURR OBJPROC_9ATTRMAX)
                  (> OBJPROC_9ATTRNEIGHBOURR OBJPROC_9PARAMTWO_NR)
                  (= OBJPROC_9ATTRNEIGHBOURR (YESTERDAY OBJPROC_9PARAMONE_NR))
                  (= OBJPROC_0PARAMTWO_NR (YESTERDAY OBJPROC_9PARAMONE_NR))
                  (= OBJPROC_9PARAMONE_NR OBJPROC_9ATTRMAX)
                  (= OBJPROC_9ATTRACTIVE 1)
                  (= OBJPROC_9ATTRMAX (YESTERDAY OBJPROC_9ATTRMAX))
                  (= OBJPROC_9ATTRNEIGHBOURR
                     (YESTERDAY OBJPROC_9ATTRNEIGHBOURR))
                  (= OBJPROC_9ATTRMYNUMBER (YESTERDAY OBJPROC_9ATTRMYNUMBER))
                  (= OBJPROC_9ATTRACTIVE (YESTERDAY OBJPROC_9ATTRACTIVE)))
This is AE2SBVZOT.

1. processing formula
Used boolean propositions: 
((= OBJPROC_8ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
 (= OBJPROC_7ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
 (= OBJPROC_7ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
 (= OBJPROC_6ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
 (= OBJPROC_6ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
 (= OBJPROC_6ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
 (= OBJPROC_5ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
 (= OBJPROC_5ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
 (= OBJPROC_5ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
 (= OBJPROC_5ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_4ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
 (= OBJPROC_4ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
 (= OBJPROC_4ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
 (= OBJPROC_4ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_4ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
 (= OBJPROC_3ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
 (= OBJPROC_3ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
 (= OBJPROC_3ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
 (= OBJPROC_3ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_3ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
 (= OBJPROC_3ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
 (= OBJPROC_2ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
 (= OBJPROC_2ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
 (= OBJPROC_2ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
 (= OBJPROC_2ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_2ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
 (= OBJPROC_2ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
 (= OBJPROC_2ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER)
 (= OBJPROC_1ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
 (= OBJPROC_1ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
 (= OBJPROC_1ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
 (= OBJPROC_1ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_1ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
 (= OBJPROC_1ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
 (= OBJPROC_1ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER)
 (= OBJPROC_1ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_7ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER)
 (= OBJPROC_0ATTRMYNUMBER OBJPROC_1ATTRMYNUMBER)
 (= OBJPROC_2PARAMWIN_NR (YESTERDAY OBJPROC_1PARAMONE_NR))
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_TRIGGER
 (<= OBJPROC_1ATTRNEIGHBOURR OBJPROC_1ATTRMAX)
 (<= OBJPROC_1ATTRNEIGHBOURR OBJPROC_1PARAMTWO_NR)
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_2PARAMTWO_NR (YESTERDAY OBJPROC_1PARAMTWO_NR))
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_2PARAMWIN_NR (YESTERDAY OBJPROC_1PARAMWIN_NR))
 (= OBJPROC_1PARAMWIN_NR OBJPROC_1ATTRMYNUMBER)
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_2PARAMONE_NR (YESTERDAY OBJPROC_1PARAMONE_NR))
 (= OBJPROC_1ATTRACTIVE 0)
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_1ATTRMAX OBJPROC_1ATTRMYNUMBER)
 (= OBJPROC_2PARAMONE_NR OBJPROC_1ATTRMYNUMBER)
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W_TIMECONDITION
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEC_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_2PARAMONE_NR (YESTERDAY OBJPROC_1ATTRNEIGHBOURR))
 (= OBJPROC_1ATTRMAX (YESTERDAY OBJPROC_1ATTRNEIGHBOURR))
 (> OBJPROC_1ATTRNEIGHBOURR OBJPROC_1ATTRMAX)
 (> OBJPROC_1ATTRNEIGHBOURR OBJPROC_1PARAMTWO_NR)
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_1ATTRNEIGHBOURR (YESTERDAY OBJPROC_1PARAMONE_NR))
 (= OBJPROC_2PARAMTWO_NR (YESTERDAY OBJPROC_1PARAMONE_NR))
 (= OBJPROC_1PARAMONE_NR OBJPROC_1ATTRMAX) (= OBJPROC_1ATTRACTIVE 1)
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D-YEEECSEESWSDSEQA_37W
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D-YEEOCSEESWSDSEQA_37W
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D-YEDECSEESWSDSEQA_37W
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D-YEDOCSEESWSDSEQA_37W
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D-YED-CSEESWSDSEQA_37W
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D-YEDUCSEESWSDSEQA_37W
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_GUARD
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_1_STDPROCESS_SM_STATELOST_EXIT OBJPROC_1_STDPROCESS_SM_STATELOST_ENTER
 $OBJPROC_1_STDPROCESS_SM_STATELOST OBJPROC_1_STDPROCESS_SM_STATEINIT_EXIT
 OBJPROC_1_STDPROCESS_SM_STATEINIT_ENTER $OBJPROC_1_STDPROCESS_SM_STATEINIT
 OBJPROC_1_STDPROCESS_SM_STATEWIN_EXIT OBJPROC_1_STDPROCESS_SM_STATEWIN_ENTER
 $OBJPROC_1_STDPROCESS_SM_STATEWIN
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D-YEEUCSEESWSDSEQA_37W
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D-YEE-CSEESWSDSEQA_37W
 OBJPROC_1_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_1_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W
 OBJPROC_1_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_1_STDPROCESS_SM_STATEMAIN
 (= OBJPROC_1ATTRMAX (YESTERDAY OBJPROC_1ATTRMAX))
 OBJPROC_1ASSIGNMENT_D-YEC-CSEESWSDSEQA_37WMAX
 OBJPROC_1ASSIGNMENT_D-YED-CSEESWSDSEQA_37WMAX
 (= OBJPROC_1ATTRNEIGHBOURR (YESTERDAY OBJPROC_1ATTRNEIGHBOURR))
 OBJPROC_1ASSIGNMENT_D-YEDUCSEESWSDSEQA_37WNEIGHBOURR
 (= OBJPROC_1ATTRMYNUMBER (YESTERDAY OBJPROC_1ATTRMYNUMBER))
 (= OBJPROC_1ATTRACTIVE (YESTERDAY OBJPROC_1ATTRACTIVE))
 OBJPROC_1ASSIGNMENT_D-YEEOCSEESWSDSEQA_37WACTIVE OBJPROC_1OPTWO
 OBJPROC_1OPWINNER OBJPROC_1OPONE
 (= OBJPROC_8PARAMWIN_NR (YESTERDAY OBJPROC_7PARAMONE_NR))
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_GUARD
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_TRIGGER
 (<= OBJPROC_7ATTRNEIGHBOURR OBJPROC_7ATTRMAX)
 (<= OBJPROC_7ATTRNEIGHBOURR OBJPROC_7PARAMTWO_NR)
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_GUARD
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_GUARD
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_8PARAMTWO_NR (YESTERDAY OBJPROC_7PARAMTWO_NR))
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_GUARD
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_8PARAMWIN_NR (YESTERDAY OBJPROC_7PARAMWIN_NR))
 (= OBJPROC_7PARAMWIN_NR OBJPROC_7ATTRMYNUMBER)
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_GUARD
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_8PARAMONE_NR (YESTERDAY OBJPROC_7PARAMONE_NR))
 (= OBJPROC_7ATTRACTIVE 0)
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_GUARD
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_7ATTRMAX OBJPROC_7ATTRMYNUMBER)
 (= OBJPROC_8PARAMONE_NR OBJPROC_7ATTRMYNUMBER)
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W_TIMECONDITION
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEC_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_8PARAMONE_NR (YESTERDAY OBJPROC_7ATTRNEIGHBOURR))
 (= OBJPROC_7ATTRMAX (YESTERDAY OBJPROC_7ATTRNEIGHBOURR))
 (> OBJPROC_7ATTRNEIGHBOURR OBJPROC_7ATTRMAX)
 (> OBJPROC_7ATTRNEIGHBOURR OBJPROC_7PARAMTWO_NR)
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_GUARD
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_7ATTRNEIGHBOURR (YESTERDAY OBJPROC_7PARAMONE_NR))
 (= OBJPROC_8PARAMTWO_NR (YESTERDAY OBJPROC_7PARAMONE_NR))
 (= OBJPROC_7PARAMONE_NR OBJPROC_7ATTRMAX) (= OBJPROC_7ATTRACTIVE 1)
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D-YEEECSEESWSDSEQA_37W
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D-YEEOCSEESWSDSEQA_37W
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D-YEDECSEESWSDSEQA_37W
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D-YEDOCSEESWSDSEQA_37W
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D-YED-CSEESWSDSEQA_37W
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D-YEDUCSEESWSDSEQA_37W
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_GUARD
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_7_STDPROCESS_SM_STATELOST_EXIT OBJPROC_7_STDPROCESS_SM_STATELOST_ENTER
 $OBJPROC_7_STDPROCESS_SM_STATELOST OBJPROC_7_STDPROCESS_SM_STATEINIT_EXIT
 OBJPROC_7_STDPROCESS_SM_STATEINIT_ENTER $OBJPROC_7_STDPROCESS_SM_STATEINIT
 OBJPROC_7_STDPROCESS_SM_STATEWIN_EXIT OBJPROC_7_STDPROCESS_SM_STATEWIN_ENTER
 $OBJPROC_7_STDPROCESS_SM_STATEWIN
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D-YEEUCSEESWSDSEQA_37W
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D-YEE-CSEESWSDSEQA_37W
 OBJPROC_7_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_7_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W
 OBJPROC_7_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_7_STDPROCESS_SM_STATEMAIN
 (= OBJPROC_7ATTRMAX (YESTERDAY OBJPROC_7ATTRMAX))
 OBJPROC_7ASSIGNMENT_D-YEC-CSEESWSDSEQA_37WMAX
 OBJPROC_7ASSIGNMENT_D-YED-CSEESWSDSEQA_37WMAX
 (= OBJPROC_7ATTRNEIGHBOURR (YESTERDAY OBJPROC_7ATTRNEIGHBOURR))
 OBJPROC_7ASSIGNMENT_D-YEDUCSEESWSDSEQA_37WNEIGHBOURR
 (= OBJPROC_7ATTRMYNUMBER (YESTERDAY OBJPROC_7ATTRMYNUMBER))
 (= OBJPROC_7ATTRACTIVE (YESTERDAY OBJPROC_7ATTRACTIVE))
 OBJPROC_7ASSIGNMENT_D-YEEOCSEESWSDSEQA_37WACTIVE OBJPROC_7OPTWO
 OBJPROC_7OPWINNER OBJPROC_7OPONE
 (= OBJPROC_5PARAMWIN_NR (YESTERDAY OBJPROC_4PARAMONE_NR))
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_TRIGGER
 (<= OBJPROC_4ATTRNEIGHBOURR OBJPROC_4ATTRMAX)
 (<= OBJPROC_4ATTRNEIGHBOURR OBJPROC_4PARAMTWO_NR)
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_5PARAMTWO_NR (YESTERDAY OBJPROC_4PARAMTWO_NR))
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_5PARAMWIN_NR (YESTERDAY OBJPROC_4PARAMWIN_NR))
 (= OBJPROC_4PARAMWIN_NR OBJPROC_4ATTRMYNUMBER)
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_5PARAMONE_NR (YESTERDAY OBJPROC_4PARAMONE_NR))
 (= OBJPROC_4ATTRACTIVE 0)
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_4ATTRMAX OBJPROC_4ATTRMYNUMBER)
 (= OBJPROC_5PARAMONE_NR OBJPROC_4ATTRMYNUMBER)
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W_TIMECONDITION
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEC_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_5PARAMONE_NR (YESTERDAY OBJPROC_4ATTRNEIGHBOURR))
 (= OBJPROC_4ATTRMAX (YESTERDAY OBJPROC_4ATTRNEIGHBOURR))
 (> OBJPROC_4ATTRNEIGHBOURR OBJPROC_4ATTRMAX)
 (> OBJPROC_4ATTRNEIGHBOURR OBJPROC_4PARAMTWO_NR)
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_4ATTRNEIGHBOURR (YESTERDAY OBJPROC_4PARAMONE_NR))
 (= OBJPROC_5PARAMTWO_NR (YESTERDAY OBJPROC_4PARAMONE_NR))
 (= OBJPROC_4PARAMONE_NR OBJPROC_4ATTRMAX) (= OBJPROC_4ATTRACTIVE 1)
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D-YEEECSEESWSDSEQA_37W
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D-YEEOCSEESWSDSEQA_37W
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D-YEDECSEESWSDSEQA_37W
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D-YEDOCSEESWSDSEQA_37W
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D-YED-CSEESWSDSEQA_37W
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D-YEDUCSEESWSDSEQA_37W
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_GUARD
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_4_STDPROCESS_SM_STATELOST_EXIT OBJPROC_4_STDPROCESS_SM_STATELOST_ENTER
 $OBJPROC_4_STDPROCESS_SM_STATELOST OBJPROC_4_STDPROCESS_SM_STATEINIT_EXIT
 OBJPROC_4_STDPROCESS_SM_STATEINIT_ENTER $OBJPROC_4_STDPROCESS_SM_STATEINIT
 OBJPROC_4_STDPROCESS_SM_STATEWIN_EXIT OBJPROC_4_STDPROCESS_SM_STATEWIN_ENTER
 $OBJPROC_4_STDPROCESS_SM_STATEWIN
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D-YEEUCSEESWSDSEQA_37W
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D-YEE-CSEESWSDSEQA_37W
 OBJPROC_4_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_4_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W
 OBJPROC_4_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_4_STDPROCESS_SM_STATEMAIN
 (= OBJPROC_4ATTRMAX (YESTERDAY OBJPROC_4ATTRMAX))
 OBJPROC_4ASSIGNMENT_D-YEC-CSEESWSDSEQA_37WMAX
 OBJPROC_4ASSIGNMENT_D-YED-CSEESWSDSEQA_37WMAX
 (= OBJPROC_4ATTRNEIGHBOURR (YESTERDAY OBJPROC_4ATTRNEIGHBOURR))
 OBJPROC_4ASSIGNMENT_D-YEDUCSEESWSDSEQA_37WNEIGHBOURR
 (= OBJPROC_4ATTRMYNUMBER (YESTERDAY OBJPROC_4ATTRMYNUMBER))
 (= OBJPROC_4ATTRACTIVE (YESTERDAY OBJPROC_4ATTRACTIVE))
 OBJPROC_4ASSIGNMENT_D-YEEOCSEESWSDSEQA_37WACTIVE OBJPROC_4OPTWO
 OBJPROC_4OPWINNER OBJPROC_4OPONE
 (= OBJPROC_9PARAMWIN_NR (YESTERDAY OBJPROC_8PARAMONE_NR))
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_GUARD
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_TRIGGER
 (<= OBJPROC_8ATTRNEIGHBOURR OBJPROC_8ATTRMAX)
 (<= OBJPROC_8ATTRNEIGHBOURR OBJPROC_8PARAMTWO_NR)
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_GUARD
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_GUARD
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_9PARAMTWO_NR (YESTERDAY OBJPROC_8PARAMTWO_NR))
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_GUARD
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_9PARAMWIN_NR (YESTERDAY OBJPROC_8PARAMWIN_NR))
 (= OBJPROC_8PARAMWIN_NR OBJPROC_8ATTRMYNUMBER)
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_GUARD
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_9PARAMONE_NR (YESTERDAY OBJPROC_8PARAMONE_NR))
 (= OBJPROC_8ATTRACTIVE 0)
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_GUARD
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_8ATTRMAX OBJPROC_8ATTRMYNUMBER)
 (= OBJPROC_9PARAMONE_NR OBJPROC_8ATTRMYNUMBER)
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W_TIMECONDITION
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEC_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_9PARAMONE_NR (YESTERDAY OBJPROC_8ATTRNEIGHBOURR))
 (= OBJPROC_8ATTRMAX (YESTERDAY OBJPROC_8ATTRNEIGHBOURR))
 (> OBJPROC_8ATTRNEIGHBOURR OBJPROC_8ATTRMAX)
 (> OBJPROC_8ATTRNEIGHBOURR OBJPROC_8PARAMTWO_NR)
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_GUARD
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_8ATTRNEIGHBOURR (YESTERDAY OBJPROC_8PARAMONE_NR))
 (= OBJPROC_9PARAMTWO_NR (YESTERDAY OBJPROC_8PARAMONE_NR))
 (= OBJPROC_8PARAMONE_NR OBJPROC_8ATTRMAX) (= OBJPROC_8ATTRACTIVE 1)
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D-YEEECSEESWSDSEQA_37W
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D-YEEOCSEESWSDSEQA_37W
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D-YEDECSEESWSDSEQA_37W
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D-YEDOCSEESWSDSEQA_37W
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D-YED-CSEESWSDSEQA_37W
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D-YEDUCSEESWSDSEQA_37W
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_GUARD
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_8_STDPROCESS_SM_STATELOST_EXIT OBJPROC_8_STDPROCESS_SM_STATELOST_ENTER
 $OBJPROC_8_STDPROCESS_SM_STATELOST OBJPROC_8_STDPROCESS_SM_STATEINIT_EXIT
 OBJPROC_8_STDPROCESS_SM_STATEINIT_ENTER $OBJPROC_8_STDPROCESS_SM_STATEINIT
 OBJPROC_8_STDPROCESS_SM_STATEWIN_EXIT OBJPROC_8_STDPROCESS_SM_STATEWIN_ENTER
 $OBJPROC_8_STDPROCESS_SM_STATEWIN
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D-YEEUCSEESWSDSEQA_37W
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D-YEE-CSEESWSDSEQA_37W
 OBJPROC_8_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_8_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W
 OBJPROC_8_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_8_STDPROCESS_SM_STATEMAIN
 (= OBJPROC_8ATTRMAX (YESTERDAY OBJPROC_8ATTRMAX))
 OBJPROC_8ASSIGNMENT_D-YEC-CSEESWSDSEQA_37WMAX
 OBJPROC_8ASSIGNMENT_D-YED-CSEESWSDSEQA_37WMAX
 (= OBJPROC_8ATTRNEIGHBOURR (YESTERDAY OBJPROC_8ATTRNEIGHBOURR))
 OBJPROC_8ASSIGNMENT_D-YEDUCSEESWSDSEQA_37WNEIGHBOURR
 (= OBJPROC_8ATTRMYNUMBER (YESTERDAY OBJPROC_8ATTRMYNUMBER))
 (= OBJPROC_8ATTRACTIVE (YESTERDAY OBJPROC_8ATTRACTIVE))
 OBJPROC_8ASSIGNMENT_D-YEEOCSEESWSDSEQA_37WACTIVE
 OBJPROC_8OPTWOTR_D-YEDUCSEESWSDSEQA_37W_CALL
 OBJPROC_8OPTWOTR_D-YEDECSEESWSDSEQA_37W_CALL OBJPROC_8OPTWO
 OBJPROC_8OPWINNERTR_D-YEE-CSEESWSDSEQA_37W_CALL
 OBJPROC_8OPWINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_8OPWINNERTR_D-YEEUCSEESWSDSEQA_37W_CALL OBJPROC_8OPWINNER
 OBJPROC_8OPONETR_D-YEDOCSEESWSDSEQA_37W_CALL
 OBJPROC_8OPONETR_D-YED-CSEESWSDSEQA_37W_CALL
 OBJPROC_8OPONETR_D-YEC-CSEESWSDSEQA_37W_CALL OBJPROC_8OPONE
 (= OBJPROC_3PARAMWIN_NR (YESTERDAY OBJPROC_2PARAMONE_NR))
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_TRIGGER
 (<= OBJPROC_2ATTRNEIGHBOURR OBJPROC_2ATTRMAX)
 (<= OBJPROC_2ATTRNEIGHBOURR OBJPROC_2PARAMTWO_NR)
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_3PARAMTWO_NR (YESTERDAY OBJPROC_2PARAMTWO_NR))
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_3PARAMWIN_NR (YESTERDAY OBJPROC_2PARAMWIN_NR))
 (= OBJPROC_2PARAMWIN_NR OBJPROC_2ATTRMYNUMBER)
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_3PARAMONE_NR (YESTERDAY OBJPROC_2PARAMONE_NR))
 (= OBJPROC_2ATTRACTIVE 0)
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_2ATTRMAX OBJPROC_2ATTRMYNUMBER)
 (= OBJPROC_3PARAMONE_NR OBJPROC_2ATTRMYNUMBER)
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W_TIMECONDITION
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEC_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_3PARAMONE_NR (YESTERDAY OBJPROC_2ATTRNEIGHBOURR))
 (= OBJPROC_2ATTRMAX (YESTERDAY OBJPROC_2ATTRNEIGHBOURR))
 (> OBJPROC_2ATTRNEIGHBOURR OBJPROC_2ATTRMAX)
 (> OBJPROC_2ATTRNEIGHBOURR OBJPROC_2PARAMTWO_NR)
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_2ATTRNEIGHBOURR (YESTERDAY OBJPROC_2PARAMONE_NR))
 (= OBJPROC_3PARAMTWO_NR (YESTERDAY OBJPROC_2PARAMONE_NR))
 (= OBJPROC_2PARAMONE_NR OBJPROC_2ATTRMAX) (= OBJPROC_2ATTRACTIVE 1)
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D-YEEECSEESWSDSEQA_37W
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D-YEEOCSEESWSDSEQA_37W
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D-YEDECSEESWSDSEQA_37W
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D-YEDOCSEESWSDSEQA_37W
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D-YED-CSEESWSDSEQA_37W
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D-YEDUCSEESWSDSEQA_37W
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_GUARD
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_2_STDPROCESS_SM_STATELOST_EXIT OBJPROC_2_STDPROCESS_SM_STATELOST_ENTER
 $OBJPROC_2_STDPROCESS_SM_STATELOST OBJPROC_2_STDPROCESS_SM_STATEINIT_EXIT
 OBJPROC_2_STDPROCESS_SM_STATEINIT_ENTER $OBJPROC_2_STDPROCESS_SM_STATEINIT
 OBJPROC_2_STDPROCESS_SM_STATEWIN_EXIT OBJPROC_2_STDPROCESS_SM_STATEWIN_ENTER
 $OBJPROC_2_STDPROCESS_SM_STATEWIN
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D-YEEUCSEESWSDSEQA_37W
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D-YEE-CSEESWSDSEQA_37W
 OBJPROC_2_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_2_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W
 OBJPROC_2_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_2_STDPROCESS_SM_STATEMAIN
 (= OBJPROC_2ATTRMAX (YESTERDAY OBJPROC_2ATTRMAX))
 OBJPROC_2ASSIGNMENT_D-YEC-CSEESWSDSEQA_37WMAX
 OBJPROC_2ASSIGNMENT_D-YED-CSEESWSDSEQA_37WMAX
 (= OBJPROC_2ATTRNEIGHBOURR (YESTERDAY OBJPROC_2ATTRNEIGHBOURR))
 OBJPROC_2ASSIGNMENT_D-YEDUCSEESWSDSEQA_37WNEIGHBOURR
 (= OBJPROC_2ATTRMYNUMBER (YESTERDAY OBJPROC_2ATTRMYNUMBER))
 (= OBJPROC_2ATTRACTIVE (YESTERDAY OBJPROC_2ATTRACTIVE))
 OBJPROC_2ASSIGNMENT_D-YEEOCSEESWSDSEQA_37WACTIVE
 OBJPROC_2OPTWOTR_D-YEDUCSEESWSDSEQA_37W_CALL
 OBJPROC_2OPTWOTR_D-YEDECSEESWSDSEQA_37W_CALL OBJPROC_2OPTWO
 OBJPROC_2OPWINNERTR_D-YEE-CSEESWSDSEQA_37W_CALL
 OBJPROC_2OPWINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_2OPWINNERTR_D-YEEUCSEESWSDSEQA_37W_CALL OBJPROC_2OPWINNER
 OBJPROC_2OPONETR_D-YEC-CSEESWSDSEQA_37W_CALL
 OBJPROC_2OPONETR_D-YEDOCSEESWSDSEQA_37W_CALL
 OBJPROC_2OPONETR_D-YED-CSEESWSDSEQA_37W_CALL OBJPROC_2OPONE
 (= OBJPROC_4PARAMWIN_NR (YESTERDAY OBJPROC_3PARAMONE_NR))
 OBJPROC_4OPWINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_TRIGGER
 (<= OBJPROC_3ATTRNEIGHBOURR OBJPROC_3ATTRMAX)
 (<= OBJPROC_3ATTRNEIGHBOURR OBJPROC_3PARAMTWO_NR)
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_4OPWINNERTR_D-YEEUCSEESWSDSEQA_37W_CALL
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_4PARAMTWO_NR (YESTERDAY OBJPROC_3PARAMTWO_NR))
 OBJPROC_4OPTWOTR_D-YEDECSEESWSDSEQA_37W_CALL
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_4PARAMWIN_NR (YESTERDAY OBJPROC_3PARAMWIN_NR))
 OBJPROC_4OPWINNERTR_D-YEE-CSEESWSDSEQA_37W_CALL
 (= OBJPROC_3PARAMWIN_NR OBJPROC_3ATTRMYNUMBER)
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_4PARAMONE_NR (YESTERDAY OBJPROC_3PARAMONE_NR))
 OBJPROC_4OPONETR_D-YEDOCSEESWSDSEQA_37W_CALL (= OBJPROC_3ATTRACTIVE 0)
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_3ATTRMAX OBJPROC_3ATTRMYNUMBER)
 (= OBJPROC_4PARAMONE_NR OBJPROC_3ATTRMYNUMBER)
 OBJPROC_4OPONETR_D-YEC-CSEESWSDSEQA_37W_CALL
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W_TIMECONDITION
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEC_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_4PARAMONE_NR (YESTERDAY OBJPROC_3ATTRNEIGHBOURR))
 OBJPROC_4OPONETR_D-YED-CSEESWSDSEQA_37W_CALL
 (= OBJPROC_3ATTRMAX (YESTERDAY OBJPROC_3ATTRNEIGHBOURR))
 (> OBJPROC_3ATTRNEIGHBOURR OBJPROC_3ATTRMAX)
 (> OBJPROC_3ATTRNEIGHBOURR OBJPROC_3PARAMTWO_NR)
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_3ATTRNEIGHBOURR (YESTERDAY OBJPROC_3PARAMONE_NR))
 (= OBJPROC_4PARAMTWO_NR (YESTERDAY OBJPROC_3PARAMONE_NR))
 OBJPROC_4OPTWOTR_D-YEDUCSEESWSDSEQA_37W_CALL
 (= OBJPROC_3PARAMONE_NR OBJPROC_3ATTRMAX) (= OBJPROC_3ATTRACTIVE 1)
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D-YEEECSEESWSDSEQA_37W
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D-YEEOCSEESWSDSEQA_37W
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D-YEDECSEESWSDSEQA_37W
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D-YEDOCSEESWSDSEQA_37W
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D-YED-CSEESWSDSEQA_37W
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D-YEDUCSEESWSDSEQA_37W
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_GUARD
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_3_STDPROCESS_SM_STATELOST_EXIT OBJPROC_3_STDPROCESS_SM_STATELOST_ENTER
 $OBJPROC_3_STDPROCESS_SM_STATELOST OBJPROC_3_STDPROCESS_SM_STATEINIT_EXIT
 OBJPROC_3_STDPROCESS_SM_STATEINIT_ENTER $OBJPROC_3_STDPROCESS_SM_STATEINIT
 OBJPROC_3_STDPROCESS_SM_STATEWIN_EXIT OBJPROC_3_STDPROCESS_SM_STATEWIN_ENTER
 $OBJPROC_3_STDPROCESS_SM_STATEWIN
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D-YEEUCSEESWSDSEQA_37W
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D-YEE-CSEESWSDSEQA_37W
 OBJPROC_3_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_3_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W
 OBJPROC_3_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_3_STDPROCESS_SM_STATEMAIN
 (= OBJPROC_3ATTRMAX (YESTERDAY OBJPROC_3ATTRMAX))
 OBJPROC_3ASSIGNMENT_D-YEC-CSEESWSDSEQA_37WMAX
 OBJPROC_3ASSIGNMENT_D-YED-CSEESWSDSEQA_37WMAX
 (= OBJPROC_3ATTRNEIGHBOURR (YESTERDAY OBJPROC_3ATTRNEIGHBOURR))
 OBJPROC_3ASSIGNMENT_D-YEDUCSEESWSDSEQA_37WNEIGHBOURR
 (= OBJPROC_3ATTRMYNUMBER (YESTERDAY OBJPROC_3ATTRMYNUMBER))
 (= OBJPROC_3ATTRACTIVE (YESTERDAY OBJPROC_3ATTRACTIVE))
 OBJPROC_3ASSIGNMENT_D-YEEOCSEESWSDSEQA_37WACTIVE
 OBJPROC_3OPTWOTR_D-YEDUCSEESWSDSEQA_37W_CALL
 OBJPROC_3OPTWOTR_D-YEDECSEESWSDSEQA_37W_CALL OBJPROC_3OPTWO
 OBJPROC_3OPWINNERTR_D-YEE-CSEESWSDSEQA_37W_CALL
 OBJPROC_3OPWINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_3OPWINNERTR_D-YEEUCSEESWSDSEQA_37W_CALL OBJPROC_3OPWINNER
 OBJPROC_3OPONETR_D-YEC-CSEESWSDSEQA_37W_CALL
 OBJPROC_3OPONETR_D-YED-CSEESWSDSEQA_37W_CALL
 OBJPROC_3OPONETR_D-YEDOCSEESWSDSEQA_37W_CALL OBJPROC_3OPONE
 (= OBJPROC_1PARAMWIN_NR (YESTERDAY OBJPROC_0PARAMONE_NR))
 OBJPROC_1OPWINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_TRIGGER
 (<= OBJPROC_0ATTRNEIGHBOURR OBJPROC_0ATTRMAX)
 (<= OBJPROC_0ATTRNEIGHBOURR OBJPROC_0PARAMTWO_NR)
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_1OPWINNERTR_D-YEEUCSEESWSDSEQA_37W_CALL
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_1PARAMTWO_NR (YESTERDAY OBJPROC_0PARAMTWO_NR))
 OBJPROC_1OPTWOTR_D-YEDECSEESWSDSEQA_37W_CALL
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_1PARAMWIN_NR (YESTERDAY OBJPROC_0PARAMWIN_NR))
 OBJPROC_1OPWINNERTR_D-YEE-CSEESWSDSEQA_37W_CALL
 (= OBJPROC_0PARAMWIN_NR OBJPROC_0ATTRMYNUMBER)
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_1PARAMONE_NR (YESTERDAY OBJPROC_0PARAMONE_NR))
 OBJPROC_1OPONETR_D-YEDOCSEESWSDSEQA_37W_CALL (= OBJPROC_0ATTRACTIVE 0)
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_0ATTRMAX OBJPROC_0ATTRMYNUMBER)
 (= OBJPROC_1PARAMONE_NR OBJPROC_0ATTRMYNUMBER)
 OBJPROC_1OPONETR_D-YEC-CSEESWSDSEQA_37W_CALL
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W_TIMECONDITION
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEC_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_1PARAMONE_NR (YESTERDAY OBJPROC_0ATTRNEIGHBOURR))
 OBJPROC_1OPONETR_D-YED-CSEESWSDSEQA_37W_CALL
 (= OBJPROC_0ATTRMAX (YESTERDAY OBJPROC_0ATTRNEIGHBOURR))
 (> OBJPROC_0ATTRNEIGHBOURR OBJPROC_0ATTRMAX)
 (> OBJPROC_0ATTRNEIGHBOURR OBJPROC_0PARAMTWO_NR)
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_0ATTRNEIGHBOURR (YESTERDAY OBJPROC_0PARAMONE_NR))
 (= OBJPROC_1PARAMTWO_NR (YESTERDAY OBJPROC_0PARAMONE_NR))
 OBJPROC_1OPTWOTR_D-YEDUCSEESWSDSEQA_37W_CALL
 (= OBJPROC_0PARAMONE_NR OBJPROC_0ATTRMAX) (= OBJPROC_0ATTRACTIVE 1)
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D-YEEECSEESWSDSEQA_37W
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D-YEEOCSEESWSDSEQA_37W
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D-YEDECSEESWSDSEQA_37W
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D-YEDOCSEESWSDSEQA_37W
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D-YED-CSEESWSDSEQA_37W
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D-YEDUCSEESWSDSEQA_37W
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_GUARD
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_0_STDPROCESS_SM_STATELOST_EXIT OBJPROC_0_STDPROCESS_SM_STATELOST_ENTER
 $OBJPROC_0_STDPROCESS_SM_STATELOST OBJPROC_0_STDPROCESS_SM_STATEINIT_EXIT
 OBJPROC_0_STDPROCESS_SM_STATEINIT_ENTER $OBJPROC_0_STDPROCESS_SM_STATEINIT
 OBJPROC_0_STDPROCESS_SM_STATEWIN_EXIT OBJPROC_0_STDPROCESS_SM_STATEWIN_ENTER
 $OBJPROC_0_STDPROCESS_SM_STATEWIN
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D-YEEUCSEESWSDSEQA_37W
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D-YEE-CSEESWSDSEQA_37W
 OBJPROC_0_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_0_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W
 OBJPROC_0_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_0_STDPROCESS_SM_STATEMAIN
 (= OBJPROC_0ATTRMAX (YESTERDAY OBJPROC_0ATTRMAX))
 OBJPROC_0ASSIGNMENT_D-YEC-CSEESWSDSEQA_37WMAX
 OBJPROC_0ASSIGNMENT_D-YED-CSEESWSDSEQA_37WMAX
 (= OBJPROC_0ATTRNEIGHBOURR (YESTERDAY OBJPROC_0ATTRNEIGHBOURR))
 OBJPROC_0ASSIGNMENT_D-YEDUCSEESWSDSEQA_37WNEIGHBOURR
 (= OBJPROC_0ATTRMYNUMBER (YESTERDAY OBJPROC_0ATTRMYNUMBER))
 (= OBJPROC_0ATTRACTIVE (YESTERDAY OBJPROC_0ATTRACTIVE))
 OBJPROC_0ASSIGNMENT_D-YEEOCSEESWSDSEQA_37WACTIVE OBJPROC_0OPTWO
 OBJPROC_0OPWINNER OBJPROC_0OPONE
 (= OBJPROC_6PARAMWIN_NR (YESTERDAY OBJPROC_5PARAMONE_NR))
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_TRIGGER
 (<= OBJPROC_5ATTRNEIGHBOURR OBJPROC_5ATTRMAX)
 (<= OBJPROC_5ATTRNEIGHBOURR OBJPROC_5PARAMTWO_NR)
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_6PARAMTWO_NR (YESTERDAY OBJPROC_5PARAMTWO_NR))
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_6PARAMWIN_NR (YESTERDAY OBJPROC_5PARAMWIN_NR))
 (= OBJPROC_5PARAMWIN_NR OBJPROC_5ATTRMYNUMBER)
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_6PARAMONE_NR (YESTERDAY OBJPROC_5PARAMONE_NR))
 (= OBJPROC_5ATTRACTIVE 0)
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_5ATTRMAX OBJPROC_5ATTRMYNUMBER)
 (= OBJPROC_6PARAMONE_NR OBJPROC_5ATTRMYNUMBER)
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W_TIMECONDITION
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEC_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_6PARAMONE_NR (YESTERDAY OBJPROC_5ATTRNEIGHBOURR))
 (= OBJPROC_5ATTRMAX (YESTERDAY OBJPROC_5ATTRNEIGHBOURR))
 (> OBJPROC_5ATTRNEIGHBOURR OBJPROC_5ATTRMAX)
 (> OBJPROC_5ATTRNEIGHBOURR OBJPROC_5PARAMTWO_NR)
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_5ATTRNEIGHBOURR (YESTERDAY OBJPROC_5PARAMONE_NR))
 (= OBJPROC_6PARAMTWO_NR (YESTERDAY OBJPROC_5PARAMONE_NR))
 (= OBJPROC_5PARAMONE_NR OBJPROC_5ATTRMAX) (= OBJPROC_5ATTRACTIVE 1)
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D-YEEECSEESWSDSEQA_37W
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D-YEEOCSEESWSDSEQA_37W
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D-YEDECSEESWSDSEQA_37W
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D-YEDOCSEESWSDSEQA_37W
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D-YED-CSEESWSDSEQA_37W
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D-YEDUCSEESWSDSEQA_37W
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_GUARD
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_5_STDPROCESS_SM_STATELOST_EXIT OBJPROC_5_STDPROCESS_SM_STATELOST_ENTER
 $OBJPROC_5_STDPROCESS_SM_STATELOST OBJPROC_5_STDPROCESS_SM_STATEINIT_EXIT
 OBJPROC_5_STDPROCESS_SM_STATEINIT_ENTER $OBJPROC_5_STDPROCESS_SM_STATEINIT
 OBJPROC_5_STDPROCESS_SM_STATEWIN_EXIT OBJPROC_5_STDPROCESS_SM_STATEWIN_ENTER
 $OBJPROC_5_STDPROCESS_SM_STATEWIN
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D-YEEUCSEESWSDSEQA_37W
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D-YEE-CSEESWSDSEQA_37W
 OBJPROC_5_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_5_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W
 OBJPROC_5_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_5_STDPROCESS_SM_STATEMAIN
 (= OBJPROC_5ATTRMAX (YESTERDAY OBJPROC_5ATTRMAX))
 OBJPROC_5ASSIGNMENT_D-YEC-CSEESWSDSEQA_37WMAX
 OBJPROC_5ASSIGNMENT_D-YED-CSEESWSDSEQA_37WMAX
 (= OBJPROC_5ATTRNEIGHBOURR (YESTERDAY OBJPROC_5ATTRNEIGHBOURR))
 OBJPROC_5ASSIGNMENT_D-YEDUCSEESWSDSEQA_37WNEIGHBOURR
 (= OBJPROC_5ATTRMYNUMBER (YESTERDAY OBJPROC_5ATTRMYNUMBER))
 (= OBJPROC_5ATTRACTIVE (YESTERDAY OBJPROC_5ATTRACTIVE))
 OBJPROC_5ASSIGNMENT_D-YEEOCSEESWSDSEQA_37WACTIVE
 OBJPROC_5OPTWOTR_D-YEDUCSEESWSDSEQA_37W_CALL
 OBJPROC_5OPTWOTR_D-YEDECSEESWSDSEQA_37W_CALL OBJPROC_5OPTWO
 OBJPROC_5OPWINNERTR_D-YEE-CSEESWSDSEQA_37W_CALL
 OBJPROC_5OPWINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_5OPWINNERTR_D-YEEUCSEESWSDSEQA_37W_CALL OBJPROC_5OPWINNER
 OBJPROC_5OPONETR_D-YEC-CSEESWSDSEQA_37W_CALL
 OBJPROC_5OPONETR_D-YED-CSEESWSDSEQA_37W_CALL
 OBJPROC_5OPONETR_D-YEDOCSEESWSDSEQA_37W_CALL OBJPROC_5OPONE
 (= OBJPROC_7PARAMWIN_NR (YESTERDAY OBJPROC_6PARAMONE_NR))
 OBJPROC_7OPWINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_TRIGGER
 (<= OBJPROC_6ATTRNEIGHBOURR OBJPROC_6ATTRMAX)
 (<= OBJPROC_6ATTRNEIGHBOURR OBJPROC_6PARAMTWO_NR)
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_7OPWINNERTR_D-YEEUCSEESWSDSEQA_37W_CALL
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_7PARAMTWO_NR (YESTERDAY OBJPROC_6PARAMTWO_NR))
 OBJPROC_7OPTWOTR_D-YEDECSEESWSDSEQA_37W_CALL
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_7PARAMWIN_NR (YESTERDAY OBJPROC_6PARAMWIN_NR))
 OBJPROC_7OPWINNERTR_D-YEE-CSEESWSDSEQA_37W_CALL
 (= OBJPROC_6PARAMWIN_NR OBJPROC_6ATTRMYNUMBER)
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_7PARAMONE_NR (YESTERDAY OBJPROC_6PARAMONE_NR))
 OBJPROC_7OPONETR_D-YEDOCSEESWSDSEQA_37W_CALL (= OBJPROC_6ATTRACTIVE 0)
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_6ATTRMAX OBJPROC_6ATTRMYNUMBER)
 (= OBJPROC_7PARAMONE_NR OBJPROC_6ATTRMYNUMBER)
 OBJPROC_7OPONETR_D-YEC-CSEESWSDSEQA_37W_CALL
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W_TIMECONDITION
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEC_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_7PARAMONE_NR (YESTERDAY OBJPROC_6ATTRNEIGHBOURR))
 OBJPROC_7OPONETR_D-YED-CSEESWSDSEQA_37W_CALL
 (= OBJPROC_6ATTRMAX (YESTERDAY OBJPROC_6ATTRNEIGHBOURR))
 (> OBJPROC_6ATTRNEIGHBOURR OBJPROC_6ATTRMAX)
 (> OBJPROC_6ATTRNEIGHBOURR OBJPROC_6PARAMTWO_NR)
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_6ATTRNEIGHBOURR (YESTERDAY OBJPROC_6PARAMONE_NR))
 (= OBJPROC_7PARAMTWO_NR (YESTERDAY OBJPROC_6PARAMONE_NR))
 OBJPROC_7OPTWOTR_D-YEDUCSEESWSDSEQA_37W_CALL
 (= OBJPROC_6PARAMONE_NR OBJPROC_6ATTRMAX) (= OBJPROC_6ATTRACTIVE 1)
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D-YEEECSEESWSDSEQA_37W
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D-YEEOCSEESWSDSEQA_37W
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D-YEDECSEESWSDSEQA_37W
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D-YEDOCSEESWSDSEQA_37W
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D-YED-CSEESWSDSEQA_37W
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D-YEDUCSEESWSDSEQA_37W
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_GUARD
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_6_STDPROCESS_SM_STATELOST_EXIT OBJPROC_6_STDPROCESS_SM_STATELOST_ENTER
 $OBJPROC_6_STDPROCESS_SM_STATELOST OBJPROC_6_STDPROCESS_SM_STATEINIT_EXIT
 OBJPROC_6_STDPROCESS_SM_STATEINIT_ENTER $OBJPROC_6_STDPROCESS_SM_STATEINIT
 OBJPROC_6_STDPROCESS_SM_STATEWIN_EXIT OBJPROC_6_STDPROCESS_SM_STATEWIN_ENTER
 $OBJPROC_6_STDPROCESS_SM_STATEWIN
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D-YEEUCSEESWSDSEQA_37W
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D-YEE-CSEESWSDSEQA_37W
 OBJPROC_6_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_6_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W
 OBJPROC_6_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_6_STDPROCESS_SM_STATEMAIN
 (= OBJPROC_6ATTRMAX (YESTERDAY OBJPROC_6ATTRMAX))
 OBJPROC_6ASSIGNMENT_D-YEC-CSEESWSDSEQA_37WMAX
 OBJPROC_6ASSIGNMENT_D-YED-CSEESWSDSEQA_37WMAX
 (= OBJPROC_6ATTRNEIGHBOURR (YESTERDAY OBJPROC_6ATTRNEIGHBOURR))
 OBJPROC_6ASSIGNMENT_D-YEDUCSEESWSDSEQA_37WNEIGHBOURR
 (= OBJPROC_6ATTRMYNUMBER (YESTERDAY OBJPROC_6ATTRMYNUMBER))
 (= OBJPROC_6ATTRACTIVE (YESTERDAY OBJPROC_6ATTRACTIVE))
 OBJPROC_6ASSIGNMENT_D-YEEOCSEESWSDSEQA_37WACTIVE
 OBJPROC_6OPTWOTR_D-YEDUCSEESWSDSEQA_37W_CALL
 OBJPROC_6OPTWOTR_D-YEDECSEESWSDSEQA_37W_CALL OBJPROC_6OPTWO
 OBJPROC_6OPWINNERTR_D-YEE-CSEESWSDSEQA_37W_CALL
 OBJPROC_6OPWINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_6OPWINNERTR_D-YEEUCSEESWSDSEQA_37W_CALL OBJPROC_6OPWINNER
 OBJPROC_6OPONETR_D-YEDOCSEESWSDSEQA_37W_CALL
 OBJPROC_6OPONETR_D-YED-CSEESWSDSEQA_37W_CALL
 OBJPROC_6OPONETR_D-YEC-CSEESWSDSEQA_37W_CALL OBJPROC_6OPONE
 OBJMONITOR_STDMONITOR_SM_TRANSITION_D_YEI_CSEESWSDSEQA_37W_TRIGGER
 OBJMONITOR_STDMONITOR_SM_TRANSITION_D_YEJOCSEESWSDSEQA_37W_TRIGGER
 OBJMONITOR_STDMONITOR_SM_STATESTATE_ERROR_EXIT
 OBJMONITOR_STDMONITOR_SM_STATESTATE_ERROR_ENTER
 $OBJMONITOR_STDMONITOR_SM_STATESTATE_ERROR
 OBJMONITOR_STDMONITOR_SM_TRANSITION_D-YEJOCSEESWSDSEQA_37W
 OBJMONITOR_STDMONITOR_SM_STATESTATE_WINNER_EXIT
 OBJMONITOR_STDMONITOR_SM_STATESTATE_WINNER_ENTER
 $OBJMONITOR_STDMONITOR_SM_STATESTATE_WINNER
 OBJMONITOR_STDMONITOR_SM_TRANSITION_D-YEI-CSEESWSDSEQA_37W
 OBJMONITOR_STDMONITOR_SM_STATESTATE_NO_WINNER_EXIT
 OBJMONITOR_STDMONITOR_SM_STATESTATE_NO_WINNER_ENTER
 $OBJMONITOR_STDMONITOR_SM_STATESTATE_NO_WINNER
 (= OBJPROC_0PARAMWIN_NR (YESTERDAY OBJPROC_9PARAMONE_NR))
 OBJPROC_0OPWINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_GUARD
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEEECSEESWSDSEQA_37W_TRIGGER
 (<= OBJPROC_9ATTRNEIGHBOURR OBJPROC_9ATTRMAX)
 (<= OBJPROC_9ATTRNEIGHBOURR OBJPROC_9PARAMTWO_NR)
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_GUARD
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEEOCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_0OPWINNERTR_D-YEEUCSEESWSDSEQA_37W_CALL
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_GUARD
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEEUCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_0PARAMTWO_NR (YESTERDAY OBJPROC_9PARAMTWO_NR))
 OBJPROC_0OPTWOTR_D-YEDECSEESWSDSEQA_37W_CALL
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_GUARD
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEDECSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_0PARAMWIN_NR (YESTERDAY OBJPROC_9PARAMWIN_NR))
 OBJPROC_0OPWINNERTR_D-YEE-CSEESWSDSEQA_37W_CALL
 (= OBJPROC_9PARAMWIN_NR OBJPROC_9ATTRMYNUMBER)
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_GUARD
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEE_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_0PARAMONE_NR (YESTERDAY OBJPROC_9PARAMONE_NR))
 OBJPROC_0OPONETR_D-YEDOCSEESWSDSEQA_37W_CALL (= OBJPROC_9ATTRACTIVE 0)
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_GUARD
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEDOCSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_9ATTRMAX OBJPROC_9ATTRMYNUMBER)
 (= OBJPROC_0PARAMONE_NR OBJPROC_9ATTRMYNUMBER)
 OBJPROC_0OPONETR_D-YEC-CSEESWSDSEQA_37W_CALL
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W_TIMECONDITION
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEC_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_0PARAMONE_NR (YESTERDAY OBJPROC_9ATTRNEIGHBOURR))
 OBJPROC_0OPONETR_D-YED-CSEESWSDSEQA_37W_CALL
 (= OBJPROC_9ATTRMAX (YESTERDAY OBJPROC_9ATTRNEIGHBOURR))
 (> OBJPROC_9ATTRNEIGHBOURR OBJPROC_9ATTRMAX)
 (> OBJPROC_9ATTRNEIGHBOURR OBJPROC_9PARAMTWO_NR)
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_GUARD
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YED_CSEESWSDSEQA_37W_TRIGGER
 (= OBJPROC_9ATTRNEIGHBOURR (YESTERDAY OBJPROC_9PARAMONE_NR))
 (= OBJPROC_0PARAMTWO_NR (YESTERDAY OBJPROC_9PARAMONE_NR))
 OBJPROC_0OPTWOTR_D-YEDUCSEESWSDSEQA_37W_CALL
 (= OBJPROC_9PARAMONE_NR OBJPROC_9ATTRMAX) (= OBJPROC_9ATTRACTIVE 1)
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D-YEEECSEESWSDSEQA_37W
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D-YEEOCSEESWSDSEQA_37W
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D-YEDECSEESWSDSEQA_37W
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D-YEDOCSEESWSDSEQA_37W
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D-YED-CSEESWSDSEQA_37W
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D-YEDUCSEESWSDSEQA_37W
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_GUARD
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D_YEDUCSEESWSDSEQA_37W_TRIGGER
 OBJPROC_9_STDPROCESS_SM_STATELOST_EXIT OBJPROC_9_STDPROCESS_SM_STATELOST_ENTER
 $OBJPROC_9_STDPROCESS_SM_STATELOST OBJPROC_9_STDPROCESS_SM_STATEINIT_EXIT
 OBJPROC_9_STDPROCESS_SM_STATEINIT_ENTER $OBJPROC_9_STDPROCESS_SM_STATEINIT
 OBJPROC_9_STDPROCESS_SM_STATEWIN_EXIT OBJPROC_9_STDPROCESS_SM_STATEWIN_ENTER
 $OBJPROC_9_STDPROCESS_SM_STATEWIN
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D-YEEUCSEESWSDSEQA_37W
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D-YEE-CSEESWSDSEQA_37W
 OBJPROC_9_STDPROCESS_SM_STATEMAIN_EXIT
 OBJPROC_9_STDPROCESS_SM_TRANSITION_D-YEC-CSEESWSDSEQA_37W
 OBJPROC_9_STDPROCESS_SM_STATEMAIN_ENTER $OBJPROC_9_STDPROCESS_SM_STATEMAIN
 MADESYSTEMSTART (= OBJPROC_9ATTRMAX (YESTERDAY OBJPROC_9ATTRMAX))
 OBJPROC_9ASSIGNMENT_D-YEC-CSEESWSDSEQA_37WMAX
 OBJPROC_9ASSIGNMENT_D-YED-CSEESWSDSEQA_37WMAX
 (= OBJPROC_9ATTRNEIGHBOURR (YESTERDAY OBJPROC_9ATTRNEIGHBOURR))
 OBJPROC_9ASSIGNMENT_D-YEDUCSEESWSDSEQA_37WNEIGHBOURR
 (= OBJPROC_9ATTRMYNUMBER (YESTERDAY OBJPROC_9ATTRMYNUMBER))
 (= OBJPROC_9ATTRACTIVE (YESTERDAY OBJPROC_9ATTRACTIVE))
 OBJPROC_9ASSIGNMENT_D-YEEOCSEESWSDSEQA_37WACTIVE
 OBJPROC_9OPTWOTR_D-YEDUCSEESWSDSEQA_37W_CALL
 OBJPROC_9OPTWOTR_D-YEDECSEESWSDSEQA_37W_CALL OBJPROC_9OPTWO
 OBJPROC_9OPWINNERTR_D-YEEUCSEESWSDSEQA_37W_CALL
 OBJPROC_9OPWINNERTR_D-YEE-CSEESWSDSEQA_37W_CALL
 OBJPROC_9OPWINNERTR_D-YEEECSEESWSDSEQA_37W_CALL OBJPROC_9OPWINNER
 OBJPROC_9OPONETR_D-YED-CSEESWSDSEQA_37W_CALL
 OBJPROC_9OPONETR_D-YEC-CSEESWSDSEQA_37W_CALL
 OBJPROC_9OPONETR_D-YEDOCSEESWSDSEQA_37W_CALL OBJPROC_9OPONE
 OBJPROC_1OPWE_HAVE_WINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_7OPWE_HAVE_WINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_4OPWE_HAVE_WINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_8OPWE_HAVE_WINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_2OPWE_HAVE_WINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_3OPWE_HAVE_WINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_0OPWE_HAVE_WINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_5OPWE_HAVE_WINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_6OPWE_HAVE_WINNERTR_D-YEEECSEESWSDSEQA_37W_CALL
 OBJPROC_9OPWE_HAVE_WINNERTR_D-YEEECSEESWSDSEQA_37W_CALL WE_HAVE_WINNER)

Used arithmetic terms: 
NIL

Used timed arithmetic terms: 
(OBJPROC_1ATTRMAX OBJPROC_1ATTRNEIGHBOURR OBJPROC_1ATTRMYNUMBER
 OBJPROC_1ATTRACTIVE OBJPROC_7ATTRMAX OBJPROC_7ATTRNEIGHBOURR
 OBJPROC_7ATTRMYNUMBER OBJPROC_7ATTRACTIVE OBJPROC_4ATTRMAX
 OBJPROC_4ATTRNEIGHBOURR OBJPROC_4ATTRMYNUMBER OBJPROC_4ATTRACTIVE
 OBJPROC_8PARAMWIN_NR OBJPROC_8PARAMTWO_NR OBJPROC_8PARAMONE_NR
 OBJPROC_8ATTRMAX OBJPROC_8ATTRNEIGHBOURR OBJPROC_8ATTRMYNUMBER
 OBJPROC_8ATTRACTIVE OBJPROC_2PARAMWIN_NR OBJPROC_2PARAMTWO_NR
 OBJPROC_2PARAMONE_NR OBJPROC_2ATTRMAX OBJPROC_2ATTRNEIGHBOURR
 OBJPROC_2ATTRMYNUMBER OBJPROC_2ATTRACTIVE OBJPROC_4PARAMWIN_NR
 OBJPROC_3PARAMWIN_NR OBJPROC_4PARAMONE_NR OBJPROC_3PARAMTWO_NR
 OBJPROC_4PARAMTWO_NR OBJPROC_3PARAMONE_NR OBJPROC_3ATTRMAX
 OBJPROC_3ATTRNEIGHBOURR OBJPROC_3ATTRMYNUMBER OBJPROC_3ATTRACTIVE
 OBJPROC_1PARAMWIN_NR OBJPROC_1PARAMONE_NR OBJPROC_1PARAMTWO_NR
 OBJPROC_0ATTRMAX OBJPROC_0ATTRNEIGHBOURR OBJPROC_0ATTRMYNUMBER
 OBJPROC_0ATTRACTIVE OBJPROC_5PARAMWIN_NR OBJPROC_5PARAMTWO_NR
 OBJPROC_5PARAMONE_NR OBJPROC_5ATTRMAX OBJPROC_5ATTRNEIGHBOURR
 OBJPROC_5ATTRMYNUMBER OBJPROC_5ATTRACTIVE OBJPROC_7PARAMWIN_NR
 OBJPROC_6PARAMWIN_NR OBJPROC_7PARAMONE_NR OBJPROC_6PARAMTWO_NR
 OBJPROC_7PARAMTWO_NR OBJPROC_6PARAMONE_NR OBJPROC_6ATTRMAX
 OBJPROC_6ATTRNEIGHBOURR OBJPROC_6ATTRMYNUMBER OBJPROC_6ATTRACTIVE
 OBJPROC_0PARAMWIN_NR OBJPROC_9PARAMWIN_NR OBJPROC_0PARAMONE_NR
 OBJPROC_9PARAMTWO_NR OBJPROC_0PARAMTWO_NR OBJPROC_9PARAMONE_NR
 OBJPROC_9ATTRMAX OBJPROC_9ATTRNEIGHBOURR OBJPROC_9ATTRMYNUMBER
 OBJPROC_9ATTRACTIVE)

Graph dependency over terms 
(((YESTERDAY OBJPROC_9ATTRACTIVE) OBJPROC_9ATTRACTIVE
  (YESTERDAY OBJPROC_6ATTRACTIVE) 1 (YESTERDAY OBJPROC_5ATTRACTIVE) 1
  (YESTERDAY OBJPROC_0ATTRACTIVE) 1 (YESTERDAY OBJPROC_3ATTRACTIVE) 1
  (YESTERDAY OBJPROC_2ATTRACTIVE) 1 (YESTERDAY OBJPROC_8ATTRACTIVE) 1
  (YESTERDAY OBJPROC_4ATTRACTIVE) 1 (YESTERDAY OBJPROC_7ATTRACTIVE) 1
  OBJPROC_9ATTRACTIVE OBJPROC_6ATTRACTIVE OBJPROC_5ATTRACTIVE
  OBJPROC_0ATTRACTIVE OBJPROC_3ATTRACTIVE OBJPROC_2ATTRACTIVE
  OBJPROC_8ATTRACTIVE OBJPROC_4ATTRACTIVE OBJPROC_7ATTRACTIVE
  (YESTERDAY OBJPROC_1ATTRACTIVE) 1 0 OBJPROC_1ATTRACTIVE)
 ((YESTERDAY OBJPROC_9ATTRMYNUMBER) (YESTERDAY OBJPROC_9ATTRNEIGHBOURR)
  (YESTERDAY OBJPROC_9ATTRMAX) OBJPROC_9ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_9ATTRNEIGHBOURR) OBJPROC_9ATTRMYNUMBER
  OBJPROC_9ATTRNEIGHBOURR OBJPROC_9ATTRMAX OBJPROC_9ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_9PARAMONE_NR) (YESTERDAY OBJPROC_9PARAMTWO_NR)
  OBJPROC_9ATTRNEIGHBOURR OBJPROC_9ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_8PARAMTWO_NR) (YESTERDAY OBJPROC_9ATTRNEIGHBOURR)
  OBJPROC_9ATTRMYNUMBER (YESTERDAY OBJPROC_9PARAMONE_NR) OBJPROC_9ATTRMYNUMBER
  (YESTERDAY OBJPROC_8PARAMWIN_NR) (YESTERDAY OBJPROC_9PARAMWIN_NR)
  (YESTERDAY OBJPROC_9PARAMONE_NR) (YESTERDAY OBJPROC_6ATTRMYNUMBER)
  OBJPROC_9ATTRMYNUMBER (YESTERDAY OBJPROC_6ATTRNEIGHBOURR)
  (YESTERDAY OBJPROC_6ATTRMAX) OBJPROC_6ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_6ATTRNEIGHBOURR) OBJPROC_6ATTRMYNUMBER
  OBJPROC_6ATTRNEIGHBOURR OBJPROC_6ATTRMAX OBJPROC_6ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_6PARAMONE_NR) (YESTERDAY OBJPROC_6PARAMTWO_NR)
  OBJPROC_6ATTRNEIGHBOURR OBJPROC_6ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_5PARAMTWO_NR) (YESTERDAY OBJPROC_6ATTRNEIGHBOURR)
  OBJPROC_6ATTRMYNUMBER (YESTERDAY OBJPROC_6PARAMONE_NR) OBJPROC_6ATTRMYNUMBER
  (YESTERDAY OBJPROC_5PARAMWIN_NR) (YESTERDAY OBJPROC_6PARAMWIN_NR)
  (YESTERDAY OBJPROC_6PARAMONE_NR) (YESTERDAY OBJPROC_5ATTRMYNUMBER)
  OBJPROC_6PARAMONE_NR OBJPROC_6ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER
  OBJPROC_6PARAMONE_NR OBJPROC_6PARAMTWO_NR OBJPROC_6PARAMONE_NR
  OBJPROC_6PARAMWIN_NR (YESTERDAY OBJPROC_5ATTRNEIGHBOURR)
  (YESTERDAY OBJPROC_5PARAMONE_NR) (YESTERDAY OBJPROC_5ATTRMAX)
  OBJPROC_5ATTRNEIGHBOURR (YESTERDAY OBJPROC_5ATTRNEIGHBOURR)
  OBJPROC_5ATTRMYNUMBER OBJPROC_5ATTRNEIGHBOURR OBJPROC_5ATTRMAX
  OBJPROC_5ATTRNEIGHBOURR OBJPROC_5ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_4PARAMTWO_NR) OBJPROC_5ATTRMYNUMBER
  (YESTERDAY OBJPROC_4PARAMWIN_NR) (YESTERDAY OBJPROC_0ATTRMYNUMBER)
  OBJPROC_0PARAMWIN_NR OBJPROC_5ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER
  OBJPROC_9ATTRMYNUMBER (YESTERDAY OBJPROC_0ATTRMAX) OBJPROC_0PARAMONE_NR
  (YESTERDAY OBJPROC_0ATTRNEIGHBOURR) OBJPROC_0ATTRMYNUMBER
  (YESTERDAY OBJPROC_0ATTRNEIGHBOURR) OBJPROC_0PARAMTWO_NR OBJPROC_0ATTRMAX
  OBJPROC_0PARAMTWO_NR OBJPROC_0ATTRMAX OBJPROC_0ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_0PARAMONE_NR) (YESTERDAY OBJPROC_0PARAMTWO_NR)
  (YESTERDAY OBJPROC_0ATTRNEIGHBOURR) OBJPROC_0ATTRMYNUMBER
  (YESTERDAY OBJPROC_0PARAMONE_NR) (YESTERDAY OBJPROC_0PARAMWIN_NR)
  (YESTERDAY OBJPROC_0PARAMONE_NR) (YESTERDAY OBJPROC_3ATTRMYNUMBER)
  OBJPROC_0ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER
  OBJPROC_9ATTRMYNUMBER (YESTERDAY OBJPROC_3ATTRNEIGHBOURR)
  (YESTERDAY OBJPROC_3ATTRMAX) OBJPROC_3ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_3ATTRNEIGHBOURR) OBJPROC_3ATTRMYNUMBER
  OBJPROC_3ATTRNEIGHBOURR OBJPROC_3ATTRMAX OBJPROC_3ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_3PARAMONE_NR) (YESTERDAY OBJPROC_3PARAMTWO_NR)
  OBJPROC_3ATTRNEIGHBOURR OBJPROC_3ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_2PARAMTWO_NR) (YESTERDAY OBJPROC_3ATTRNEIGHBOURR)
  OBJPROC_3ATTRMYNUMBER (YESTERDAY OBJPROC_3PARAMONE_NR) OBJPROC_3ATTRMYNUMBER
  (YESTERDAY OBJPROC_2PARAMWIN_NR) (YESTERDAY OBJPROC_3PARAMWIN_NR)
  (YESTERDAY OBJPROC_3PARAMONE_NR) (YESTERDAY OBJPROC_2ATTRMYNUMBER)
  OBJPROC_3PARAMONE_NR OBJPROC_0ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER
  OBJPROC_5ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER
  OBJPROC_3PARAMONE_NR OBJPROC_3PARAMTWO_NR OBJPROC_3PARAMONE_NR
  OBJPROC_3PARAMWIN_NR (YESTERDAY OBJPROC_2ATTRNEIGHBOURR)
  (YESTERDAY OBJPROC_2PARAMONE_NR) (YESTERDAY OBJPROC_2ATTRMAX)
  OBJPROC_2ATTRNEIGHBOURR (YESTERDAY OBJPROC_2ATTRNEIGHBOURR)
  OBJPROC_2ATTRMYNUMBER OBJPROC_2ATTRNEIGHBOURR OBJPROC_2ATTRMAX
  OBJPROC_2ATTRMYNUMBER (YESTERDAY OBJPROC_1PARAMWIN_NR)
  (YESTERDAY OBJPROC_8ATTRMYNUMBER) OBJPROC_9PARAMONE_NR OBJPROC_0ATTRMYNUMBER
  OBJPROC_2ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER
  OBJPROC_6ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER OBJPROC_9PARAMONE_NR
  OBJPROC_9PARAMTWO_NR OBJPROC_9PARAMONE_NR OBJPROC_9PARAMWIN_NR
  (YESTERDAY OBJPROC_8ATTRNEIGHBOURR) (YESTERDAY OBJPROC_8PARAMONE_NR)
  (YESTERDAY OBJPROC_8ATTRMAX) OBJPROC_8ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_8ATTRNEIGHBOURR) OBJPROC_8ATTRMYNUMBER
  OBJPROC_8ATTRNEIGHBOURR OBJPROC_8ATTRMAX OBJPROC_8ATTRNEIGHBOURR
  OBJPROC_8ATTRNEIGHBOURR (YESTERDAY OBJPROC_7PARAMTWO_NR)
  OBJPROC_8ATTRMYNUMBER (YESTERDAY OBJPROC_7PARAMWIN_NR) OBJPROC_5PARAMONE_NR
  OBJPROC_5PARAMTWO_NR OBJPROC_5PARAMONE_NR OBJPROC_5PARAMWIN_NR
  (YESTERDAY OBJPROC_4ATTRNEIGHBOURR) (YESTERDAY OBJPROC_4PARAMONE_NR)
  OBJPROC_4PARAMTWO_NR OBJPROC_4PARAMTWO_NR (YESTERDAY OBJPROC_4ATTRMAX)
  OBJPROC_4PARAMONE_NR OBJPROC_4ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_4ATTRNEIGHBOURR) OBJPROC_4ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_4ATTRMYNUMBER) OBJPROC_5PARAMONE_NR OBJPROC_4ATTRMAX
  OBJPROC_4PARAMWIN_NR OBJPROC_0ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER
  OBJPROC_3ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER
  OBJPROC_8ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER OBJPROC_8PARAMONE_NR
  OBJPROC_8PARAMTWO_NR OBJPROC_8PARAMONE_NR OBJPROC_8PARAMWIN_NR
  (YESTERDAY OBJPROC_7ATTRNEIGHBOURR) (YESTERDAY OBJPROC_7PARAMONE_NR)
  OBJPROC_7PARAMTWO_NR OBJPROC_7PARAMTWO_NR (YESTERDAY OBJPROC_7ATTRMAX)
  OBJPROC_7PARAMONE_NR OBJPROC_7ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_7ATTRNEIGHBOURR) OBJPROC_7ATTRNEIGHBOURR
  (YESTERDAY OBJPROC_7ATTRMYNUMBER) OBJPROC_8PARAMONE_NR OBJPROC_7ATTRMAX
  OBJPROC_7PARAMWIN_NR OBJPROC_0ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER
  OBJPROC_3ATTRMYNUMBER OBJPROC_4ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER
  OBJPROC_6ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER
  (YESTERDAY OBJPROC_1ATTRMYNUMBER) OBJPROC_2PARAMONE_NR OBJPROC_1PARAMWIN_NR
  OBJPROC_0ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER
  OBJPROC_4ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER
  OBJPROC_7ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER
  OBJPROC_2PARAMONE_NR (YESTERDAY OBJPROC_1ATTRMAX) OBJPROC_1PARAMONE_NR
  (YESTERDAY OBJPROC_1ATTRNEIGHBOURR) OBJPROC_1ATTRMYNUMBER
  (YESTERDAY OBJPROC_1ATTRNEIGHBOURR) OBJPROC_1PARAMTWO_NR OBJPROC_1ATTRMAX
  OBJPROC_1PARAMTWO_NR OBJPROC_1ATTRMAX OBJPROC_1ATTRNEIGHBOURR
  OBJPROC_2PARAMONE_NR OBJPROC_2PARAMWIN_NR OBJPROC_2ATTRNEIGHBOURR
  OBJPROC_2ATTRNEIGHBOURR (YESTERDAY OBJPROC_1PARAMONE_NR) OBJPROC_2PARAMTWO_NR
  (YESTERDAY OBJPROC_1PARAMTWO_NR)))

Related variables 
((OBJPROC_9ATTRACTIVE OBJPROC_6ATTRACTIVE OBJPROC_5ATTRACTIVE
  OBJPROC_0ATTRACTIVE OBJPROC_3ATTRACTIVE OBJPROC_2ATTRACTIVE
  OBJPROC_8ATTRACTIVE OBJPROC_4ATTRACTIVE OBJPROC_7ATTRACTIVE 1 0
  OBJPROC_1ATTRACTIVE)
 (OBJPROC_9ATTRMAX OBJPROC_9ATTRNEIGHBOURR OBJPROC_6ATTRMAX
  OBJPROC_6ATTRNEIGHBOURR OBJPROC_6PARAMTWO_NR OBJPROC_6PARAMONE_NR
  OBJPROC_6PARAMWIN_NR OBJPROC_5ATTRMAX OBJPROC_5ATTRNEIGHBOURR
  OBJPROC_0ATTRMAX OBJPROC_0PARAMTWO_NR OBJPROC_0ATTRNEIGHBOURR
  OBJPROC_0PARAMWIN_NR OBJPROC_0PARAMONE_NR OBJPROC_3ATTRMAX
  OBJPROC_3ATTRNEIGHBOURR OBJPROC_3PARAMTWO_NR OBJPROC_3PARAMONE_NR
  OBJPROC_3PARAMWIN_NR OBJPROC_2ATTRMAX OBJPROC_9PARAMTWO_NR
  OBJPROC_9PARAMONE_NR OBJPROC_9PARAMWIN_NR OBJPROC_8ATTRMAX
  OBJPROC_8ATTRNEIGHBOURR OBJPROC_5PARAMTWO_NR OBJPROC_5PARAMWIN_NR
  OBJPROC_4PARAMTWO_NR OBJPROC_4PARAMONE_NR OBJPROC_4ATTRNEIGHBOURR
  OBJPROC_5PARAMONE_NR OBJPROC_4ATTRMAX OBJPROC_4PARAMWIN_NR
  OBJPROC_8PARAMTWO_NR OBJPROC_8PARAMWIN_NR OBJPROC_7PARAMTWO_NR
  OBJPROC_7PARAMONE_NR OBJPROC_7ATTRNEIGHBOURR OBJPROC_8PARAMONE_NR
  OBJPROC_7ATTRMAX OBJPROC_7PARAMWIN_NR OBJPROC_1PARAMWIN_NR
  OBJPROC_0ATTRMYNUMBER OBJPROC_2ATTRMYNUMBER OBJPROC_3ATTRMYNUMBER
  OBJPROC_4ATTRMYNUMBER OBJPROC_5ATTRMYNUMBER OBJPROC_6ATTRMYNUMBER
  OBJPROC_7ATTRMYNUMBER OBJPROC_8ATTRMYNUMBER OBJPROC_9ATTRMYNUMBER
  OBJPROC_1ATTRMYNUMBER OBJPROC_1ATTRMAX OBJPROC_1ATTRNEIGHBOURR
  OBJPROC_2PARAMONE_NR OBJPROC_2PARAMWIN_NR OBJPROC_2ATTRNEIGHBOURR
  OBJPROC_1PARAMONE_NR OBJPROC_2PARAMTWO_NR OBJPROC_1PARAMTWO_NR))

Time bound: 50

Number of Boolean variables: 
565
define FO future formulae Xt
define FO future formulae Yt
define for interpreted relations: <,>,=,<=,>= 
define FO terms for +,-,*,/,mod 
define loop constraints

done processing formula
define LTL future formulae X, U, R
define LTL future formulae X, U, R
gen-past2...
gen-past2...
define LTL boolean connectives
define LTL boolean connectives

no CNF
  0.000 seconds of real time

2. SMT solving: z3...
 
Evaluation took:
  62.543 seconds of real time
  0.004000 seconds of total run time (0.000000 user, 0.004000 system)
  0.01% CPU
  212,645,773,964 processor cycles
  32,768 bytes consed
  
---SAT---
------ time 0 ------
Evaluation took:
  66.147 seconds of real time
  3.604000 seconds of total run time (3.224000 user, 0.380000 system)
  [ Run times consist of 0.412 seconds GC time, and 3.192 seconds non-GC time. ]
  5.45% CPU
  224,900,153,766 processor cycles
  13,678,646,560 bytes consed
  
  before it was aborted by a non-local transfer of control.
  
